"""
Audio coach TTS service.

Google Cloud Text-to-Speech wrapper that takes a coach-persona-voiced
script (generated by `services/gemini/body_analyzer.py::generate_audio_coach_script`)
and returns MP3 bytes. Caches the resulting MP3 in S3 so replays never
re-synthesize.

Persona → voice mapping lives here (not in the model layer) so we can tune
voices without changing the Gemini prompt.
"""
from __future__ import annotations

import asyncio
import logging
from typing import Optional, Tuple

from core.config import get_settings

logger = logging.getLogger("audio_coach")


# Map coach_persona_id → (voice_name, speaking_rate, pitch).
# Voices are Google Cloud TTS en-US neural2 — high quality, low-latency.
# If a persona isn't mapped, default to en-US-Neural2-F (warm female).
_PERSONA_VOICE_MAP = {
    "default":     ("en-US-Neural2-F",  1.00,  0.0),
    "alex":        ("en-US-Neural2-D",  1.05,  -1.0),  # coach-bro energy
    "sam":         ("en-US-Neural2-I",  0.98,  -2.0),  # stoic senior
    "maya":        ("en-US-Neural2-F",  1.02,  1.0),   # encouraging
    "kai":         ("en-US-Neural2-A",  1.00,  -0.5),  # balanced male
    "hype_danny":  ("en-US-Neural2-J",  1.10,  0.5),   # hype bro
    "gentle_jen":  ("en-US-Neural2-H",  0.95,  2.0),   # soft-spoken
    "drill_sgt":   ("en-US-Neural2-D",  1.15,  -3.0),  # harsh
}


def _persona_voice(persona_id: Optional[str]) -> Tuple[str, float, float]:
    """Resolve persona → TTS voice settings with a safe default."""
    if persona_id and persona_id in _PERSONA_VOICE_MAP:
        return _PERSONA_VOICE_MAP[persona_id]
    return _PERSONA_VOICE_MAP["default"]


async def synthesize_coach_brief(
    *,
    script_text: str,
    coach_persona_id: Optional[str] = None,
) -> bytes:
    """Synthesize MP3 bytes for a short coach brief.

    Runs the blocking TTS client in a thread-pool so we don't block the
    event loop. Returns raw MP3 bytes; the caller is responsible for
    uploading to S3 and persisting the key.
    """
    try:
        # Lazy import — keeps the dep optional for dev.
        from google.cloud import texttospeech
    except ImportError:
        logger.warning(
            "google-cloud-texttospeech not installed; audio coach disabled"
        )
        raise RuntimeError(
            "Audio coach is not configured on this backend. "
            "Install google-cloud-texttospeech to enable."
        )

    voice_name, rate, pitch = _persona_voice(coach_persona_id)

    def _synth() -> bytes:
        client = texttospeech.TextToSpeechClient()
        input_ = texttospeech.SynthesisInput(text=script_text)
        voice = texttospeech.VoiceSelectionParams(
            language_code="en-US",
            name=voice_name,
        )
        audio_config = texttospeech.AudioConfig(
            audio_encoding=texttospeech.AudioEncoding.MP3,
            speaking_rate=rate,
            pitch=pitch,
        )
        resp = client.synthesize_speech(
            input=input_, voice=voice, audio_config=audio_config,
        )
        return resp.audio_content

    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(None, _synth)


async def upload_brief_mp3(
    *,
    user_id: str,
    brief_date_iso: str,
    mp3_bytes: bytes,
) -> Tuple[str, str]:
    """Upload MP3 to S3 at audio_coach/{user_id}/{date}.mp3.

    Returns (s3_key, signed_url_valid_24h).
    """
    import boto3
    settings = get_settings()
    bucket = getattr(settings, "s3_bucket_name", None)
    if not bucket:
        raise RuntimeError("S3 not configured; audio coach cannot persist")

    client = boto3.client(
        "s3",
        region_name=getattr(settings, "s3_region", "us-east-1"),
        aws_access_key_id=getattr(settings, "s3_access_key_id", None),
        aws_secret_access_key=getattr(settings, "s3_secret_access_key", None),
    )
    s3_key = f"audio_coach/{user_id}/{brief_date_iso}.mp3"

    loop = asyncio.get_running_loop()
    await loop.run_in_executor(
        None,
        lambda: client.put_object(
            Bucket=bucket,
            Key=s3_key,
            Body=mp3_bytes,
            ContentType="audio/mpeg",
            CacheControl="private, max-age=86400",
        ),
    )
    signed_url = await loop.run_in_executor(
        None,
        lambda: client.generate_presigned_url(
            "get_object",
            Params={"Bucket": bucket, "Key": s3_key},
            ExpiresIn=86400,  # 24 h
        ),
    )
    return s3_key, signed_url


def get_signed_url_for_key(s3_key: str, expires: int = 86400) -> str:
    """Re-sign an existing MP3 key (used when the cached row is re-served)."""
    import boto3
    settings = get_settings()
    bucket = getattr(settings, "s3_bucket_name", None)
    client = boto3.client(
        "s3",
        region_name=getattr(settings, "s3_region", "us-east-1"),
        aws_access_key_id=getattr(settings, "s3_access_key_id", None),
        aws_secret_access_key=getattr(settings, "s3_secret_access_key", None),
    )
    return client.generate_presigned_url(
        "get_object",
        Params={"Bucket": bucket, "Key": s3_key},
        ExpiresIn=expires,
    )
