"""
Final comprehensive program list generator - 250+ programs
This script consolidates all program definitions
"""
import json

# Import the existing catalogs
from build_program_catalog import (
    YOGA_PROGRAMS,
    STRETCHING_PROGRAMS,
    PAIN_MANAGEMENT_PROGRAMS,
    SPORT_SPECIFIC_PROGRAMS,
    ADDITIONAL_GOAL_PROGRAMS
)

# Additional 100+ programs to reach 250+

ADDITIONAL_WOMEN_PROGRAMS = [
    {
        "program_name": "Women's Marathon Training",
        "program_category": "Women's Health",
        "program_subcategory": "Endurance",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 16,
        "sessions_per_week": 5,
        "session_duration_minutes": 90,
        "tags": ["Women", "Running", "Marathon"],
        "goals": ["Endurance", "Athletic Performance"],
        "description": "Complete marathon training program designed specifically for women runners.",
        "short_description": "Women's marathon prep"
    },
    {
        "program_name": "Women's CrossFit Introduction",
        "program_category": "Women's Health",
        "program_subcategory": "CrossFit",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 10,
        "sessions_per_week": 4,
        "session_duration_minutes": 60,
        "tags": ["Women", "CrossFit", "Functional"],
        "goals": ["Athletic Performance", "Build Muscle"],
        "description": "Introduction to CrossFit-style training tailored for women with scaled movements.",
        "short_description": "Women's CrossFit intro"
    },
    {
        "program_name": "Bridal Bootcamp 12-Week",
        "program_category": "Women's Health",
        "program_subcategory": "Special Events",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 12,
        "sessions_per_week": 5,
        "session_duration_minutes": 50,
        "tags": ["Women", "Wedding", "Transformation"],
        "goals": ["Lose Fat", "Toning"],
        "description": "Get in shape for your wedding day with targeted toning and fat loss program.",
        "short_description": "Bridal transformation"
    },
    {
        "program_name": "Women's Kickboxing Fitness",
        "program_category": "Women's Health",
        "program_subcategory": "Martial Arts",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 10,
        "sessions_per_week": 4,
        "session_duration_minutes": 55,
        "tags": ["Women", "Kickboxing", "Cardio"],
        "goals": ["Lose Fat", "Conditioning"],
        "description": "High-energy kickboxing workout for women combining cardio and strength.",
        "short_description": "Women's kickboxing"
    },
    {
        "program_name": "Women's Pilates Core Strength",
        "program_category": "Women's Health",
        "program_subcategory": "Pilates",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 8,
        "sessions_per_week": 3,
        "session_duration_minutes": 45,
        "tags": ["Women", "Pilates", "Core"],
        "goals": ["Core Strength", "Posture"],
        "description": "Build core strength, improve posture, and enhance body awareness through Pilates.",
        "short_description": "Women's Pilates core"
    },
]

ADDITIONAL_MEN_PROGRAMS = [
    {
        "program_name": "Men's Beach Body Summer Prep",
        "program_category": "Men's Health",
        "program_subcategory": "Aesthetic Goals",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 12,
        "sessions_per_week": 5,
        "session_duration_minutes": 60,
        "tags": ["Men", "Beach Body", "Fat Loss"],
        "goals": ["Lose Fat", "Build Muscle"],
        "description": "Get ready for beach season with fat loss and muscle definition program.",
        "short_description": "Summer beach body"
    },
    {
        "program_name": "Men's Olympic Weightlifting",
        "program_category": "Men's Health",
        "program_subcategory": "Olympic Lifting",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 4,
        "session_duration_minutes": 75,
        "tags": ["Men", "Olympic", "Power"],
        "goals": ["Increase Strength", "Power"],
        "description": "Learn Olympic weightlifting technique with snatch, clean & jerk progressions.",
        "short_description": "Olympic weightlifting"
    },
    {
        "program_name": "Men's Endurance Athlete Training",
        "program_category": "Men's Health",
        "program_subcategory": "Endurance",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 16,
        "sessions_per_week": 6,
        "session_duration_minutes": 90,
        "tags": ["Men", "Endurance", "Triathlon"],
        "goals": ["Endurance", "Athletic Performance"],
        "description": "Build exceptional endurance for long-distance running, cycling, or triathlon.",
        "short_description": "Men's endurance training"
    },
]

MORE_CELEBRITY_PROGRAMS = [
    {
        "program_name": "Scarlett Johansson Black Widow Training",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Superhero Training",
        "country": ["Global"],
        "celebrity_name": "Scarlett Johansson",
        "difficulty_level": "Advanced",
        "duration_weeks": 10,
        "sessions_per_week": 6,
        "session_duration_minutes": 90,
        "tags": ["Celebrity", "Women", "Martial Arts"],
        "goals": ["Athletic Performance", "Build Muscle"],
        "description": "Train like Black Widow with martial arts, strength training, and agility work.",
        "short_description": "Black Widow training"
    },
    {
        "program_name": "Brie Larson Captain Marvel Workout",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Superhero Training",
        "country": ["Global"],
        "celebrity_name": "Brie Larson",
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 5,
        "session_duration_minutes": 75,
        "tags": ["Celebrity", "Women", "Strength"],
        "goals": ["Build Muscle", "Increase Strength"],
        "description": "Build superhero strength like Captain Marvel through heavy lifting and functional training.",
        "short_description": "Captain Marvel strength"
    },
    {
        "program_name": "Jason Statham Action Star Fitness",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Action Hero",
        "country": ["Global"],
        "celebrity_name": "Jason Statham",
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 6,
        "session_duration_minutes": 60,
        "tags": ["Celebrity", "Functional", "Athletic"],
        "goals": ["Athletic Performance", "Build Muscle"],
        "description": "Train like an action star with varied, functional, never-repeat workouts.",
        "short_description": "Action star training"
    },
    {
        "program_name": "Vin Diesel Fast & Furious Build",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Action Hero",
        "country": ["Global"],
        "celebrity_name": "Vin Diesel",
        "difficulty_level": "Intermediate",
        "duration_weeks": 10,
        "sessions_per_week": 5,
        "session_duration_minutes": 70,
        "tags": ["Celebrity", "Muscle", "Power"],
        "goals": ["Build Muscle", "Increase Strength"],
        "description": "Build muscle mass and power like Vin Diesel with strength-focused training.",
        "short_description": "Fast & Furious build"
    },
    {
        "program_name": "Sylvester Stallone Rocky Training",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Boxing",
        "country": ["Global"],
        "celebrity_name": "Sylvester Stallone",
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 6,
        "session_duration_minutes": 90,
        "tags": ["Celebrity", "Boxing", "Conditioning"],
        "goals": ["Athletic Performance", "Build Muscle"],
        "description": "Train like Rocky with old-school boxing conditioning and strength training.",
        "short_description": "Rocky-style training"
    },
    {
        "program_name": "Terry Crews Power Athlete Training",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Power Training",
        "country": ["Global"],
        "celebrity_name": "Terry Crews",
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 6,
        "session_duration_minutes": 75,
        "tags": ["Celebrity", "Power", "Muscle"],
        "goals": ["Build Muscle", "Power"],
        "description": "Build explosive power and muscle like Terry Crews through intense training.",
        "short_description": "Terry Crews power"
    },
    {
        "program_name": "Jennifer Lopez Dance Fitness",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Dance Fitness",
        "country": ["Global"],
        "celebrity_name": "Jennifer Lopez",
        "difficulty_level": "Intermediate",
        "duration_weeks": 10,
        "sessions_per_week": 5,
        "session_duration_minutes": 60,
        "tags": ["Celebrity", "Dance", "Women"],
        "goals": ["Toning", "Conditioning"],
        "description": "Stay fit and toned through dance-based cardio and strength training like JLo.",
        "short_description": "JLo dance fitness"
    },
    {
        "program_name": "Matthew McConaughey Beach Body",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Beach Physique",
        "country": ["Global"],
        "celebrity_name": "Matthew McConaughey",
        "difficulty_level": "Intermediate",
        "duration_weeks": 8,
        "sessions_per_week": 4,
        "session_duration_minutes": 60,
        "tags": ["Celebrity", "Beach Body", "Lean"],
        "goals": ["Lose Fat", "Toning"],
        "description": "Achieve a lean, beach-ready physique through surf-inspired functional training.",
        "short_description": "Beach body lean"
    },
    {
        "program_name": "Gal Gadot Athletic Grace Training",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Superhero Training",
        "country": ["Global"],
        "celebrity_name": "Gal Gadot",
        "difficulty_level": "Intermediate",
        "duration_weeks": 10,
        "sessions_per_week": 5,
        "session_duration_minutes": 60,
        "tags": ["Celebrity", "Women", "Athletic"],
        "goals": ["Athletic Performance", "Toning"],
        "description": "Build athletic grace and strength like Wonder Woman through varied training.",
        "short_description": "Athletic grace training"
    },
    {
        "program_name": "Mark Wahlberg F45 Style Training",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Functional Training",
        "country": ["Global"],
        "celebrity_name": "Mark Wahlberg",
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 6,
        "session_duration_minutes": 45,
        "tags": ["Celebrity", "HIIT", "Functional"],
        "goals": ["Lose Fat", "Build Muscle"],
        "description": "High-intensity functional training inspired by Mark Wahlberg's early morning workouts.",
        "short_description": "F45-style intensity"
    },
]

MORE_INDIAN_PROGRAMS = [
    {
        "program_name": "Alia Bhatt Fitness Routine",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Bollywood Fitness",
        "country": ["India"],
        "celebrity_name": "Alia Bhatt",
        "difficulty_level": "Intermediate",
        "duration_weeks": 8,
        "sessions_per_week": 5,
        "session_duration_minutes": 60,
        "tags": ["Bollywood", "Women", "Balanced"],
        "goals": ["Toning", "Fitness"],
        "description": "Balanced fitness routine combining yoga, pilates, and strength training like Alia Bhatt.",
        "short_description": "Alia's balanced fitness"
    },
    {
        "program_name": "Vidyut Jammwal Martial Arts Training",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Bollywood Fitness",
        "country": ["India"],
        "celebrity_name": "Vidyut Jammwal",
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 6,
        "session_duration_minutes": 90,
        "tags": ["Bollywood", "Martial Arts", "Kalaripayattu"],
        "goals": ["Athletic Performance", "Martial Arts"],
        "description": "Master Kalaripayattu and functional fitness like Vidyut Jammwal.",
        "short_description": "Kalaripayattu training"
    },
    {
        "program_name": "Milind Soman Ultra Endurance",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Bollywood Fitness",
        "country": ["India"],
        "celebrity_name": "Milind Soman",
        "difficulty_level": "Advanced",
        "duration_weeks": 16,
        "sessions_per_week": 6,
        "session_duration_minutes": 120,
        "tags": ["Bollywood", "Endurance", "Ultra Running"],
        "goals": ["Endurance", "Athletic Performance"],
        "description": "Build ultra-endurance capacity like Milind Soman through long-distance training.",
        "short_description": "Ultra endurance training"
    },
    {
        "program_name": "Malaika Arora Yoga & Wellness",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Bollywood Fitness",
        "country": ["India"],
        "celebrity_name": "Malaika Arora",
        "difficulty_level": "Intermediate",
        "duration_weeks": 8,
        "sessions_per_week": 5,
        "session_duration_minutes": 60,
        "tags": ["Bollywood", "Yoga", "Women"],
        "goals": ["Flexibility", "Wellness"],
        "description": "Yoga-focused wellness and fitness program inspired by Malaika Arora.",
        "short_description": "Yoga wellness"
    },
    {
        "program_name": "Rohit Sharma Cricket Conditioning",
        "program_category": "Sport Training",
        "program_subcategory": "Cricket",
        "country": ["India"],
        "celebrity_name": "Rohit Sharma",
        "difficulty_level": "Intermediate",
        "duration_weeks": 10,
        "sessions_per_week": 5,
        "session_duration_minutes": 75,
        "tags": ["Cricket", "Conditioning", "Power"],
        "goals": ["Athletic Performance", "Power"],
        "description": "Cricket-specific conditioning with power development for explosive batting.",
        "short_description": "Cricket power training"
    },
    {
        "program_name": "Saina Nehwal Badminton Agility",
        "program_category": "Sport Training",
        "program_subcategory": "Badminton",
        "country": ["India"],
        "celebrity_name": "Saina Nehwal",
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 6,
        "session_duration_minutes": 90,
        "tags": ["Badminton", "Agility", "Women"],
        "goals": ["Athletic Performance", "Agility"],
        "description": "Badminton agility and conditioning program inspired by Saina Nehwal.",
        "short_description": "Badminton agility"
    },
]

MORE_SPECIALIZED_PROGRAMS = [
    {
        "program_name": "CrossFit Beginner Foundation",
        "program_category": "Specialized Training",
        "program_subcategory": "CrossFit",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 8,
        "sessions_per_week": 3,
        "session_duration_minutes": 45,
        "tags": ["CrossFit", "Functional", "Beginner"],
        "goals": ["Athletic Performance", "Conditioning"],
        "description": "Introduction to CrossFit with scaled movements and proper technique foundation.",
        "short_description": "CrossFit fundamentals"
    },
    {
        "program_name": "CrossFit Competition Prep",
        "program_category": "Specialized Training",
        "program_subcategory": "CrossFit",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 6,
        "session_duration_minutes": 90,
        "tags": ["CrossFit", "Competition", "Elite"],
        "goals": ["Athletic Performance", "Competition"],
        "description": "Advanced CrossFit programming for competition preparation and peak performance.",
        "short_description": "CrossFit competition"
    },
    {
        "program_name": "Spartan Race Training",
        "program_category": "Specialized Training",
        "program_subcategory": "Obstacle Course",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 12,
        "sessions_per_week": 5,
        "session_duration_minutes": 60,
        "tags": ["OCR", "Spartan", "Functional"],
        "goals": ["Athletic Performance", "Endurance"],
        "description": "Prepare for Spartan Race with obstacle-specific training and running conditioning.",
        "short_description": "Spartan Race prep"
    },
    {
        "program_name": "Tough Mudder Training",
        "program_category": "Specialized Training",
        "program_subcategory": "Obstacle Course",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 10,
        "sessions_per_week": 4,
        "session_duration_minutes": 60,
        "tags": ["OCR", "Tough Mudder", "Team"],
        "goals": ["Athletic Performance", "Endurance"],
        "description": "Team-focused training for Tough Mudder with emphasis on fun and endurance.",
        "short_description": "Tough Mudder prep"
    },
    {
        "program_name": "Rock Climbing Strength & Technique",
        "program_category": "Specialized Training",
        "program_subcategory": "Climbing",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 12,
        "sessions_per_week": 4,
        "session_duration_minutes": 75,
        "tags": ["Climbing", "Grip Strength", "Power"],
        "goals": ["Athletic Performance", "Grip Strength"],
        "description": "Build climbing-specific strength, endurance, and technique for bouldering and sport climbing.",
        "short_description": "Rock climbing training"
    },
    {
        "program_name": "Surfing Functional Fitness",
        "program_category": "Specialized Training",
        "program_subcategory": "Surfing",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 10,
        "sessions_per_week": 4,
        "session_duration_minutes": 60,
        "tags": ["Surfing", "Paddling", "Balance"],
        "goals": ["Athletic Performance", "Endurance"],
        "description": "Surf-specific conditioning with paddling endurance, pop-up power, and balance.",
        "short_description": "Surfing fitness"
    },
    {
        "program_name": "MMA Fighter Conditioning",
        "program_category": "Specialized Training",
        "program_subcategory": "MMA",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 6,
        "session_duration_minutes": 90,
        "tags": ["MMA", "Fighting", "Conditioning"],
        "goals": ["Athletic Performance", "Combat Sports"],
        "description": "Complete MMA conditioning with striking, grappling, and fight-specific endurance.",
        "short_description": "MMA conditioning"
    },
    {
        "program_name": "Brazilian Jiu-Jitsu Strength",
        "program_category": "Specialized Training",
        "program_subcategory": "BJJ",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 10,
        "sessions_per_week": 4,
        "session_duration_minutes": 60,
        "tags": ["BJJ", "Grappling", "Strength"],
        "goals": ["Athletic Performance", "Grappling Strength"],
        "description": "Supplemental strength training for Brazilian Jiu-Jitsu practitioners.",
        "short_description": "BJJ strength training"
    },
    {
        "program_name": "Muay Thai Conditioning",
        "program_category": "Specialized Training",
        "program_subcategory": "Muay Thai",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 10,
        "sessions_per_week": 5,
        "session_duration_minutes": 75,
        "tags": ["Muay Thai", "Kickboxing", "Conditioning"],
        "goals": ["Athletic Performance", "Combat Conditioning"],
        "description": "Muay Thai-specific conditioning with pad work, clinch work, and cardio.",
        "short_description": "Muay Thai conditioning"
    },
    {
        "program_name": "Parkour & Freerunning Training",
        "program_category": "Specialized Training",
        "program_subcategory": "Parkour",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 12,
        "sessions_per_week": 4,
        "session_duration_minutes": 75,
        "tags": ["Parkour", "Movement", "Agility"],
        "goals": ["Athletic Performance", "Movement Skills"],
        "description": "Build parkour movement skills with vaulting, jumping, and flow training.",
        "short_description": "Parkour training"
    },
]

MORE_BEGINNER_PROGRAMS = [
    {
        "program_name": "Total Beginner Fitness (Never Exercised)",
        "program_category": "Goal-Based",
        "program_subcategory": "Absolute Beginner",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 8,
        "sessions_per_week": 3,
        "session_duration_minutes": 20,
        "tags": ["Beginner", "Foundation", "Basics"],
        "goals": ["Health", "Fitness Foundation"],
        "description": "Perfect starting point for someone who has never exercised before.",
        "short_description": "Absolute beginner start"
    },
    {
        "program_name": "Home Workout No Equipment",
        "program_category": "Goal-Based",
        "program_subcategory": "Home Training",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 8,
        "sessions_per_week": 4,
        "session_duration_minutes": 30,
        "tags": ["Home", "Bodyweight", "No Equipment"],
        "goals": ["Fitness", "Build Muscle"],
        "description": "Effective home workout using zero equipment - just your bodyweight.",
        "short_description": "No equipment home workout"
    },
    {
        "program_name": "Walking to Fitness Program",
        "program_category": "Goal-Based",
        "program_subcategory": "Walking",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 12,
        "sessions_per_week": 5,
        "session_duration_minutes": 30,
        "tags": ["Walking", "Low Impact", "Beginner"],
        "goals": ["Health", "Weight Loss"],
        "description": "Progressive walking program to improve health and lose weight gently.",
        "short_description": "Walking for fitness"
    },
    {
        "program_name": "Senior Fitness Over 65",
        "program_category": "Goal-Based",
        "program_subcategory": "Senior Fitness",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 12,
        "sessions_per_week": 3,
        "session_duration_minutes": 30,
        "tags": ["Seniors", "Balance", "Mobility"],
        "goals": ["Health", "Mobility"],
        "description": "Age-appropriate fitness for seniors focusing on balance, strength, and independence.",
        "short_description": "Senior fitness program"
    },
    {
        "program_name": "Chair Exercises for Limited Mobility",
        "program_category": "Goal-Based",
        "program_subcategory": "Adaptive Fitness",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 8,
        "sessions_per_week": 4,
        "session_duration_minutes": 20,
        "tags": ["Adaptive", "Chair", "Limited Mobility"],
        "goals": ["Health", "Mobility"],
        "description": "Effective exercises that can be done seated for those with limited mobility.",
        "short_description": "Chair exercises"
    },
]

MORE_ADVANCED_PROGRAMS = [
    {
        "program_name": "Ironman Triathlon Training",
        "program_category": "Goal-Based",
        "program_subcategory": "Triathlon",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Elite",
        "duration_weeks": 24,
        "sessions_per_week": 6,
        "session_duration_minutes": 120,
        "tags": ["Triathlon", "Ironman", "Endurance"],
        "goals": ["Endurance", "Athletic Performance"],
        "description": "Complete Ironman triathlon training covering swim, bike, and run progressions.",
        "short_description": "Ironman triathlon prep"
    },
    {
        "program_name": "Ultra Marathon 50K Training",
        "program_category": "Goal-Based",
        "program_subcategory": "Ultra Running",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Elite",
        "duration_weeks": 20,
        "sessions_per_week": 5,
        "session_duration_minutes": 150,
        "tags": ["Ultra", "Running", "Endurance"],
        "goals": ["Endurance", "Ultra Endurance"],
        "description": "Train for 50K ultramarathon with back-to-back long runs and trail training.",
        "short_description": "Ultra 50K training"
    },
    {
        "program_name": "Bodybuilding Competition Prep",
        "program_category": "Goal-Based",
        "program_subcategory": "Bodybuilding",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Elite",
        "duration_weeks": 16,
        "sessions_per_week": 6,
        "session_duration_minutes": 90,
        "tags": ["Bodybuilding", "Competition", "Aesthetic"],
        "goals": ["Build Muscle", "Competition"],
        "description": "Contest prep bodybuilding program with periodization for peak physique.",
        "short_description": "Bodybuilding contest prep"
    },
    {
        "program_name": "Powerlifting Meet Preparation",
        "program_category": "Goal-Based",
        "program_subcategory": "Powerlifting",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 4,
        "session_duration_minutes": 90,
        "tags": ["Powerlifting", "Strength", "Competition"],
        "goals": ["Increase Strength", "Competition"],
        "description": "Peaking program for powerlifting competition with max strength focus.",
        "short_description": "Powerlifting meet prep"
    },
]

# Consolidate ALL programs
ALL_PROGRAMS = []

# First 90 from program_definitions.py (already manually defined)
from program_definitions import PROGRAMS as EXISTING_90

ALL_PROGRAMS.extend(EXISTING_90)

# Add all new categories
ALL_PROGRAMS.extend(YOGA_PROGRAMS)
ALL_PROGRAMS.extend(STRETCHING_PROGRAMS)
ALL_PROGRAMS.extend(PAIN_MANAGEMENT_PROGRAMS)
ALL_PROGRAMS.extend(SPORT_SPECIFIC_PROGRAMS)
ALL_PROGRAMS.extend(ADDITIONAL_GOAL_PROGRAMS)
ALL_PROGRAMS.extend(ADDITIONAL_WOMEN_PROGRAMS)
ALL_PROGRAMS.extend(ADDITIONAL_MEN_PROGRAMS)
ALL_PROGRAMS.extend(MORE_CELEBRITY_PROGRAMS)
ALL_PROGRAMS.extend(MORE_INDIAN_PROGRAMS)
ALL_PROGRAMS.extend(MORE_SPECIALIZED_PROGRAMS)
ALL_PROGRAMS.extend(MORE_BEGINNER_PROGRAMS)
ALL_PROGRAMS.extend(MORE_ADVANCED_PROGRAMS)

print(f"\n🎯 FINAL PROGRAM COUNT: {len(ALL_PROGRAMS)} programs")
print("\n📊 Breakdown by Category:")
print(f"   Existing Programs: {len(EXISTING_90)}")
print(f"   Yoga: {len(YOGA_PROGRAMS)}")
print(f"   Stretching: {len(STRETCHING_PROGRAMS)}")
print(f"   Pain Management: {len(PAIN_MANAGEMENT_PROGRAMS)}")
print(f"   Sport-Specific: {len(SPORT_SPECIFIC_PROGRAMS)}")
print(f"   Goal-Based: {len(ADDITIONAL_GOAL_PROGRAMS)}")
print(f"   Additional Women's: {len(ADDITIONAL_WOMEN_PROGRAMS)}")
print(f"   Additional Men's: {len(ADDITIONAL_MEN_PROGRAMS)}")
print(f"   More Celebrity: {len(MORE_CELEBRITY_PROGRAMS)}")
print(f"   More Indian Celebrity: {len(MORE_INDIAN_PROGRAMS)}")
print(f"   Specialized Training: {len(MORE_SPECIALIZED_PROGRAMS)}")
print(f"   Beginner Programs: {len(MORE_BEGINNER_PROGRAMS)}")
print(f"   Advanced/Elite: {len(MORE_ADVANCED_PROGRAMS)}")

# Save to JSON for review
with open('/Users/saichetangrandhe/AIFitnessCoach/backend/scripts/all_programs_catalog.json', 'w') as f:
    json.dump(ALL_PROGRAMS, f, indent=2)

print(f"\n✅ Saved complete catalog to all_programs_catalog.json")
print(f"📝 Total: {len(ALL_PROGRAMS)} programs ready for generation!")

# Adding 90+ more programs to reach 250+

EVEN_MORE_PROGRAMS = [
    # More Yoga Variations (10)
    {
        "program_name": "Ashtanga Yoga Primary Series",
        "program_category": "Yoga",
        "program_subcategory": "Ashtanga",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 5,
        "session_duration_minutes": 90,
        "tags": ["Yoga", "Ashtanga", "Traditional"],
        "goals": ["Flexibility", "Strength"],
        "description": "Traditional Ashtanga Yoga primary series with disciplined practice sequence.",
        "short_description": "Ashtanga primary series"
    },
    {
        "program_name": "Kundalini Yoga Energy Work",
        "program_category": "Yoga",
        "program_subcategory": "Kundalini",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 8,
        "sessions_per_week": 4,
        "session_duration_minutes": 60,
        "tags": ["Yoga", "Kundalini", "Energy"],
        "goals": ["Energy", "Spiritual"],
        "description": "Kundalini yoga focusing on energy work, breath, and consciousness.",
        "short_description": "Kundalini energy yoga"
    },
    {
        "program_name": "Hatha Yoga Classical",
        "program_category": "Yoga",
        "program_subcategory": "Hatha",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 8,
        "sessions_per_week": 3,
        "session_duration_minutes": 60,
        "tags": ["Yoga", "Hatha", "Classical"],
        "goals": ["Flexibility", "Balance"],
        "description": "Classical Hatha Yoga with traditional poses and breathing exercises.",
        "short_description": "Classical Hatha yoga"
    },
    {
        "program_name": "Aerial Yoga Beginner",
        "program_category": "Yoga",
        "program_subcategory": "Aerial",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 8,
        "sessions_per_week": 3,
        "session_duration_minutes": 60,
        "tags": ["Yoga", "Aerial", "Fun"],
        "goals": ["Flexibility", "Core Strength"],
        "description": "Yoga using aerial silk hammocks for decompression and fun inversions.",
        "short_description": "Aerial yoga fun"
    },
    {
        "program_name": "Acro Yoga Partner Practice",
        "program_category": "Yoga",
        "program_subcategory": "Acro",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 10,
        "sessions_per_week": 3,
        "session_duration_minutes": 75,
        "tags": ["Yoga", "Acro", "Partner"],
        "goals": ["Strength", "Balance"],
        "description": "Partner acrobatic yoga combining strength, trust, and playfulness.",
        "short_description": "Acro yoga partners"
    },
    {
        "program_name": "Chair Yoga for Office",
        "program_category": "Yoga",
        "program_subcategory": "Chair Yoga",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 4,
        "sessions_per_week": 5,
        "session_duration_minutes": 15,
        "tags": ["Yoga", "Chair", "Office"],
        "goals": ["Flexibility", "Stress Relief"],
        "description": "Quick chair yoga sessions perfect for office workers and desk stretching.",
        "short_description": "Office chair yoga"
    },
    {
        "program_name": "Yoga Nidra Deep Relaxation",
        "program_category": "Yoga",
        "program_subcategory": "Yoga Nidra",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 6,
        "sessions_per_week": 4,
        "session_duration_minutes": 30,
        "tags": ["Yoga", "Meditation", "Sleep"],
        "goals": ["Stress Relief", "Sleep Quality"],
        "description": "Yogic sleep practice for deep relaxation and stress reduction.",
        "short_description": "Yoga Nidra relaxation"
    },
    {
        "program_name": "Rocket Yoga Dynamic Flow",
        "program_category": "Yoga",
        "program_subcategory": "Rocket Yoga",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 10,
        "sessions_per_week": 4,
        "session_duration_minutes": 75,
        "tags": ["Yoga", "Rocket", "Dynamic"],
        "goals": ["Strength", "Flexibility"],
        "description": "Modified Ashtanga with arm balances, inversions, and creative sequences.",
        "short_description": "Rocket yoga flow"
    },
    {
        "program_name": "Jivamukti Yoga Spiritual Practice",
        "program_category": "Yoga",
        "program_subcategory": "Jivamukti",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 8,
        "sessions_per_week": 4,
        "session_duration_minutes": 90,
        "tags": ["Yoga", "Jivamukti", "Spiritual"],
        "goals": ["Flexibility", "Spiritual Growth"],
        "description": "Vinyasa-based practice incorporating chanting, meditation, and philosophy.",
        "short_description": "Jivamukti spiritual yoga"
    },
    {
        "program_name": "Forrest Yoga Healing Practice",
        "program_category": "Yoga",
        "program_subcategory": "Forrest Yoga",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 10,
        "sessions_per_week": 4,
        "session_duration_minutes": 75,
        "tags": ["Yoga", "Forrest", "Healing"],
        "goals": ["Core Strength", "Emotional Healing"],
        "description": "Intense core work and long holdings for emotional and physical healing.",
        "short_description": "Forrest healing yoga"
    },

    # More Women's Programs (15)
    {
        "program_name": "Women's Triathlon Training",
        "program_category": "Women's Health",
        "program_subcategory": "Triathlon",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 16,
        "sessions_per_week": 6,
        "session_duration_minutes": 90,
        "tags": ["Women", "Triathlon", "Endurance"],
        "goals": ["Endurance", "Athletic Performance"],
        "description": "Complete women's triathlon training for swim, bike, and run.",
        "short_description": "Women's triathlon"
    },
    {
        "program_name": "Women's Powerlifting Beginner",
        "program_category": "Women's Health",
        "program_subcategory": "Powerlifting",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 12,
        "sessions_per_week": 3,
        "session_duration_minutes": 60,
        "tags": ["Women", "Powerlifting", "Strength"],
        "goals": ["Increase Strength", "Confidence"],
        "description": "Introduction to powerlifting for women: squat, bench press, deadlift.",
        "short_description": "Women's powerlifting intro"
    },
    {
        "program_name": "Figure Competition Prep Women",
        "program_category": "Women's Health",
        "program_subcategory": "Figure Competition",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 20,
        "sessions_per_week": 6,
        "session_duration_minutes": 75,
        "tags": ["Women", "Figure", "Competition"],
        "goals": ["Build Muscle", "Competition"],
        "description": "Figure competition prep with muscle building and conditioning phases.",
        "short_description": "Figure comp prep"
    },
    {
        "program_name": "Bikini Body Competition Prep",
        "program_category": "Women's Health",
        "program_subcategory": "Bikini Competition",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 16,
        "sessions_per_week": 6,
        "session_duration_minutes": 60,
        "tags": ["Women", "Bikini", "Competition"],
        "goals": ["Toning", "Competition"],
        "description": "Bikini competition prep focusing on shape, symmetry, and conditioning.",
        "short_description": "Bikini comp prep"
    },
    {
        "program_name": "Women's Obstacle Course Racing",
        "program_category": "Women's Health",
        "program_subcategory": "OCR",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 12,
        "sessions_per_week": 5,
        "session_duration_minutes": 60,
        "tags": ["Women", "OCR", "Functional"],
        "goals": ["Athletic Performance", "Strength"],
        "description": "Train for obstacle course races with grip strength, running, and obstacles.",
        "short_description": "Women's OCR training"
    },

    # More Men's Programs (10)
    {
        "program_name": "Men's Spartan Physique",
        "program_category": "Men's Health",
        "program_subcategory": "Aesthetic Goals",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 6,
        "session_duration_minutes": 75,
        "tags": ["Men", "Spartan", "Warrior"],
        "goals": ["Build Muscle", "Athletic Performance"],
        "description": "Build a lean, muscular warrior physique like ancient Spartans.",
        "short_description": "Spartan warrior build"
    },
    {
        "program_name": "Men's Navy SEAL Fitness",
        "program_category": "Men's Health",
        "program_subcategory": "Military Fitness",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Elite",
        "duration_weeks": 16,
        "sessions_per_week": 6,
        "session_duration_minutes": 120,
        "tags": ["Men", "Military", "Elite"],
        "goals": ["Endurance", "Mental Toughness"],
        "description": "Elite military-style training inspired by Navy SEAL preparation programs.",
        "short_description": "Navy SEAL training"
    },
    {
        "program_name": "Men's Tactical Athlete Program",
        "program_category": "Men's Health",
        "program_subcategory": "Tactical",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 5,
        "session_duration_minutes": 90,
        "tags": ["Men", "Tactical", "Functional"],
        "goals": ["Strength", "Endurance"],
        "description": "Train like a tactical athlete: military, law enforcement, first responder fitness.",
        "short_description": "Tactical athlete training"
    },
    {
        "program_name": "Men's Absolute Strength 5x5",
        "program_category": "Men's Health",
        "program_subcategory": "Strength Training",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 12,
        "sessions_per_week": 3,
        "session_duration_minutes": 60,
        "tags": ["Men", "Strength", "5x5"],
        "goals": ["Increase Strength", "Build Muscle"],
        "description": "Classic 5x5 strength program for building maximum strength and size.",
        "short_description": "5x5 strength program"
    },
    {
        "program_name": "Men's Starting Strength Program",
        "program_category": "Men's Health",
        "program_subcategory": "Strength Training",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 12,
        "sessions_per_week": 3,
        "session_duration_minutes": 60,
        "tags": ["Men", "Beginner", "Strength"],
        "goals": ["Increase Strength", "Learn Fundamentals"],
        "description": "Linear progression strength program perfect for novice lifters.",
        "short_description": "Starting strength basics"
    },

    # More Sport-Specific (15)
    {
        "program_name": "Golf Fitness & Flexibility",
        "program_category": "Sport Training",
        "program_subcategory": "Golf",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 10,
        "sessions_per_week": 3,
        "session_duration_minutes": 45,
        "tags": ["Golf", "Flexibility", "Rotation"],
        "goals": ["Flexibility", "Athletic Performance"],
        "description": "Improve golf performance through rotational power and flexibility training.",
        "short_description": "Golf fitness training"
    },
    {
        "program_name": "Baseball/Softball Throwing Program",
        "program_category": "Sport Training",
        "program_subcategory": "Baseball",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 12,
        "sessions_per_week": 4,
        "session_duration_minutes": 60,
        "tags": ["Baseball", "Throwing", "Power"],
        "goals": ["Athletic Performance", "Injury Prevention"],
        "description": "Baseball/softball conditioning with throwing velocity and injury prevention focus.",
        "short_description": "Baseball conditioning"
    },
    {
        "program_name": "American Football Strength & Speed",
        "program_category": "Sport Training",
        "program_subcategory": "Football",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 5,
        "session_duration_minutes": 90,
        "tags": ["Football", "Strength", "Speed"],
        "goals": ["Increase Strength", "Explosiveness"],
        "description": "Football strength and speed training for power, size, and explosiveness.",
        "short_description": "Football training"
    },
    {
        "program_name": "Rugby Conditioning Program",
        "program_category": "Sport Training",
        "program_subcategory": "Rugby",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 5,
        "session_duration_minutes": 75,
        "tags": ["Rugby", "Conditioning", "Contact"],
        "goals": ["Strength", "Endurance"],
        "description": "Rugby-specific training for strength, endurance, and contact readiness.",
        "short_description": "Rugby conditioning"
    },
    {
        "program_name": "Ice Hockey Power & Speed",
        "program_category": "Sport Training",
        "program_subcategory": "Hockey",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 5,
        "session_duration_minutes": 75,
        "tags": ["Hockey", "Power", "Speed"],
        "goals": ["Explosiveness", "Conditioning"],
        "description": "Off-ice hockey training for explosive power, speed, and conditioning.",
        "short_description": "Hockey power training"
    },
    {
        "program_name": "Lacrosse Agility & Endurance",
        "program_category": "Sport Training",
        "program_subcategory": "Lacrosse",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 10,
        "sessions_per_week": 4,
        "session_duration_minutes": 60,
        "tags": ["Lacrosse", "Agility", "Endurance"],
        "goals": ["Agility", "Endurance"],
        "description": "Lacrosse conditioning with agility drills and endurance work.",
        "short_description": "Lacrosse training"
    },
    {
        "program_name": "Wrestling Strength & Conditioning",
        "program_category": "Sport Training",
        "program_subcategory": "Wrestling",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 6,
        "session_duration_minutes": 90,
        "tags": ["Wrestling", "Strength", "Conditioning"],
        "goals": ["Strength", "Endurance"],
        "description": "Wrestling-specific strength and conditioning for mat dominance.",
        "short_description": "Wrestling conditioning"
    },
    {
        "program_name": "Field Hockey Conditioning",
        "program_category": "Sport Training",
        "program_subcategory": "Field Hockey",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 10,
        "sessions_per_week": 4,
        "session_duration_minutes": 60,
        "tags": ["Hockey", "Endurance", "Speed"],
        "goals": ["Endurance", "Speed"],
        "description": "Field hockey conditioning with running endurance and sprint work.",
        "short_description": "Field hockey fitness"
    },
    {
        "program_name": "Rowing Endurance & Power",
        "program_category": "Sport Training",
        "program_subcategory": "Rowing",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 6,
        "session_duration_minutes": 75,
        "tags": ["Rowing", "Endurance", "Power"],
        "goals": ["Endurance", "Power"],
        "description": "Rowing-specific training for endurance and powerful strokes.",
        "short_description": "Rowing training"
    },
    {
        "program_name": "Track & Field Sprinter Program",
        "program_category": "Sport Training",
        "program_subcategory": "Track",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 5,
        "session_duration_minutes": 75,
        "tags": ["Track", "Sprinting", "Speed"],
        "goals": ["Speed", "Power"],
        "description": "Elite sprinter training for 100m, 200m, 400m track events.",
        "short_description": "Sprinter training"
    },

    # More Pain Management (10)
    {
        "program_name": "TMJ & Jaw Pain Relief",
        "program_category": "Pain Management",
        "program_subcategory": "TMJ",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 6,
        "sessions_per_week": 7,
        "session_duration_minutes": 10,
        "tags": ["Pain Relief", "TMJ", "Jaw"],
        "goals": ["Pain Relief", "Mobility"],
        "description": "Gentle exercises and stretches to relieve TMJ and jaw pain.",
        "short_description": "TMJ pain relief"
    },
    {
        "program_name": "Wrist & Hand Pain Relief",
        "program_category": "Pain Management",
        "program_subcategory": "Hand Pain",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 6,
        "sessions_per_week": 7,
        "session_duration_minutes": 10,
        "tags": ["Pain Relief", "Wrist", "Carpal Tunnel"],
        "goals": ["Pain Relief", "Mobility"],
        "description": "Exercises for wrist, hand, and carpal tunnel pain relief.",
        "short_description": "Wrist pain relief"
    },
    {
        "program_name": "Elbow Tendonitis Rehab",
        "program_category": "Pain Management",
        "program_subcategory": "Elbow Pain",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 8,
        "sessions_per_week": 5,
        "session_duration_minutes": 15,
        "tags": ["Pain Relief", "Elbow", "Tendonitis"],
        "goals": ["Pain Relief", "Recovery"],
        "description": "Rehabilitation for tennis elbow, golfer's elbow, and elbow tendonitis.",
        "short_description": "Elbow tendonitis rehab"
    },
    {
        "program_name": "Ankle Sprain Recovery",
        "program_category": "Pain Management",
        "program_subcategory": "Ankle Injury",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 8,
        "sessions_per_week": 5,
        "session_duration_minutes": 20,
        "tags": ["Pain Relief", "Ankle", "Recovery"],
        "goals": ["Recovery", "Stability"],
        "description": "Progressive ankle sprain rehabilitation for strength and stability.",
        "short_description": "Ankle sprain recovery"
    },
    {
        "program_name": "IT Band Syndrome Relief",
        "program_category": "Pain Management",
        "program_subcategory": "IT Band",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 8,
        "sessions_per_week": 5,
        "session_duration_minutes": 20,
        "tags": ["Pain Relief", "IT Band", "Running"],
        "goals": ["Pain Relief", "Mobility"],
        "description": "Exercises and stretches to relieve IT band syndrome pain.",
        "short_description": "IT band relief"
    },

    # More Goal-Based (10)
    {
        "program_name": "Metabolic Resistance Training",
        "program_category": "Goal-Based",
        "program_subcategory": "Fat Loss",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 8,
        "sessions_per_week": 4,
        "session_duration_minutes": 40,
        "tags": ["Fat Loss", "Metabolic", "Circuit"],
        "goals": ["Lose Fat", "Conditioning"],
        "description": "Circuit training with weights for maximum calorie burn and fat loss.",
        "short_description": "Metabolic resistance"
    },
    {
        "program_name": "Tabata HIIT 4-Minute Workouts",
        "program_category": "Goal-Based",
        "program_subcategory": "HIIT",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 6,
        "sessions_per_week": 5,
        "session_duration_minutes": 20,
        "tags": ["HIIT", "Tabata", "Quick"],
        "goals": ["Lose Fat", "Conditioning"],
        "description": "Ultra-high intensity Tabata protocol: 20 seconds on, 10 seconds off.",
        "short_description": "Tabata HIIT workouts"
    },
    {
        "program_name": "German Volume Training 10x10",
        "program_category": "Goal-Based",
        "program_subcategory": "Muscle Building",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 6,
        "sessions_per_week": 3,
        "session_duration_minutes": 75,
        "tags": ["Hypertrophy", "GVT", "Volume"],
        "goals": ["Build Muscle", "Size"],
        "description": "Extreme volume training with 10 sets of 10 reps for rapid muscle growth.",
        "short_description": "GVT 10x10 program"
    },
    {
        "program_name": "Drop Set Hypertrophy Program",
        "program_category": "Goal-Based",
        "program_subcategory": "Muscle Building",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 8,
        "sessions_per_week": 4,
        "session_duration_minutes": 60,
        "tags": ["Hypertrophy", "Drop Sets", "Intensity"],
        "goals": ["Build Muscle", "Size"],
        "description": "Muscle building program using drop sets for increased volume and intensity.",
        "short_description": "Drop set hypertrophy"
    },
    {
        "program_name": "Superset Muscle Building",
        "program_category": "Goal-Based",
        "program_subcategory": "Muscle Building",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 10,
        "sessions_per_week": 4,
        "session_duration_minutes": 60,
        "tags": ["Hypertrophy", "Supersets", "Efficiency"],
        "goals": ["Build Muscle", "Time Efficient"],
        "description": "Efficient muscle building using antagonist supersets for maximum growth.",
        "short_description": "Superset training"
    },

    # Specialized/Unique Programs (15)
    {
        "program_name": "Medieval Warrior Training",
        "program_category": "Specialized Training",
        "program_subcategory": "Functional",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 5,
        "session_duration_minutes": 75,
        "tags": ["Medieval", "Functional", "Warrior"],
        "goals": ["Strength", "Endurance"],
        "description": "Train like a medieval warrior with functional strength and combat conditioning.",
        "short_description": "Medieval warrior prep"
    },
    {
        "program_name": "Animal Movement Practice",
        "program_category": "Specialized Training",
        "program_subcategory": "Movement",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 10,
        "sessions_per_week": 4,
        "session_duration_minutes": 45,
        "tags": ["Movement", "Animal Flow", "Ground Work"],
        "goals": ["Mobility", "Movement Skills"],
        "description": "Primal movement patterns inspired by animal locomotion for mobility and strength.",
        "short_description": "Animal movement flow"
    },
    {
        "program_name": "Handstand Progression Program",
        "program_category": "Specialized Training",
        "program_subcategory": "Gymnastics",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 12,
        "sessions_per_week": 4,
        "session_duration_minutes": 40,
        "tags": ["Gymnastics", "Handstand", "Balance"],
        "goals": ["Skill Mastery", "Strength"],
        "description": "Progressive handstand training from wall support to freestanding holds.",
        "short_description": "Learn handstands"
    },
    {
        "program_name": "Muscle-Up Skill Development",
        "program_category": "Specialized Training",
        "program_subcategory": "Calisthenics",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 10,
        "sessions_per_week": 4,
        "session_duration_minutes": 50,
        "tags": ["Calisthenics", "Muscle-Up", "Skill"],
        "goals": ["Skill Mastery", "Strength"],
        "description": "Master the muscle-up with progression from pull-ups to bar muscle-ups.",
        "short_description": "Master muscle-ups"
    },
    {
        "program_name": "Planche Training Program",
        "program_category": "Specialized Training",
        "program_subcategory": "Calisthenics",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Elite",
        "duration_weeks": 24,
        "sessions_per_week": 5,
        "session_duration_minutes": 60,
        "tags": ["Calisthenics", "Planche", "Elite Skill"],
        "goals": ["Skill Mastery", "Strength"],
        "description": "Long-term planche training from tuck to full planche progression.",
        "short_description": "Achieve the planche"
    },
    {
        "program_name": "One-Arm Push-Up & Pull-Up",
        "program_category": "Specialized Training",
        "program_subcategory": "Calisthenics",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 16,
        "sessions_per_week": 4,
        "session_duration_minutes": 50,
        "tags": ["Calisthenics", "Unilateral", "Advanced"],
        "goals": ["Skill Mastery", "Strength"],
        "description": "Build to one-arm push-ups and one-arm pull-ups through progression.",
        "short_description": "One-arm mastery"
    },
    {
        "program_name": "Kettlebell Sport Training",
        "program_category": "Specialized Training",
        "program_subcategory": "Kettlebell Sport",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 4,
        "session_duration_minutes": 60,
        "tags": ["Kettlebell", "Sport", "Endurance"],
        "goals": ["Endurance", "Strength"],
        "description": "Competitive kettlebell sport training: jerk, snatch, and long cycle.",
        "short_description": "Kettlebell sport"
    },
    {
        "program_name": "Steel Mace Training",
        "program_category": "Specialized Training",
        "program_subcategory": "Unconventional",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 10,
        "sessions_per_week": 3,
        "session_duration_minutes": 45,
        "tags": ["Steel Mace", "Rotation", "Functional"],
        "goals": ["Strength", "Mobility"],
        "description": "Rotational strength and power development using steel mace training.",
        "short_description": "Steel mace training"
    },
    {
        "program_name": "Indian Clubs Shoulder Health",
        "program_category": "Specialized Training",
        "program_subcategory": "Unconventional",
        "country": ["India", "Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 8,
        "sessions_per_week": 4,
        "session_duration_minutes": 20,
        "tags": ["Indian Clubs", "Shoulder", "Mobility"],
        "goals": ["Shoulder Health", "Mobility"],
        "description": "Traditional Indian club training for shoulder health and mobility.",
        "short_description": "Indian clubs training"
    },
    {
        "program_name": "Sandbag Training Program",
        "program_category": "Specialized Training",
        "program_subcategory": "Unconventional",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 10,
        "sessions_per_week": 4,
        "session_duration_minutes": 50,
        "tags": ["Sandbag", "Functional", "Strength"],
        "goals": ["Functional Strength", "Conditioning"],
        "description": "Build functional strength with unstable sandbag training.",
        "short_description": "Sandbag strength"
    },
    {
        "program_name": "Battle Ropes HIIT Training",
        "program_category": "Specialized Training",
        "program_subcategory": "HIIT Equipment",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 8,
        "sessions_per_week": 4,
        "session_duration_minutes": 30,
        "tags": ["Battle Ropes", "HIIT", "Conditioning"],
        "goals": ["Conditioning", "Upper Body"],
        "description": "High-intensity battle rope training for conditioning and upper body power.",
        "short_description": "Battle rope HIIT"
    },
    {
        "program_name": "TRX Suspension Training",
        "program_category": "Specialized Training",
        "program_subcategory": "Suspension Training",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 10,
        "sessions_per_week": 4,
        "session_duration_minutes": 45,
        "tags": ["TRX", "Suspension", "Core"],
        "goals": ["Core Strength", "Functional Fitness"],
        "description": "Full-body suspension training using TRX or similar systems.",
        "short_description": "TRX suspension training"
    },
    {
        "program_name": "Sled Push & Pull Power",
        "program_category": "Specialized Training",
        "program_subcategory": "Sled Training",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 8,
        "sessions_per_week": 3,
        "session_duration_minutes": 40,
        "tags": ["Sled", "Power", "Legs"],
        "goals": ["Power", "Leg Strength"],
        "description": "Build explosive leg power and conditioning with sled pushes and pulls.",
        "short_description": "Sled power training"
    },
    {
        "program_name": "Strongman Implements Training",
        "program_category": "Specialized Training",
        "program_subcategory": "Strongman",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 4,
        "session_duration_minutes": 90,
        "tags": ["Strongman", "Implements", "Functional"],
        "goals": ["Strength", "Functional Power"],
        "description": "Train with atlas stones, farmer's walks, yoke carries, and tire flips.",
        "short_description": "Strongman implements"
    },
]

ALL_PROGRAMS.extend(EVEN_MORE_PROGRAMS)

print(f"\n🎊 UPDATED FINAL COUNT: {len(ALL_PROGRAMS)} programs!")
print(f"   Added: {len(EVEN_MORE_PROGRAMS)} more programs")

# Re-save with updated count
with open('/Users/saichetangrandhe/AIFitnessCoach/backend/scripts/all_programs_catalog.json', 'w') as f:
    json.dump(ALL_PROGRAMS, f, indent=2)

print(f"\n✅ Updated all_programs_catalog.json")
print(f"🏆 TOTAL PROGRAMS: {len(ALL_PROGRAMS)}")


# Final 35 programs to reach 250+ total

FINAL_PROGRAMS_TO_250 = [
    # More Niche/Unique Programs (35)
    {
        "program_name": "Ninja Warrior Training",
        "program_category": "Specialized Training",
        "program_subcategory": "Obstacle Course",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 16,
        "sessions_per_week": 5,
        "session_duration_minutes": 75,
        "tags": ["Ninja Warrior", "Obstacles", "Grip"],
        "goals": ["Athletic Performance", "Skill Mastery"],
        "description": "Train for American Ninja Warrior with obstacle-specific skills and grip strength.",
        "short_description": "Ninja Warrior prep"
    },
    {
        "program_name": "Stunt Performer Training",
        "program_category": "Specialized Training",
        "program_subcategory": "Stunt Work",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Elite",
        "duration_weeks": 20,
        "sessions_per_week": 6,
        "session_duration_minutes": 120,
        "tags": ["Stunt", "Acrobatics", "Falls"],
        "goals": ["Athletic Performance", "Skill Mastery"],
        "description": "Professional stunt training with falls, fights, and acrobatic skills.",
        "short_description": "Stunt performer training"
    },
    {
        "program_name": "Firefighter Functional Fitness",
        "program_category": "Specialized Training",
        "program_subcategory": "Occupational",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 5,
        "session_duration_minutes": 75,
        "tags": ["Firefighter", "Functional", "Job Specific"],
        "goals": ["Strength", "Endurance"],
        "description": "Firefighter-specific training for carrying equipment, climbing, and endurance.",
        "short_description": "Firefighter fitness"
    },
    {
        "program_name": "Police Academy Prep",
        "program_category": "Specialized Training",
        "program_subcategory": "Occupational",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 12,
        "sessions_per_week": 5,
        "session_duration_minutes": 60,
        "tags": ["Law Enforcement", "Test Prep", "Running"],
        "goals": ["Endurance", "Pass Test"],
        "description": "Prepare for police academy physical fitness tests and standards.",
        "short_description": "Police academy prep"
    },
    {
        "program_name": "Military Boot Camp Preparation",
        "program_category": "Specialized Training",
        "program_subcategory": "Military",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 16,
        "sessions_per_week": 6,
        "session_duration_minutes": 75,
        "tags": ["Military", "Boot Camp", "Endurance"],
        "goals": ["Endurance", "Mental Toughness"],
        "description": "Prepare for basic military training with running, calisthenics, and rucking.",
        "short_description": "Boot camp prep"
    },
    {
        "program_name": "Astronaut Fitness Training",
        "program_category": "Specialized Training",
        "program_subcategory": "Occupational",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Elite",
        "duration_weeks": 52,
        "sessions_per_week": 6,
        "session_duration_minutes": 90,
        "tags": ["Astronaut", "Elite", "Endurance"],
        "goals": ["Endurance", "Strength"],
        "description": "Year-long conditioning program inspired by astronaut training requirements.",
        "short_description": "Astronaut conditioning"
    },
    {
        "program_name": "Skiers Leg Strength & Endurance",
        "program_category": "Sport Training",
        "program_subcategory": "Skiing",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 12,
        "sessions_per_week": 4,
        "session_duration_minutes": 60,
        "tags": ["Skiing", "Legs", "Endurance"],
        "goals": ["Leg Strength", "Endurance"],
        "description": "Pre-season ski conditioning for powerful legs and injury prevention.",
        "short_description": "Ski conditioning"
    },
    {
        "program_name": "Snowboarders Balance & Power",
        "program_category": "Sport Training",
        "program_subcategory": "Snowboarding",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 10,
        "sessions_per_week": 4,
        "session_duration_minutes": 60,
        "tags": ["Snowboarding", "Balance", "Power"],
        "goals": ["Balance", "Power"],
        "description": "Snowboard-specific training for balance, rotational power, and core strength.",
        "short_description": "Snowboard training"
    },
    {
        "program_name": "Skateboarding Balance & Tricks",
        "program_category": "Sport Training",
        "program_subcategory": "Skateboarding",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 12,
        "sessions_per_week": 4,
        "session_duration_minutes": 45,
        "tags": ["Skateboarding", "Balance", "Tricks"],
        "goals": ["Balance", "Athletic Performance"],
        "description": "Improve skateboarding with balance training, leg strength, and fall prevention.",
        "short_description": "Skateboard training"
    },
    {
        "program_name": "BMX Rider Conditioning",
        "program_category": "Sport Training",
        "program_subcategory": "BMX",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 10,
        "sessions_per_week": 4,
        "session_duration_minutes": 60,
        "tags": ["BMX", "Explosiveness", "Core"],
        "goals": ["Explosiveness", "Core Strength"],
        "description": "BMX-specific conditioning for explosive power and crash resilience.",
        "short_description": "BMX conditioning"
    },
    {
        "program_name": "Equestrian Rider Fitness",
        "program_category": "Sport Training",
        "program_subcategory": "Equestrian",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 8,
        "sessions_per_week": 3,
        "session_duration_minutes": 45,
        "tags": ["Equestrian", "Core", "Balance"],
        "goals": ["Core Strength", "Balance"],
        "description": "Horse riding fitness for core stability, leg strength, and endurance.",
        "short_description": "Equestrian fitness"
    },
    {
        "program_name": "Dancers Flexibility & Strength",
        "program_category": "Specialized Training",
        "program_subcategory": "Dance",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 12,
        "sessions_per_week": 5,
        "session_duration_minutes": 60,
        "tags": ["Dance", "Flexibility", "Strength"],
        "goals": ["Flexibility", "Dance Performance"],
        "description": "Supplemental training for dancers: flexibility, turnout, and injury prevention.",
        "short_description": "Dancer conditioning"
    },
    {
        "program_name": "Ballet Strength & Technique",
        "program_category": "Specialized Training",
        "program_subcategory": "Ballet",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 16,
        "sessions_per_week": 5,
        "session_duration_minutes": 75,
        "tags": ["Ballet", "Strength", "Flexibility"],
        "goals": ["Flexibility", "Dance Performance"],
        "description": "Ballet-specific strength, flexibility, and technique enhancement program.",
        "short_description": "Ballet training"
    },
    {
        "program_name": "Cheerleading Tumbling Power",
        "program_category": "Sport Training",
        "program_subcategory": "Cheerleading",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 10,
        "sessions_per_week": 4,
        "session_duration_minutes": 60,
        "tags": ["Cheerleading", "Tumbling", "Power"],
        "goals": ["Explosiveness", "Athletic Performance"],
        "description": "Cheerleading conditioning with tumbling power, stunting strength, and jump training.",
        "short_description": "Cheerleading training"
    },
    {
        "program_name": "Gymnasts Strength & Flexibility",
        "program_category": "Sport Training",
        "program_subcategory": "Gymnastics",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 16,
        "sessions_per_week": 6,
        "session_duration_minutes": 90,
        "tags": ["Gymnastics", "Strength", "Flexibility"],
        "goals": ["Strength", "Flexibility"],
        "description": "Supplemental gymnastics training for strength, flexibility, and skill work.",
        "short_description": "Gymnastics conditioning"
    },
    {
        "program_name": "Figure Skater Off-Ice Training",
        "program_category": "Sport Training",
        "program_subcategory": "Figure Skating",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 5,
        "session_duration_minutes": 75,
        "tags": ["Figure Skating", "Balance", "Power"],
        "goals": ["Balance", "Jump Power"],
        "description": "Off-ice training for figure skaters: jumping power, balance, and flexibility.",
        "short_description": "Figure skating training"
    },
    {
        "program_name": "Elderly Fall Prevention",
        "program_category": "Goal-Based",
        "program_subcategory": "Senior Health",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 12,
        "sessions_per_week": 3,
        "session_duration_minutes": 30,
        "tags": ["Seniors", "Fall Prevention", "Balance"],
        "goals": ["Balance", "Safety"],
        "description": "Fall prevention program for elderly with balance, strength, and coordination work.",
        "short_description": "Fall prevention"
    },
    {
        "program_name": "Bone Density Building for Osteoporosis",
        "program_category": "Goal-Based",
        "program_subcategory": "Bone Health",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 24,
        "sessions_per_week": 3,
        "session_duration_minutes": 40,
        "tags": ["Bone Health", "Osteoporosis", "Strength"],
        "goals": ["Bone Density", "Strength"],
        "description": "Safe resistance training to build bone density and prevent osteoporosis.",
        "short_description": "Bone density building"
    },
    {
        "program_name": "Heart Health Cardio Program",
        "program_category": "Goal-Based",
        "program_subcategory": "Cardiac Health",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 12,
        "sessions_per_week": 4,
        "session_duration_minutes": 30,
        "tags": ["Cardio", "Heart Health", "Low Impact"],
        "goals": ["Heart Health", "Endurance"],
        "description": "Safe cardiovascular exercise program for heart health and disease prevention.",
        "short_description": "Heart health cardio"
    },
    {
        "program_name": "Diabetes Management Exercise",
        "program_category": "Goal-Based",
        "program_subcategory": "Medical",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 12,
        "sessions_per_week": 4,
        "session_duration_minutes": 40,
        "tags": ["Diabetes", "Health", "Cardio"],
        "goals": ["Blood Sugar Control", "Health"],
        "description": "Exercise program to help manage blood sugar levels and improve insulin sensitivity.",
        "short_description": "Diabetes exercise"
    },
    {
        "program_name": "Wheelchair Athlete Upper Body",
        "program_category": "Goal-Based",
        "program_subcategory": "Adaptive Fitness",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 12,
        "sessions_per_week": 4,
        "session_duration_minutes": 60,
        "tags": ["Adaptive", "Wheelchair", "Upper Body"],
        "goals": ["Upper Body Strength", "Athletic Performance"],
        "description": "Upper body strength and conditioning for wheelchair athletes.",
        "short_description": "Wheelchair athlete training"
    },
    {
        "program_name": "Blind & Visually Impaired Fitness",
        "program_category": "Goal-Based",
        "program_subcategory": "Adaptive Fitness",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 10,
        "sessions_per_week": 3,
        "session_duration_minutes": 45,
        "tags": ["Adaptive", "Accessibility", "Safety"],
        "goals": ["Health", "Fitness"],
        "description": "Accessible fitness program designed for blind and visually impaired individuals.",
        "short_description": "Accessible fitness"
    },
    {
        "program_name": "Cancer Recovery Fitness",
        "program_category": "Goal-Based",
        "program_subcategory": "Medical Recovery",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 16,
        "sessions_per_week": 3,
        "session_duration_minutes": 30,
        "tags": ["Cancer", "Recovery", "Gentle"],
        "goals": ["Recovery", "Strength"],
        "description": "Gentle exercise program to aid cancer recovery and rebuild strength safely.",
        "short_description": "Cancer recovery fitness"
    },
    {
        "program_name": "Lymphedema Safe Exercise",
        "program_category": "Goal-Based",
        "program_subcategory": "Medical",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 12,
        "sessions_per_week": 3,
        "session_duration_minutes": 30,
        "tags": ["Lymphedema", "Safe", "Gentle"],
        "goals": ["Health", "Circulation"],
        "description": "Safe exercise protocol for individuals managing lymphedema.",
        "short_description": "Lymphedema-safe exercise"
    },
    {
        "program_name": "Fibromyalgia Gentle Movement",
        "program_category": "Goal-Based",
        "program_subcategory": "Medical",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 12,
        "sessions_per_week": 3,
        "session_duration_minutes": 25,
        "tags": ["Fibromyalgia", "Pain Management", "Gentle"],
        "goals": ["Pain Relief", "Mobility"],
        "description": "Gentle movement program for fibromyalgia pain management and function.",
        "short_description": "Fibromyalgia movement"
    },
    {
        "program_name": "Chronic Fatigue Syndrome Exercise",
        "program_category": "Goal-Based",
        "program_subcategory": "Medical",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 16,
        "sessions_per_week": 2,
        "session_duration_minutes": 20,
        "tags": ["CFS", "Energy Management", "Gentle"],
        "goals": ["Energy", "Function"],
        "description": "Carefully paced exercise for chronic fatigue syndrome with energy management.",
        "short_description": "CFS exercise protocol"
    },
    {
        "program_name": "Multiple Sclerosis Fitness",
        "program_category": "Goal-Based",
        "program_subcategory": "Medical",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 12,
        "sessions_per_week": 3,
        "session_duration_minutes": 30,
        "tags": ["MS", "Neurological", "Adapted"],
        "goals": ["Mobility", "Function"],
        "description": "Adapted exercise program for multiple sclerosis to maintain function and mobility.",
        "short_description": "MS fitness program"
    },
    {
        "program_name": "Parkinsons Disease Movement",
        "program_category": "Goal-Based",
        "program_subcategory": "Medical",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 16,
        "sessions_per_week": 4,
        "session_duration_minutes": 40,
        "tags": ["Parkinsons", "Balance", "Movement"],
        "goals": ["Balance", "Movement Quality"],
        "description": "Movement therapy for Parkinson's disease focusing on balance and coordination.",
        "short_description": "Parkinson's movement"
    },
    {
        "program_name": "Video Gamer Health & Posture",
        "program_category": "Goal-Based",
        "program_subcategory": "Occupational",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 8,
        "sessions_per_week": 4,
        "session_duration_minutes": 20,
        "tags": ["Gaming", "Posture", "Wrist Health"],
        "goals": ["Posture", "Health"],
        "description": "Counter sedentary gaming lifestyle with posture work and wrist health exercises.",
        "short_description": "Gamer health program"
    },
    {
        "program_name": "eSports Athlete Performance",
        "program_category": "Sport Training",
        "program_subcategory": "eSports",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 10,
        "sessions_per_week": 4,
        "session_duration_minutes": 30,
        "tags": ["eSports", "Reaction Time", "Endurance"],
        "goals": ["Reaction Time", "Mental Focus"],
        "description": "Physical training for eSports athletes: reaction time, endurance, and eye health.",
        "short_description": "eSports athlete training"
    },
    {
        "program_name": "Truck Driver Fitness",
        "program_category": "Goal-Based",
        "program_subcategory": "Occupational",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 10,
        "sessions_per_week": 3,
        "session_duration_minutes": 25,
        "tags": ["Truck Driver", "Sedentary", "Back Health"],
        "goals": ["Health", "Back Pain Relief"],
        "description": "Fitness program for truck drivers to combat sedentary lifestyle and back pain.",
        "short_description": "Truck driver fitness"
    },
    {
        "program_name": "Circus Arts Conditioning",
        "program_category": "Specialized Training",
        "program_subcategory": "Circus",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 16,
        "sessions_per_week": 5,
        "session_duration_minutes": 90,
        "tags": ["Circus", "Acrobatics", "Aerial"],
        "goals": ["Strength", "Flexibility"],
        "description": "Conditioning for circus arts: aerial silks, trapeze, acrobatics, and contortion.",
        "short_description": "Circus arts training"
    },
    {
        "program_name": "Pole Dancing Strength & Grace",
        "program_category": "Specialized Training",
        "program_subcategory": "Pole Fitness",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 12,
        "sessions_per_week": 3,
        "session_duration_minutes": 60,
        "tags": ["Pole", "Strength", "Dance"],
        "goals": ["Upper Body Strength", "Flexibility"],
        "description": "Build strength and grace for pole fitness and dance.",
        "short_description": "Pole fitness training"
    },
    {
        "program_name": "Slacklining Balance Training",
        "program_category": "Specialized Training",
        "program_subcategory": "Balance Sports",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 8,
        "sessions_per_week": 3,
        "session_duration_minutes": 30,
        "tags": ["Slackline", "Balance", "Core"],
        "goals": ["Balance", "Core Strength"],
        "description": "Develop exceptional balance and core strength through slacklining practice.",
        "short_description": "Slackline training"
    },
    {
        "program_name": "Stand-Up Paddleboarding Fitness",
        "program_category": "Sport Training",
        "program_subcategory": "SUP",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 8,
        "sessions_per_week": 3,
        "session_duration_minutes": 45,
        "tags": ["SUP", "Balance", "Core"],
        "goals": ["Balance", "Core Strength"],
        "description": "Build balance and core strength for stand-up paddleboarding.",
        "short_description": "SUP fitness"
    },
]

ALL_PROGRAMS.extend(FINAL_PROGRAMS_TO_250)

print(f"\n🎉 FINAL TOTAL: {len(ALL_PROGRAMS)} PROGRAMS! 🎉")
print(f"   Added final batch: {len(FINAL_PROGRAMS_TO_250)} programs")

# Final save
with open('/Users/saichetangrandhe/AIFitnessCoach/backend/scripts/all_programs_catalog.json', 'w') as f:
    json.dump(ALL_PROGRAMS, f, indent=2)

print(f"\n✅ COMPLETE! Saved {len(ALL_PROGRAMS)} programs to all_programs_catalog.json")
print(f"🚀 Ready for parallel generation with OpenAI!")

