"""
Complete list of 250+ workout program definitions
Organized by category for easy management
"""

PROGRAMS = [
    # ============================================================
    # CELEBRITY/ACTOR TRANSFORMATIONS (15 programs)
    # ============================================================
    {
        "program_name": "Brad Pitt Fight Club Workout",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Actor Transformation",
        "country": ["Global"],
        "celebrity_name": "Brad Pitt",
        "difficulty_level": "Intermediate",
        "duration_weeks": 8,
        "sessions_per_week": 4,
        "session_duration_minutes": 60,
        "tags": ["Celebrity", "Muscle Definition", "Functional Fitness"],
        "goals": ["Build Muscle", "Lose Fat"],
        "description": "Get Brad Pitt's lean, defined Fight Club physique through high-intensity training and targeted strength work.",
        "short_description": "Brad Pitt's lean Fight Club look"
    },
    {
        "program_name": "Henry Cavill Superman Workout",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Superhero Training",
        "country": ["Global"],
        "celebrity_name": "Henry Cavill",
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 5,
        "session_duration_minutes": 75,
        "tags": ["Celebrity", "Muscle Building", "Strength"],
        "goals": ["Build Muscle", "Increase Strength"],
        "description": "Build superhero mass like Henry Cavill through heavy compound lifts and progressive overload.",
        "short_description": "Superman's powerful physique"
    },
    {
        "program_name": "Chris Hemsworth Thor Workout",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Superhero Training",
        "country": ["Global"],
        "celebrity_name": "Chris Hemsworth",
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 6,
        "session_duration_minutes": 90,
        "tags": ["Celebrity", "Muscle Building", "Functional Strength"],
        "goals": ["Build Muscle", "Athletic Performance"],
        "description": "Build the massive, functional physique of Thor through intense training and compound movements.",
        "short_description": "Thor's godly physique"
    },
    {
        "program_name": "Dwayne The Rock Johnson Workout",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Bodybuilding",
        "country": ["Global"],
        "celebrity_name": "Dwayne Johnson",
        "difficulty_level": "Advanced",
        "duration_weeks": 16,
        "sessions_per_week": 6,
        "session_duration_minutes": 90,
        "tags": ["Celebrity", "Muscle Mass", "High Volume"],
        "goals": ["Build Muscle", "Increase Strength"],
        "description": "Train like The Rock with high-volume bodybuilding splits and intense dedication.",
        "short_description": "The Rock's massive build"
    },
    {
        "program_name": "Michael B Jordan Creed Workout",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Boxing Physique",
        "country": ["Global"],
        "celebrity_name": "Michael B Jordan",
        "difficulty_level": "Intermediate",
        "duration_weeks": 10,
        "sessions_per_week": 5,
        "session_duration_minutes": 75,
        "tags": ["Celebrity", "Boxing", "Functional Fitness"],
        "goals": ["Build Muscle", "Athletic Performance"],
        "description": "Develop a boxer's physique like Adonis Creed with boxing-focused training.",
        "short_description": "Creed's fighter physique"
    },
    {
        "program_name": "Jason Momoa Aquaman Workout",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Superhero Training",
        "country": ["Global"],
        "celebrity_name": "Jason Momoa",
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 5,
        "session_duration_minutes": 80,
        "tags": ["Celebrity", "Functional Strength", "Explosive Power"],
        "goals": ["Build Muscle", "Increase Strength"],
        "description": "Build Aquaman's warrior physique through climbing-inspired functional training.",
        "short_description": "Aquaman's warrior build"
    },
    {
        "program_name": "Zac Efron Baywatch Workout",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Beach Body",
        "country": ["Global"],
        "celebrity_name": "Zac Efron",
        "difficulty_level": "Intermediate",
        "duration_weeks": 8,
        "sessions_per_week": 5,
        "session_duration_minutes": 60,
        "tags": ["Celebrity", "Aesthetic", "Six Pack"],
        "goals": ["Build Muscle", "Lose Fat"],
        "description": "Achieve the ultimate beach body aesthetic with focused ab work and definition training.",
        "short_description": "Baywatch beach body"
    },
    {
        "program_name": "Ryan Reynolds Deadpool Workout",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Superhero Training",
        "country": ["Global"],
        "celebrity_name": "Ryan Reynolds",
        "difficulty_level": "Intermediate",
        "duration_weeks": 10,
        "sessions_per_week": 5,
        "session_duration_minutes": 70,
        "tags": ["Celebrity", "Lean Muscle", "Functional"],
        "goals": ["Build Muscle", "Lose Fat"],
        "description": "Build Deadpool's lean, athletic physique through varied training methods.",
        "short_description": "Deadpool's lean build"
    },
    {
        "program_name": "Chris Pratt Star-Lord Transformation",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Weight Loss Transformation",
        "country": ["Global"],
        "celebrity_name": "Chris Pratt",
        "difficulty_level": "Beginner",
        "duration_weeks": 16,
        "sessions_per_week": 5,
        "session_duration_minutes": 60,
        "tags": ["Celebrity", "Fat Loss", "Transformation"],
        "goals": ["Lose Fat", "Build Muscle"],
        "description": "Transform your body like Chris Pratt's dramatic Star-Lord transformation.",
        "short_description": "Star-Lord transformation"
    },
    {
        "program_name": "Tom Holland Spider-Man Workout",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Superhero Training",
        "country": ["Global"],
        "celebrity_name": "Tom Holland",
        "difficulty_level": "Intermediate",
        "duration_weeks": 8,
        "sessions_per_week": 5,
        "session_duration_minutes": 60,
        "tags": ["Celebrity", "Gymnastics", "Calisthenics"],
        "goals": ["Athletic Performance", "Build Muscle"],
        "description": "Build Spider-Man's agile, acrobatic physique through gymnastics and bodyweight training.",
        "short_description": "Spider-Man's agility"
    },
    {
        "program_name": "Hugh Jackman Wolverine Workout",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Superhero Training",
        "country": ["Global"],
        "celebrity_name": "Hugh Jackman",
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 6,
        "session_duration_minutes": 75,
        "tags": ["Celebrity", "Muscle Building", "Power"],
        "goals": ["Build Muscle", "Increase Strength"],
        "description": "Build Wolverine's powerful, muscular physique through heavy lifting and high intensity.",
        "short_description": "Wolverine's power"
    },
    {
        "program_name": "Arnold Schwarzenegger Classic Bodybuilding",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Bodybuilding",
        "country": ["Global"],
        "celebrity_name": "Arnold Schwarzenegger",
        "difficulty_level": "Advanced",
        "duration_weeks": 16,
        "sessions_per_week": 6,
        "session_duration_minutes": 120,
        "tags": ["Celebrity", "Bodybuilding", "Classic"],
        "goals": ["Build Muscle", "Increase Strength"],
        "description": "Train using Arnold's legendary bodybuilding methods from the Golden Era.",
        "short_description": "Arnold's classic routine"
    },
    {
        "program_name": "Chadwick Boseman Black Panther Workout",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Superhero Training",
        "country": ["Global"],
        "celebrity_name": "Chadwick Boseman",
        "difficulty_level": "Intermediate",
        "duration_weeks": 10,
        "sessions_per_week": 5,
        "session_duration_minutes": 70,
        "tags": ["Celebrity", "Martial Arts", "Functional"],
        "goals": ["Build Muscle", "Athletic Performance"],
        "description": "Develop Black Panther's warrior physique through martial arts-inspired training.",
        "short_description": "Black Panther's warrior build"
    },
    {
        "program_name": "Chris Evans Captain America Workout",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Superhero Training",
        "country": ["Global"],
        "celebrity_name": "Chris Evans",
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 5,
        "session_duration_minutes": 80,
        "tags": ["Celebrity", "Muscle Building", "Strength"],
        "goals": ["Build Muscle", "Increase Strength"],
        "description": "Build Captain America's superhero physique through compound strength training.",
        "short_description": "Cap's super soldier build"
    },
    {
        "program_name": "Will Smith Ali Boxing Transformation",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Boxing Physique",
        "country": ["Global"],
        "celebrity_name": "Will Smith",
        "difficulty_level": "Intermediate",
        "duration_weeks": 12,
        "sessions_per_week": 6,
        "session_duration_minutes": 90,
        "tags": ["Celebrity", "Boxing", "Conditioning"],
        "goals": ["Athletic Performance", "Build Muscle"],
        "description": "Train like Muhammad Ali with boxing-focused conditioning and strength work.",
        "short_description": "Ali's boxing physique"
    },

    # ============================================================
    # INDIAN CELEBRITY & SPORTS ICONS (15 programs)
    # ============================================================
    {
        "program_name": "MS Dhoni Cricket Fitness",
        "program_category": "Sport Training",
        "program_subcategory": "Cricket",
        "country": ["India"],
        "celebrity_name": "MS Dhoni",
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 6,
        "session_duration_minutes": 90,
        "tags": ["Cricket", "Endurance", "Explosiveness"],
        "goals": ["Athletic Performance", "Build Muscle"],
        "description": "Train like Captain Cool with cricket-specific fitness and mental toughness training.",
        "short_description": "Dhoni's cricket fitness"
    },
    {
        "program_name": "Virat Kohli Fitness Regime",
        "program_category": "Sport Training",
        "program_subcategory": "Cricket",
        "country": ["India"],
        "celebrity_name": "Virat Kohli",
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 6,
        "session_duration_minutes": 75,
        "tags": ["Cricket", "Athletic", "Discipline"],
        "goals": ["Athletic Performance", "Endurance"],
        "description": "Follow Virat Kohli's intense fitness philosophy with focus on discipline and performance.",
        "short_description": "Kohli's athletic regime"
    },
    {
        "program_name": "Hrithik Roshan Transformation",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Bollywood Fitness",
        "country": ["India"],
        "celebrity_name": "Hrithik Roshan",
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 6,
        "session_duration_minutes": 90,
        "tags": ["Bollywood", "Aesthetic", "Dance Fitness"],
        "goals": ["Build Muscle", "Lose Fat"],
        "description": "Achieve Bollywood's most aesthetic physique through Hrithik's intense training methods.",
        "short_description": "Hrithik's Greek God look"
    },
    {
        "program_name": "John Abraham Power Workout",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Bollywood Fitness",
        "country": ["India"],
        "celebrity_name": "John Abraham",
        "difficulty_level": "Advanced",
        "duration_weeks": 10,
        "sessions_per_week": 5,
        "session_duration_minutes": 75,
        "tags": ["Bollywood", "Muscle", "Power"],
        "goals": ["Build Muscle", "Increase Strength"],
        "description": "Build massive muscle like John Abraham through heavy compound movements.",
        "short_description": "John's powerful build"
    },
    {
        "program_name": "Tiger Shroff Martial Arts Fitness",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Bollywood Fitness",
        "country": ["India"],
        "celebrity_name": "Tiger Shroff",
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 6,
        "session_duration_minutes": 90,
        "tags": ["Bollywood", "Martial Arts", "Flexibility"],
        "goals": ["Athletic Performance", "Build Muscle"],
        "description": "Train like Tiger Shroff with martial arts, gymnastics, and incredible flexibility work.",
        "short_description": "Tiger's martial arts fitness"
    },
    {
        "program_name": "Ranveer Singh Energy Workout",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Bollywood Fitness",
        "country": ["India"],
        "celebrity_name": "Ranveer Singh",
        "difficulty_level": "Intermediate",
        "duration_weeks": 10,
        "sessions_per_week": 5,
        "session_duration_minutes": 70,
        "tags": ["Bollywood", "Functional", "High Energy"],
        "goals": ["Build Muscle", "Athletic Performance"],
        "description": "Match Ranveer's explosive energy with dynamic, fun, and intense workouts.",
        "short_description": "Ranveer's dynamic training"
    },
    {
        "program_name": "Akshay Kumar Martial Arts Training",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Bollywood Fitness",
        "country": ["India"],
        "celebrity_name": "Akshay Kumar",
        "difficulty_level": "Intermediate",
        "duration_weeks": 8,
        "sessions_per_week": 6,
        "session_duration_minutes": 75,
        "tags": ["Bollywood", "Martial Arts", "Discipline"],
        "goals": ["Athletic Performance", "Flexibility"],
        "description": "Follow Akshay Kumar's disciplined martial arts and functional fitness approach.",
        "short_description": "Akshay's martial discipline"
    },
    {
        "program_name": "Shahid Kapoor Fighter Physique",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Bollywood Fitness",
        "country": ["India"],
        "celebrity_name": "Shahid Kapoor",
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 6,
        "session_duration_minutes": 80,
        "tags": ["Bollywood", "Lean Muscle", "Aesthetic"],
        "goals": ["Build Muscle", "Lose Fat"],
        "description": "Achieve Shahid's lean, muscular fighter physique through intense training.",
        "short_description": "Shahid's fighter look"
    },
    {
        "program_name": "Sushant Singh Rajput MS Dhoni Transformation",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Bollywood Fitness",
        "country": ["India"],
        "celebrity_name": "Sushant Singh Rajput",
        "difficulty_level": "Intermediate",
        "duration_weeks": 10,
        "sessions_per_week": 5,
        "session_duration_minutes": 75,
        "tags": ["Bollywood", "Cricket Fitness", "Athletic"],
        "goals": ["Athletic Performance", "Build Muscle"],
        "description": "Transform into an athlete like Sushant did for the Dhoni biopic.",
        "short_description": "Sushant's athlete transformation"
    },
    {
        "program_name": "Farhan Akhtar Bhaag Milkha Bhaag",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Bollywood Fitness",
        "country": ["India"],
        "celebrity_name": "Farhan Akhtar",
        "difficulty_level": "Advanced",
        "duration_weeks": 16,
        "sessions_per_week": 6,
        "session_duration_minutes": 90,
        "tags": ["Bollywood", "Running", "Endurance"],
        "goals": ["Athletic Performance", "Endurance"],
        "description": "Train like a champion sprinter with Farhan's Milkha Singh transformation program.",
        "short_description": "Farhan's sprinter training"
    },
    {
        "program_name": "Deepika Padukone Athletic Fitness",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Bollywood Fitness",
        "country": ["India"],
        "celebrity_name": "Deepika Padukone",
        "difficulty_level": "Intermediate",
        "duration_weeks": 8,
        "sessions_per_week": 5,
        "session_duration_minutes": 60,
        "tags": ["Bollywood", "Women", "Athletic"],
        "goals": ["Toning", "Athletic Performance"],
        "description": "Achieve Deepika's tall, athletic, and graceful physique through balanced training.",
        "short_description": "Deepika's athletic grace"
    },
    {
        "program_name": "Katrina Kaif Dance Fitness",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Bollywood Fitness",
        "country": ["India"],
        "celebrity_name": "Katrina Kaif",
        "difficulty_level": "Intermediate",
        "duration_weeks": 8,
        "sessions_per_week": 5,
        "session_duration_minutes": 60,
        "tags": ["Bollywood", "Women", "Dance"],
        "goals": ["Toning", "Flexibility"],
        "description": "Train like Katrina with dance-based cardio, flexibility, and toning work.",
        "short_description": "Katrina's dance fitness"
    },
    {
        "program_name": "Shilpa Shetty Yoga Fitness",
        "program_category": "Celebrity Workout",
        "program_subcategory": "Bollywood Fitness",
        "country": ["India"],
        "celebrity_name": "Shilpa Shetty",
        "difficulty_level": "Beginner",
        "duration_weeks": 8,
        "sessions_per_week": 5,
        "session_duration_minutes": 45,
        "tags": ["Bollywood", "Yoga", "Wellness"],
        "goals": ["Flexibility", "Wellness"],
        "description": "Follow Shilpa Shetty's yoga-focused wellness and fitness approach.",
        "short_description": "Shilpa's yoga wellness"
    },
    {
        "program_name": "PV Sindhu Badminton Conditioning",
        "program_category": "Sport Training",
        "program_subcategory": "Badminton",
        "country": ["India"],
        "celebrity_name": "PV Sindhu",
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 6,
        "session_duration_minutes": 90,
        "tags": ["Badminton", "Women", "Agility"],
        "goals": ["Athletic Performance", "Endurance"],
        "description": "Train with Olympic medalist PV Sindhu's badminton-specific conditioning program.",
        "short_description": "Sindhu's badminton training"
    },
    {
        "program_name": "Mary Kom Boxing Fitness",
        "program_category": "Sport Training",
        "program_subcategory": "Boxing",
        "country": ["India"],
        "celebrity_name": "Mary Kom",
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 6,
        "session_duration_minutes": 90,
        "tags": ["Boxing", "Women", "Strength"],
        "goals": ["Athletic Performance", "Build Muscle"],
        "description": "Train like a champion boxer with Mary Kom's intense boxing conditioning.",
        "short_description": "Mary Kom's boxing power"
    },

    # ============================================================
    # WOMEN'S HEALTH & FITNESS (45 programs)
    # ============================================================
    {
        "program_name": "Pregnancy First Trimester Safe Workout",
        "program_category": "Women's Health",
        "program_subcategory": "Pregnancy",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 12,
        "sessions_per_week": 3,
        "session_duration_minutes": 30,
        "tags": ["Pregnancy", "Women", "Safe Exercise"],
        "goals": ["Health", "Wellness"],
        "description": "Safe, gentle exercises for the first trimester of pregnancy focusing on low-impact movement.",
        "short_description": "First trimester safe exercise"
    },
    {
        "program_name": "Pregnancy Second Trimester Strength",
        "program_category": "Women's Health",
        "program_subcategory": "Pregnancy",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 12,
        "sessions_per_week": 3,
        "session_duration_minutes": 40,
        "tags": ["Pregnancy", "Women", "Strength"],
        "goals": ["Health", "Maintain Fitness"],
        "description": "Modified strength training safe for second trimester with focus on maintaining fitness.",
        "short_description": "Second trimester strength"
    },
    {
        "program_name": "Pregnancy Third Trimester Mobility",
        "program_category": "Women's Health",
        "program_subcategory": "Pregnancy",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 12,
        "sessions_per_week": 3,
        "session_duration_minutes": 30,
        "tags": ["Pregnancy", "Women", "Mobility"],
        "goals": ["Health", "Flexibility"],
        "description": "Gentle mobility and stretching for third trimester comfort and birth preparation.",
        "short_description": "Third trimester mobility"
    },
    {
        "program_name": "Postpartum Recovery 0-6 Weeks",
        "program_category": "Women's Health",
        "program_subcategory": "Postpartum",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 6,
        "sessions_per_week": 3,
        "session_duration_minutes": 20,
        "tags": ["Postpartum", "Women", "Recovery"],
        "goals": ["Health", "Recovery"],
        "description": "Gentle postpartum recovery exercises focusing on pelvic floor and core healing.",
        "short_description": "Early postpartum recovery"
    },
    {
        "program_name": "Postpartum Rebuild 6-12 Weeks",
        "program_category": "Women's Health",
        "program_subcategory": "Postpartum",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 6,
        "sessions_per_week": 4,
        "session_duration_minutes": 30,
        "tags": ["Postpartum", "Women", "Rebuild"],
        "goals": ["Health", "Regain Strength"],
        "description": "Rebuild core and pelvic floor strength after clearance from healthcare provider.",
        "short_description": "Postpartum rebuild"
    },
    {
        "program_name": "Postpartum Body Transformation 3-6 Months",
        "program_category": "Women's Health",
        "program_subcategory": "Postpartum",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 12,
        "sessions_per_week": 4,
        "session_duration_minutes": 45,
        "tags": ["Postpartum", "Women", "Fat Loss"],
        "goals": ["Lose Fat", "Build Muscle"],
        "description": "Return to fitness and transform your body safely after postpartum recovery period.",
        "short_description": "Postpartum transformation"
    },
    {
        "program_name": "PCOS Weight Management",
        "program_category": "Women's Health",
        "program_subcategory": "Hormonal Health",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 12,
        "sessions_per_week": 4,
        "session_duration_minutes": 50,
        "tags": ["PCOS", "Women", "Weight Loss"],
        "goals": ["Lose Fat", "Hormonal Balance"],
        "description": "Exercise program designed to manage PCOS symptoms and support healthy weight loss.",
        "short_description": "PCOS weight management"
    },
    {
        "program_name": "PCOS Strength & Insulin Sensitivity",
        "program_category": "Women's Health",
        "program_subcategory": "Hormonal Health",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 12,
        "sessions_per_week": 4,
        "session_duration_minutes": 55,
        "tags": ["PCOS", "Women", "Strength"],
        "goals": ["Build Muscle", "Hormonal Balance"],
        "description": "Build muscle and improve insulin sensitivity with PCOS-friendly strength training.",
        "short_description": "PCOS strength training"
    },
    {
        "program_name": "Menopause Fitness Foundation",
        "program_category": "Women's Health",
        "program_subcategory": "Menopause",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 8,
        "sessions_per_week": 3,
        "session_duration_minutes": 40,
        "tags": ["Menopause", "Women", "Bone Health"],
        "goals": ["Health", "Maintain Fitness"],
        "description": "Foundation fitness program for managing menopause symptoms and maintaining health.",
        "short_description": "Menopause fitness basics"
    },
    {
        "program_name": "Menopause Strength & Bone Density",
        "program_category": "Women's Health",
        "program_subcategory": "Menopause",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 12,
        "sessions_per_week": 4,
        "session_duration_minutes": 50,
        "tags": ["Menopause", "Women", "Bone Health"],
        "goals": ["Increase Strength", "Bone Density"],
        "description": "Combat bone density loss and build strength during menopause with resistance training.",
        "short_description": "Menopause strength"
    },
    {
        "program_name": "Women's Pelvic Floor Beginner",
        "program_category": "Women's Health",
        "program_subcategory": "Pelvic Health",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 6,
        "sessions_per_week": 4,
        "session_duration_minutes": 20,
        "tags": ["Women", "Pelvic Floor", "Core"],
        "goals": ["Health", "Pelvic Strength"],
        "description": "Introduction to pelvic floor exercises for women to prevent and treat dysfunction.",
        "short_description": "Women's pelvic floor basics"
    },
    {
        "program_name": "Women's Pelvic Floor Advanced",
        "program_category": "Women's Health",
        "program_subcategory": "Pelvic Health",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 8,
        "sessions_per_week": 5,
        "session_duration_minutes": 30,
        "tags": ["Women", "Pelvic Floor", "Core Strength"],
        "goals": ["Pelvic Strength", "Core Stability"],
        "description": "Advanced pelvic floor strengthening integrated with functional movement patterns.",
        "short_description": "Advanced pelvic floor"
    },
    {
        "program_name": "Diastasis Recti Recovery",
        "program_category": "Women's Health",
        "program_subcategory": "Postpartum",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 12,
        "sessions_per_week": 4,
        "session_duration_minutes": 25,
        "tags": ["Postpartum", "Women", "Core Recovery"],
        "goals": ["Health", "Core Healing"],
        "description": "Heal diastasis recti with targeted exercises and proper core reconnection.",
        "short_description": "Diastasis recti healing"
    },
    {
        "program_name": "Women's Hormone Balance Yoga",
        "program_category": "Women's Health",
        "program_subcategory": "Hormonal Health",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 8,
        "sessions_per_week": 3,
        "session_duration_minutes": 45,
        "tags": ["Women", "Yoga", "Hormones"],
        "goals": ["Hormonal Balance", "Wellness"],
        "description": "Yoga sequences designed to support hormonal balance throughout the menstrual cycle.",
        "short_description": "Hormone balance yoga"
    },
    {
        "program_name": "Women's Aesthetic Lean Toning",
        "program_category": "Women's Health",
        "program_subcategory": "Aesthetic Goals",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 12,
        "sessions_per_week": 4,
        "session_duration_minutes": 50,
        "tags": ["Women", "Toning", "Lean Muscle"],
        "goals": ["Toning", "Lose Fat"],
        "description": "Build lean, toned muscle with a focus on aesthetic goals for women.",
        "short_description": "Women's lean toning"
    },
    {
        "program_name": "Women's Glute Building Program",
        "program_category": "Women's Health",
        "program_subcategory": "Aesthetic Goals",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 10,
        "sessions_per_week": 4,
        "session_duration_minutes": 55,
        "tags": ["Women", "Glutes", "Strength"],
        "goals": ["Build Muscle", "Toning"],
        "description": "Build strong, sculpted glutes with progressive overload and targeted exercises.",
        "short_description": "Women's glute building"
    },
    {
        "program_name": "Women's Full Body Strength",
        "program_category": "Women's Health",
        "program_subcategory": "Strength Training",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 12,
        "sessions_per_week": 4,
        "session_duration_minutes": 60,
        "tags": ["Women", "Strength", "Full Body"],
        "goals": ["Build Muscle", "Increase Strength"],
        "description": "Comprehensive full-body strength training program designed for women.",
        "short_description": "Women's full body strength"
    },
    {
        "program_name": "Women's Upper Body Strength",
        "program_category": "Women's Health",
        "program_subcategory": "Strength Training",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 8,
        "sessions_per_week": 3,
        "session_duration_minutes": 40,
        "tags": ["Women", "Upper Body", "Strength"],
        "goals": ["Build Muscle", "Increase Strength"],
        "description": "Build upper body strength and confidence with women-focused programming.",
        "short_description": "Women's upper body"
    },
    {
        "program_name": "Women's Bodyweight Home Workout",
        "program_category": "Women's Health",
        "program_subcategory": "Home Training",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 8,
        "sessions_per_week": 4,
        "session_duration_minutes": 30,
        "tags": ["Women", "Bodyweight", "Home"],
        "goals": ["Toning", "Fitness"],
        "description": "Effective bodyweight training for women that can be done at home with minimal equipment.",
        "short_description": "Women's home bodyweight"
    },
    {
        "program_name": "Women's HIIT Fat Loss",
        "program_category": "Women's Health",
        "program_subcategory": "Fat Loss",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 8,
        "sessions_per_week": 4,
        "session_duration_minutes": 30,
        "tags": ["Women", "HIIT", "Fat Loss"],
        "goals": ["Lose Fat", "Conditioning"],
        "description": "High-intensity interval training designed for women's fat loss goals.",
        "short_description": "Women's HIIT fat loss"
    },

    # ============================================================
    # MEN'S HEALTH (15 programs)
    # ============================================================
    {
        "program_name": "Men's Pelvic Floor Beginner",
        "program_category": "Men's Health",
        "program_subcategory": "Pelvic Health",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 6,
        "sessions_per_week": 4,
        "session_duration_minutes": 15,
        "tags": ["Men", "Pelvic Floor", "Health"],
        "goals": ["Health", "Pelvic Strength"],
        "description": "Introduction to pelvic floor exercises for men to improve bladder control and core stability.",
        "short_description": "Men's pelvic floor basics"
    },
    {
        "program_name": "Men's Pelvic Floor Advanced",
        "program_category": "Men's Health",
        "program_subcategory": "Pelvic Health",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 8,
        "sessions_per_week": 5,
        "session_duration_minutes": 25,
        "tags": ["Men", "Pelvic Floor", "Core"],
        "goals": ["Pelvic Strength", "Core Stability"],
        "description": "Advanced pelvic floor training for men integrated with functional strength work.",
        "short_description": "Advanced men's pelvic floor"
    },
    {
        "program_name": "Men's Testosterone Boosting Workout",
        "program_category": "Men's Health",
        "program_subcategory": "Hormonal Health",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 12,
        "sessions_per_week": 4,
        "session_duration_minutes": 60,
        "tags": ["Men", "Testosterone", "Strength"],
        "goals": ["Build Muscle", "Hormonal Health"],
        "description": "Compound lift-focused program designed to naturally support testosterone levels.",
        "short_description": "Testosterone boosting"
    },
    {
        "program_name": "Men Over 40 Fitness",
        "program_category": "Men's Health",
        "program_subcategory": "Age-Specific",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 12,
        "sessions_per_week": 4,
        "session_duration_minutes": 50,
        "tags": ["Men", "Over 40", "Health"],
        "goals": ["Maintain Fitness", "Health"],
        "description": "Age-appropriate fitness program for men over 40 focusing on longevity and vitality.",
        "short_description": "Men's 40+ fitness"
    },
    {
        "program_name": "Men Over 50 Strength & Mobility",
        "program_category": "Men's Health",
        "program_subcategory": "Age-Specific",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 12,
        "sessions_per_week": 3,
        "session_duration_minutes": 45,
        "tags": ["Men", "Over 50", "Mobility"],
        "goals": ["Maintain Fitness", "Mobility"],
        "description": "Strength and mobility program for men over 50 to maintain independence and function.",
        "short_description": "Men's 50+ strength"
    },
    {
        "program_name": "Men's Core & Abs Definition",
        "program_category": "Men's Health",
        "program_subcategory": "Aesthetic Goals",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 8,
        "sessions_per_week": 5,
        "session_duration_minutes": 30,
        "tags": ["Men", "Abs", "Core"],
        "goals": ["Lose Fat", "Core Strength"],
        "description": "Build visible abs and core strength with targeted training and conditioning.",
        "short_description": "Men's abs definition"
    },
    {
        "program_name": "Men's Chest & Arms Hypertrophy",
        "program_category": "Men's Health",
        "program_subcategory": "Aesthetic Goals",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 10,
        "sessions_per_week": 4,
        "session_duration_minutes": 60,
        "tags": ["Men", "Chest", "Arms"],
        "goals": ["Build Muscle", "Aesthetic"],
        "description": "Build impressive chest and arm muscles with focused hypertrophy training.",
        "short_description": "Chest & arms growth"
    },
    {
        "program_name": "Men's Power & Explosiveness",
        "program_category": "Men's Health",
        "program_subcategory": "Athletic Performance",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 8,
        "sessions_per_week": 4,
        "session_duration_minutes": 60,
        "tags": ["Men", "Power", "Explosive"],
        "goals": ["Athletic Performance", "Increase Strength"],
        "description": "Develop explosive power and athleticism with Olympic lifts and plyometrics.",
        "short_description": "Men's explosive power"
    },
    {
        "program_name": "Men's Functional Fitness",
        "program_category": "Men's Health",
        "program_subcategory": "Functional Training",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 12,
        "sessions_per_week": 4,
        "session_duration_minutes": 55,
        "tags": ["Men", "Functional", "Real World"],
        "goals": ["Athletic Performance", "Functional Strength"],
        "description": "Build functional strength for real-world activities and everyday performance.",
        "short_description": "Men's functional training"
    },
    {
        "program_name": "Men's Beginner Muscle Building",
        "program_category": "Men's Health",
        "program_subcategory": "Beginner Programs",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 12,
        "sessions_per_week": 3,
        "session_duration_minutes": 50,
        "tags": ["Men", "Beginner", "Muscle"],
        "goals": ["Build Muscle", "Learn Fundamentals"],
        "description": "Perfect introduction to muscle building for men new to weight training.",
        "short_description": "Beginner muscle building"
    },
    {
        "program_name": "Dad Bod to Fit Dad",
        "program_category": "Men's Health",
        "program_subcategory": "Body Transformation",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Beginner",
        "duration_weeks": 16,
        "sessions_per_week": 4,
        "session_duration_minutes": 45,
        "tags": ["Men", "Fat Loss", "Transformation"],
        "goals": ["Lose Fat", "Build Muscle"],
        "description": "Transform from dad bod to fit dad with balanced training and realistic progression.",
        "short_description": "Dad bod transformation"
    },
    {
        "program_name": "Men's Strongman Training",
        "program_category": "Men's Health",
        "program_subcategory": "Strength Sports",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 12,
        "sessions_per_week": 4,
        "session_duration_minutes": 90,
        "tags": ["Men", "Strongman", "Strength"],
        "goals": ["Increase Strength", "Build Muscle"],
        "description": "Train like a strongman with event training and maximal strength development.",
        "short_description": "Strongman training"
    },
    {
        "program_name": "Men's Powerlifting Foundation",
        "program_category": "Men's Health",
        "program_subcategory": "Strength Sports",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 12,
        "sessions_per_week": 4,
        "session_duration_minutes": 75,
        "tags": ["Men", "Powerlifting", "Strength"],
        "goals": ["Increase Strength", "Competition Prep"],
        "description": "Build a foundation in powerlifting with focus on squat, bench, and deadlift.",
        "short_description": "Powerlifting basics"
    },
    {
        "program_name": "Men's Calisthenics Mastery",
        "program_category": "Men's Health",
        "program_subcategory": "Bodyweight Training",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Intermediate",
        "duration_weeks": 12,
        "sessions_per_week": 5,
        "session_duration_minutes": 50,
        "tags": ["Men", "Calisthenics", "Bodyweight"],
        "goals": ["Build Muscle", "Athletic Performance"],
        "description": "Master advanced calisthenics skills and build impressive bodyweight strength.",
        "short_description": "Calisthenics mastery"
    },
    {
        "program_name": "Men's Athletic Conditioning",
        "program_category": "Men's Health",
        "program_subcategory": "Athletic Performance",
        "country": ["Global"],
        "celebrity_name": None,
        "difficulty_level": "Advanced",
        "duration_weeks": 8,
        "sessions_per_week": 5,
        "session_duration_minutes": 60,
        "tags": ["Men", "Conditioning", "Athletic"],
        "goals": ["Athletic Performance", "Conditioning"],
        "description": "Elite athletic conditioning program for men seeking peak performance.",
        "short_description": "Elite conditioning"
    },
]

# Continuing with remaining categories...
# Total so far: ~90 programs
