-- 2084_rewrite_exercise_instructions.sql
-- Auto-generated by backend/scripts/rewrite_exercise_instructions.py.
-- Rewrites deficient exercise instructions using the app's own vetted
-- instruction engine, routed by a correct deterministic classifier.
-- Backs up originals first. NO LLM. The MV refresh is NOT here —
-- apply_2084_rewrite.py runs it separately (REFRESH ... CONCURRENTLY
-- cannot run inside a transaction).

CREATE TABLE IF NOT EXISTS public.exercise_instruction_backup (
    id uuid NOT NULL,
    source_table text NOT NULL,
    old_instructions text,
    new_instructions text,
    movement_class text,
    rewrite_method text NOT NULL DEFAULT 'rule',
    source_citation text,
    rewrite_batch text NOT NULL,
    backed_up_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id, rewrite_batch)
);

INSERT INTO public.exercise_instruction_backup
  (id, source_table, old_instructions, new_instructions, movement_class,
   source_citation, rewrite_batch)
SELECT id, 'exercise_library', instructions, $instr$1. Set the pad at your hip crease so you can hinge freely, ankles secured under the rollers.
2. Cross your arms on your chest (or place fingertips at your temples) and brace your core.
3. Hinge DOWN at the hips with a flat, neutral spine — this is a hip hinge, not a back bend.
4. Lower until you feel a stretch in the hamstrings, with the torso pointing toward the floor.
5. Raise back up by squeezing the glutes; stop in a straight line, do not arch past it.
6. Breathing: Inhale as you lower under control. Exhale as you raise back up. Keep the core braced throughout — do not hold your breath.
7. Form check: Keep a neutral spine the whole rep — never round or yank the lower back.
8. Form check: Finish in a straight line; hyperextending hard at the top stresses the spine.
9. The 45 Degree Hyperextension (Arms In Front Of Chest) mainly trains your Lower Back (erector spinae), Glutes (gluteus maximus, gluteus mideus). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$, 'back_extension',
  $instr$[rule | engine=exercise_instruction_copy.dart | class=back_extension] NSCA ESSC 4th ed. ch.13; McGill, Low Back Disorders 2nd ed. — neutral-spine hip hinge$instr$, '2085-2026-05-18'
FROM public.exercise_library WHERE id = 'b942f7f6-f23f-442d-8038-2d2c33da5e56'
  AND NOT EXISTS (SELECT 1 FROM public.exercise_instruction_backup
                  WHERE id = 'b942f7f6-f23f-442d-8038-2d2c33da5e56');
UPDATE public.exercise_library SET instructions = $instr$1. Set the pad at your hip crease so you can hinge freely, ankles secured under the rollers.
2. Cross your arms on your chest (or place fingertips at your temples) and brace your core.
3. Hinge DOWN at the hips with a flat, neutral spine — this is a hip hinge, not a back bend.
4. Lower until you feel a stretch in the hamstrings, with the torso pointing toward the floor.
5. Raise back up by squeezing the glutes; stop in a straight line, do not arch past it.
6. Breathing: Inhale as you lower under control. Exhale as you raise back up. Keep the core braced throughout — do not hold your breath.
7. Form check: Keep a neutral spine the whole rep — never round or yank the lower back.
8. Form check: Finish in a straight line; hyperextending hard at the top stresses the spine.
9. The 45 Degree Hyperextension (Arms In Front Of Chest) mainly trains your Lower Back (erector spinae), Glutes (gluteus maximus, gluteus mideus). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$ WHERE id = 'b942f7f6-f23f-442d-8038-2d2c33da5e56';

INSERT INTO public.exercise_instruction_backup
  (id, source_table, old_instructions, new_instructions, movement_class,
   source_citation, rewrite_batch)
SELECT id, 'exercise_library', instructions, $instr$1. Kneel on a mat (stand only if advanced), gripping the wheel directly under your shoulders.
2. Brace your core hard and tuck the pelvis so the lower back cannot arch.
3. Roll the wheel forward slowly, extending only as far as you keep the back flat.
4. Stop before the hips sag or the lower back arches — that point is your range.
5. Pull through your core to roll the wheel back to the start.
6. Breathing: Inhale and brace before rolling out. Exhale as you roll the wheel back in. Hold the brace the whole rep — do not hold your breath.
7. Form check: Never let the lower back arch — shorten the range instead.
8. Form check: Beginners: start with a short range or roll out toward a wall, then extend over time.
9. The Ab Wheel All The Way Out mainly trains your Abdominals (rectus abdominis). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$, 'ab_wheel',
  $instr$[rule | engine=exercise_instruction_copy.dart | class=ab_wheel] NASM EPFT 6th ed. ch.9; McGill, Low Back Disorders 2nd ed. — trunk / core training$instr$, '2085-2026-05-18'
FROM public.exercise_library WHERE id = 'aafbf405-2fc5-465b-9703-ecff8c6251ad'
  AND NOT EXISTS (SELECT 1 FROM public.exercise_instruction_backup
                  WHERE id = 'aafbf405-2fc5-465b-9703-ecff8c6251ad');
UPDATE public.exercise_library SET instructions = $instr$1. Kneel on a mat (stand only if advanced), gripping the wheel directly under your shoulders.
2. Brace your core hard and tuck the pelvis so the lower back cannot arch.
3. Roll the wheel forward slowly, extending only as far as you keep the back flat.
4. Stop before the hips sag or the lower back arches — that point is your range.
5. Pull through your core to roll the wheel back to the start.
6. Breathing: Inhale and brace before rolling out. Exhale as you roll the wheel back in. Hold the brace the whole rep — do not hold your breath.
7. Form check: Never let the lower back arch — shorten the range instead.
8. Form check: Beginners: start with a short range or roll out toward a wall, then extend over time.
9. The Ab Wheel All The Way Out mainly trains your Abdominals (rectus abdominis). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$ WHERE id = 'aafbf405-2fc5-465b-9703-ecff8c6251ad';

INSERT INTO public.exercise_instruction_backup
  (id, source_table, old_instructions, new_instructions, movement_class,
   source_citation, rewrite_batch)
SELECT id, 'exercise_library', instructions, $instr$1. Kneel on a mat (stand only if advanced), gripping the wheel directly under your shoulders.
2. Brace your core hard and tuck the pelvis so the lower back cannot arch.
3. Roll the wheel forward slowly, extending only as far as you keep the back flat.
4. Stop before the hips sag or the lower back arches — that point is your range.
5. Pull through your core to roll the wheel back to the start.
6. Breathing: Inhale and brace before rolling out. Exhale as you roll the wheel back in. Hold the brace the whole rep — do not hold your breath.
7. Form check: Never let the lower back arch — shorten the range instead.
8. Form check: Beginners: start with a short range or roll out toward a wall, then extend over time.
9. The Ab Wheel Halfway Out mainly trains your Abdominals (rectus abdominis). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$, 'ab_wheel',
  $instr$[rule | engine=exercise_instruction_copy.dart | class=ab_wheel] NASM EPFT 6th ed. ch.9; McGill, Low Back Disorders 2nd ed. — trunk / core training$instr$, '2085-2026-05-18'
FROM public.exercise_library WHERE id = 'c98ba7a7-7573-4d27-aad6-3ae329c7f91c'
  AND NOT EXISTS (SELECT 1 FROM public.exercise_instruction_backup
                  WHERE id = 'c98ba7a7-7573-4d27-aad6-3ae329c7f91c');
UPDATE public.exercise_library SET instructions = $instr$1. Kneel on a mat (stand only if advanced), gripping the wheel directly under your shoulders.
2. Brace your core hard and tuck the pelvis so the lower back cannot arch.
3. Roll the wheel forward slowly, extending only as far as you keep the back flat.
4. Stop before the hips sag or the lower back arches — that point is your range.
5. Pull through your core to roll the wheel back to the start.
6. Breathing: Inhale and brace before rolling out. Exhale as you roll the wheel back in. Hold the brace the whole rep — do not hold your breath.
7. Form check: Never let the lower back arch — shorten the range instead.
8. Form check: Beginners: start with a short range or roll out toward a wall, then extend over time.
9. The Ab Wheel Halfway Out mainly trains your Abdominals (rectus abdominis). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$ WHERE id = 'c98ba7a7-7573-4d27-aad6-3ae329c7f91c';

INSERT INTO public.exercise_instruction_backup
  (id, source_table, old_instructions, new_instructions, movement_class,
   source_citation, rewrite_batch)
SELECT id, 'exercise_library', instructions, $instr$1. Lie on your back with your lower back lightly pressed into the floor.
2. Brace your abs and lift your shoulders or legs only as far as the brace holds.
3. Move with control through the prescribed range — heel touch, toe tap, or leg movement.
4. Keep your lower back in contact with the floor for the whole set.
5. Lower under control; do not let the legs or shoulders crash down.
6. Breathing: Exhale as you contract the abs. Inhale as you return to the start. Breathe steadily — do not hold your breath.
7. Form check: If your lower back lifts off the floor, reduce the range.
8. Form check: Move from the abs — do not yank the neck or swing the legs.
9. The Alternate Heel Touches mainly trains your Abdominals (rectus abdominis), Obliques (external and internal obliques). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$, 'floor_core',
  $instr$[rule | engine=exercise_instruction_copy.dart | class=floor_core] NASM EPFT 6th ed. ch.9; McGill, Low Back Disorders 2nd ed. — trunk / core training$instr$, '2085-2026-05-18'
FROM public.exercise_library WHERE id = '585633c0-d32c-498c-b50d-a6ddbd3f87c7'
  AND NOT EXISTS (SELECT 1 FROM public.exercise_instruction_backup
                  WHERE id = '585633c0-d32c-498c-b50d-a6ddbd3f87c7');
UPDATE public.exercise_library SET instructions = $instr$1. Lie on your back with your lower back lightly pressed into the floor.
2. Brace your abs and lift your shoulders or legs only as far as the brace holds.
3. Move with control through the prescribed range — heel touch, toe tap, or leg movement.
4. Keep your lower back in contact with the floor for the whole set.
5. Lower under control; do not let the legs or shoulders crash down.
6. Breathing: Exhale as you contract the abs. Inhale as you return to the start. Breathe steadily — do not hold your breath.
7. Form check: If your lower back lifts off the floor, reduce the range.
8. Form check: Move from the abs — do not yank the neck or swing the legs.
9. The Alternate Heel Touches mainly trains your Abdominals (rectus abdominis), Obliques (external and internal obliques). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$ WHERE id = '585633c0-d32c-498c-b50d-a6ddbd3f87c7';

INSERT INTO public.exercise_instruction_backup
  (id, source_table, old_instructions, new_instructions, movement_class,
   source_citation, rewrite_batch)
SELECT id, 'exercise_library', instructions, $instr$1. Lie on your back with your lower back lightly pressed into the floor.
2. Brace your abs and lift your shoulders or legs only as far as the brace holds.
3. Move with control through the prescribed range — heel touch, toe tap, or leg movement.
4. Keep your lower back in contact with the floor for the whole set.
5. Lower under control; do not let the legs or shoulders crash down.
6. Breathing: Exhale as you contract the abs. Inhale as you return to the start. Breathe steadily — do not hold your breath.
7. Form check: If your lower back lifts off the floor, reduce the range.
8. Form check: Move from the abs — do not yank the neck or swing the legs.
9. The Alternate Leg Pull mainly trains your Abdominals (rectus abdominis), Hip Flexors (iliopsoas). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$, 'floor_core',
  $instr$[rule | engine=exercise_instruction_copy.dart | class=floor_core] NASM EPFT 6th ed. ch.9; McGill, Low Back Disorders 2nd ed. — trunk / core training$instr$, '2085-2026-05-18'
FROM public.exercise_library WHERE id = 'c6bbf304-dd87-48e2-b5fb-194ddea2d885'
  AND NOT EXISTS (SELECT 1 FROM public.exercise_instruction_backup
                  WHERE id = 'c6bbf304-dd87-48e2-b5fb-194ddea2d885');
UPDATE public.exercise_library SET instructions = $instr$1. Lie on your back with your lower back lightly pressed into the floor.
2. Brace your abs and lift your shoulders or legs only as far as the brace holds.
3. Move with control through the prescribed range — heel touch, toe tap, or leg movement.
4. Keep your lower back in contact with the floor for the whole set.
5. Lower under control; do not let the legs or shoulders crash down.
6. Breathing: Exhale as you contract the abs. Inhale as you return to the start. Breathe steadily — do not hold your breath.
7. Form check: If your lower back lifts off the floor, reduce the range.
8. Form check: Move from the abs — do not yank the neck or swing the legs.
9. The Alternate Leg Pull mainly trains your Abdominals (rectus abdominis), Hip Flexors (iliopsoas). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$ WHERE id = 'c6bbf304-dd87-48e2-b5fb-194ddea2d885';

INSERT INTO public.exercise_instruction_backup
  (id, source_table, old_instructions, new_instructions, movement_class,
   source_citation, rewrite_batch)
SELECT id, 'exercise_library', instructions, $instr$1. Lie on your back with your lower back lightly pressed into the floor.
2. Brace your abs and lift your shoulders or legs only as far as the brace holds.
3. Move with control through the prescribed range — heel touch, toe tap, or leg movement.
4. Keep your lower back in contact with the floor for the whole set.
5. Lower under control; do not let the legs or shoulders crash down.
6. Breathing: Exhale as you contract the abs. Inhale as you return to the start. Breathe steadily — do not hold your breath.
7. Form check: If your lower back lifts off the floor, reduce the range.
8. Form check: Move from the abs — do not yank the neck or swing the legs.
9. The Alternate Toe Tap Leg Lift mainly trains your Hip Flexors (iliopsoas), Abdominals (rectus abdominis), Quadriceps (quadriceps femoris). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$, 'floor_core',
  $instr$[rule | engine=exercise_instruction_copy.dart | class=floor_core] NASM EPFT 6th ed. ch.9; McGill, Low Back Disorders 2nd ed. — trunk / core training$instr$, '2085-2026-05-18'
FROM public.exercise_library WHERE id = '652b1b3a-ac2e-4f25-85f0-f486fa912dc5'
  AND NOT EXISTS (SELECT 1 FROM public.exercise_instruction_backup
                  WHERE id = '652b1b3a-ac2e-4f25-85f0-f486fa912dc5');
UPDATE public.exercise_library SET instructions = $instr$1. Lie on your back with your lower back lightly pressed into the floor.
2. Brace your abs and lift your shoulders or legs only as far as the brace holds.
3. Move with control through the prescribed range — heel touch, toe tap, or leg movement.
4. Keep your lower back in contact with the floor for the whole set.
5. Lower under control; do not let the legs or shoulders crash down.
6. Breathing: Exhale as you contract the abs. Inhale as you return to the start. Breathe steadily — do not hold your breath.
7. Form check: If your lower back lifts off the floor, reduce the range.
8. Form check: Move from the abs — do not yank the neck or swing the legs.
9. The Alternate Toe Tap Leg Lift mainly trains your Hip Flexors (iliopsoas), Abdominals (rectus abdominis), Quadriceps (quadriceps femoris). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$ WHERE id = '652b1b3a-ac2e-4f25-85f0-f486fa912dc5';

INSERT INTO public.exercise_instruction_backup
  (id, source_table, old_instructions, new_instructions, movement_class,
   source_citation, rewrite_batch)
SELECT id, 'exercise_library', instructions, $instr$1. Lie on your back with your lower back lightly pressed into the floor.
2. Brace your abs and lift your shoulders or legs only as far as the brace holds.
3. Move with control through the prescribed range — heel touch, toe tap, or leg movement.
4. Keep your lower back in contact with the floor for the whole set.
5. Lower under control; do not let the legs or shoulders crash down.
6. Breathing: Exhale as you contract the abs. Inhale as you return to the start. Breathe steadily — do not hold your breath.
7. Form check: If your lower back lifts off the floor, reduce the range.
8. Form check: Move from the abs — do not yank the neck or swing the legs.
9. The Alternating Toe Tap mainly trains your Abdominals (rectus abdominis), Hip Flexors (iliopsoas), Quadriceps (quadriceps femoris). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$, 'floor_core',
  $instr$[rule | engine=exercise_instruction_copy.dart | class=floor_core] NASM EPFT 6th ed. ch.9; McGill, Low Back Disorders 2nd ed. — trunk / core training$instr$, '2085-2026-05-18'
FROM public.exercise_library WHERE id = 'd0b8723f-baff-446a-9336-d1e271c7b080'
  AND NOT EXISTS (SELECT 1 FROM public.exercise_instruction_backup
                  WHERE id = 'd0b8723f-baff-446a-9336-d1e271c7b080');
UPDATE public.exercise_library SET instructions = $instr$1. Lie on your back with your lower back lightly pressed into the floor.
2. Brace your abs and lift your shoulders or legs only as far as the brace holds.
3. Move with control through the prescribed range — heel touch, toe tap, or leg movement.
4. Keep your lower back in contact with the floor for the whole set.
5. Lower under control; do not let the legs or shoulders crash down.
6. Breathing: Exhale as you contract the abs. Inhale as you return to the start. Breathe steadily — do not hold your breath.
7. Form check: If your lower back lifts off the floor, reduce the range.
8. Form check: Move from the abs — do not yank the neck or swing the legs.
9. The Alternating Toe Tap mainly trains your Abdominals (rectus abdominis), Hip Flexors (iliopsoas), Quadriceps (quadriceps femoris). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$ WHERE id = 'd0b8723f-baff-446a-9336-d1e271c7b080';

INSERT INTO public.exercise_instruction_backup
  (id, source_table, old_instructions, new_instructions, movement_class,
   source_citation, rewrite_batch)
SELECT id, 'exercise_library', instructions, $instr$1. Set the pad at your hip crease so you can hinge freely, ankles secured under the rollers.
2. Cross your arms on your chest (or place fingertips at your temples) and brace your core.
3. Hinge DOWN at the hips with a flat, neutral spine — this is a hip hinge, not a back bend.
4. Lower until you feel a stretch in the hamstrings, with the torso pointing toward the floor.
5. Raise back up by squeezing the glutes; stop in a straight line, do not arch past it.
6. Breathing: Inhale as you lower under control. Exhale as you raise back up. Keep the core braced throughout — do not hold your breath.
7. Form check: Keep a neutral spine the whole rep — never round or yank the lower back.
8. Form check: Finish in a straight line; hyperextending hard at the top stresses the spine.
9. The Back Extension Machine mainly trains your Lower Back (erector spinae), Glutes (gluteus maximus, gluteus mideus). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$, 'back_extension',
  $instr$[rule | engine=exercise_instruction_copy.dart | class=back_extension] NSCA ESSC 4th ed. ch.13; McGill, Low Back Disorders 2nd ed. — neutral-spine hip hinge$instr$, '2085-2026-05-18'
FROM public.exercise_library WHERE id = 'd0971e98-e875-4eb2-abdd-4d6db72064df'
  AND NOT EXISTS (SELECT 1 FROM public.exercise_instruction_backup
                  WHERE id = 'd0971e98-e875-4eb2-abdd-4d6db72064df');
UPDATE public.exercise_library SET instructions = $instr$1. Set the pad at your hip crease so you can hinge freely, ankles secured under the rollers.
2. Cross your arms on your chest (or place fingertips at your temples) and brace your core.
3. Hinge DOWN at the hips with a flat, neutral spine — this is a hip hinge, not a back bend.
4. Lower until you feel a stretch in the hamstrings, with the torso pointing toward the floor.
5. Raise back up by squeezing the glutes; stop in a straight line, do not arch past it.
6. Breathing: Inhale as you lower under control. Exhale as you raise back up. Keep the core braced throughout — do not hold your breath.
7. Form check: Keep a neutral spine the whole rep — never round or yank the lower back.
8. Form check: Finish in a straight line; hyperextending hard at the top stresses the spine.
9. The Back Extension Machine mainly trains your Lower Back (erector spinae), Glutes (gluteus maximus, gluteus mideus). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$ WHERE id = 'd0971e98-e875-4eb2-abdd-4d6db72064df';

INSERT INTO public.exercise_instruction_backup
  (id, source_table, old_instructions, new_instructions, movement_class,
   source_citation, rewrite_batch)
SELECT id, 'exercise_library', instructions, $instr$1. Stand tall holding the weight at your sides (or in front), arms straight and relaxed.
2. Brace your core; your arms are just hooks, they do not lift.
3. Lift your shoulders straight UP toward your ears.
4. Pause briefly at the top and squeeze the upper traps.
5. Lower under control to a full stretch.
6. Breathing: Inhale before the shrug. Exhale as you lift the shoulders up. Inhale on the way down.
7. Form check: Move straight up and down — rolling the shoulders adds no benefit and stresses the joint.
8. Form check: Keep the chin level; do not crane the neck forward.
9. The Barbell Jump Shrug mainly trains your Quadriceps (Quadriceps Femoris), Glutes (Gluteus Maximus). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$, 'shrug',
  $instr$[rule | engine=exercise_instruction_copy.dart | class=shrug] NASM EPFT 6th ed. ch.13 — single-joint resistance technique$instr$, '2085-2026-05-18'
FROM public.exercise_library WHERE id = 'e7d3a706-e53e-485c-aa59-d6fe40562133'
  AND NOT EXISTS (SELECT 1 FROM public.exercise_instruction_backup
                  WHERE id = 'e7d3a706-e53e-485c-aa59-d6fe40562133');
UPDATE public.exercise_library SET instructions = $instr$1. Stand tall holding the weight at your sides (or in front), arms straight and relaxed.
2. Brace your core; your arms are just hooks, they do not lift.
3. Lift your shoulders straight UP toward your ears.
4. Pause briefly at the top and squeeze the upper traps.
5. Lower under control to a full stretch.
6. Breathing: Inhale before the shrug. Exhale as you lift the shoulders up. Inhale on the way down.
7. Form check: Move straight up and down — rolling the shoulders adds no benefit and stresses the joint.
8. Form check: Keep the chin level; do not crane the neck forward.
9. The Barbell Jump Shrug mainly trains your Quadriceps (Quadriceps Femoris), Glutes (Gluteus Maximus). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$ WHERE id = 'e7d3a706-e53e-485c-aa59-d6fe40562133';

INSERT INTO public.exercise_instruction_backup
  (id, source_table, old_instructions, new_instructions, movement_class,
   source_citation, rewrite_batch)
SELECT id, 'exercise_library', instructions, $instr$1. Hinge forward at the hips with a flat back, or set up chest-supported on an incline bench.
2. Let the weights hang straight down with a soft, fixed bend in the elbows.
3. Brace your core and keep your head in line with your spine.
4. Raise the weights out to the sides, squeezing the shoulder blades lightly together.
5. Lower under control, keeping tension on the rear delts throughout.
6. Breathing: Inhale before the rep. Exhale as you raise the weights out. Inhale on the controlled descent.
7. Form check: Lead with the elbows and stop at shoulder height.
8. Form check: Keep the movement at the shoulder — do not bend the elbows and turn it into a row.
9. The Barbell Rear Delt Raise mainly trains your Deltoids (Posterior Deltoids). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$, 'rear_delt_fly',
  $instr$[rule | engine=exercise_instruction_copy.dart | class=rear_delt_fly] NASM EPFT 6th ed. ch.13 — single-joint resistance technique$instr$, '2085-2026-05-18'
FROM public.exercise_library WHERE id = 'f7e35ee7-9e69-4f8f-b974-de7bfff30c37'
  AND NOT EXISTS (SELECT 1 FROM public.exercise_instruction_backup
                  WHERE id = 'f7e35ee7-9e69-4f8f-b974-de7bfff30c37');
UPDATE public.exercise_library SET instructions = $instr$1. Hinge forward at the hips with a flat back, or set up chest-supported on an incline bench.
2. Let the weights hang straight down with a soft, fixed bend in the elbows.
3. Brace your core and keep your head in line with your spine.
4. Raise the weights out to the sides, squeezing the shoulder blades lightly together.
5. Lower under control, keeping tension on the rear delts throughout.
6. Breathing: Inhale before the rep. Exhale as you raise the weights out. Inhale on the controlled descent.
7. Form check: Lead with the elbows and stop at shoulder height.
8. Form check: Keep the movement at the shoulder — do not bend the elbows and turn it into a row.
9. The Barbell Rear Delt Raise mainly trains your Deltoids (Posterior Deltoids). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$ WHERE id = 'f7e35ee7-9e69-4f8f-b974-de7bfff30c37';

INSERT INTO public.exercise_instruction_backup
  (id, source_table, old_instructions, new_instructions, movement_class,
   source_citation, rewrite_batch)
SELECT id, 'exercise_library', instructions, $instr$1. Hinge forward at the hips with a flat back, or set up chest-supported on an incline bench.
2. Let the weights hang straight down with a soft, fixed bend in the elbows.
3. Brace your core and keep your head in line with your spine.
4. Raise the weights out to the sides, squeezing the shoulder blades lightly together.
5. Lower under control, keeping tension on the rear delts throughout.
6. Breathing: Inhale before the rep. Exhale as you raise the weights out. Inhale on the controlled descent.
7. Form check: Lead with the elbows and stop at shoulder height.
8. Form check: Keep the movement at the shoulder — do not bend the elbows and turn it into a row.
9. The Bodyweight Bent-Over Rear Delt Fly mainly trains your Deltoids (Posterior Deltoids). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$, 'rear_delt_fly',
  $instr$[rule | engine=exercise_instruction_copy.dart | class=rear_delt_fly] NASM EPFT 6th ed. ch.13 — single-joint resistance technique$instr$, '2085-2026-05-18'
FROM public.exercise_library WHERE id = 'bfb14f19-72c4-4532-9bbc-c8e8c0926c9a'
  AND NOT EXISTS (SELECT 1 FROM public.exercise_instruction_backup
                  WHERE id = 'bfb14f19-72c4-4532-9bbc-c8e8c0926c9a');
UPDATE public.exercise_library SET instructions = $instr$1. Hinge forward at the hips with a flat back, or set up chest-supported on an incline bench.
2. Let the weights hang straight down with a soft, fixed bend in the elbows.
3. Brace your core and keep your head in line with your spine.
4. Raise the weights out to the sides, squeezing the shoulder blades lightly together.
5. Lower under control, keeping tension on the rear delts throughout.
6. Breathing: Inhale before the rep. Exhale as you raise the weights out. Inhale on the controlled descent.
7. Form check: Lead with the elbows and stop at shoulder height.
8. Form check: Keep the movement at the shoulder — do not bend the elbows and turn it into a row.
9. The Bodyweight Bent-Over Rear Delt Fly mainly trains your Deltoids (Posterior Deltoids). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$ WHERE id = 'bfb14f19-72c4-4532-9bbc-c8e8c0926c9a';

INSERT INTO public.exercise_instruction_backup
  (id, source_table, old_instructions, new_instructions, movement_class,
   source_citation, rewrite_batch)
SELECT id, 'exercise_library', instructions, $instr$1. Set up on the machine (or lie prone) with the pad just above your heels.
2. Press your hips down into the bench and keep your torso still.
3. Curl your heels toward your glutes through the full available range.
4. Pause and squeeze the hamstrings at the top.
5. Lower under control — never let the weight drop.
6. Breathing: Inhale at the start with the legs extended. Exhale as you curl the heels in. Inhale on the controlled return.
7. Form check: Keep the hips pressed down — lifting them off the pad cheats the hamstrings.
8. Form check: Control the negative; do not fully relax at the bottom.
9. The Bodyweight Lying Leg Curl mainly trains your Hamstrings (Biceps Femoris, Semitendinosus, Semimembranosus). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$, 'leg_curl',
  $instr$[rule | engine=exercise_instruction_copy.dart | class=leg_curl] NASM EPFT 6th ed. ch.13 — single-joint resistance technique$instr$, '2085-2026-05-18'
FROM public.exercise_library WHERE id = '3b2a8bdb-1976-41db-ac97-783ee5578002'
  AND NOT EXISTS (SELECT 1 FROM public.exercise_instruction_backup
                  WHERE id = '3b2a8bdb-1976-41db-ac97-783ee5578002');
UPDATE public.exercise_library SET instructions = $instr$1. Set up on the machine (or lie prone) with the pad just above your heels.
2. Press your hips down into the bench and keep your torso still.
3. Curl your heels toward your glutes through the full available range.
4. Pause and squeeze the hamstrings at the top.
5. Lower under control — never let the weight drop.
6. Breathing: Inhale at the start with the legs extended. Exhale as you curl the heels in. Inhale on the controlled return.
7. Form check: Keep the hips pressed down — lifting them off the pad cheats the hamstrings.
8. Form check: Control the negative; do not fully relax at the bottom.
9. The Bodyweight Lying Leg Curl mainly trains your Hamstrings (Biceps Femoris, Semitendinosus, Semimembranosus). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$ WHERE id = '3b2a8bdb-1976-41db-ac97-783ee5578002';

INSERT INTO public.exercise_instruction_backup
  (id, source_table, old_instructions, new_instructions, movement_class,
   source_citation, rewrite_batch)
SELECT id, 'exercise_library', instructions, $instr$1. Stand tall holding the weight at your sides (or in front), arms straight and relaxed.
2. Brace your core; your arms are just hooks, they do not lift.
3. Lift your shoulders straight UP toward your ears.
4. Pause briefly at the top and squeeze the upper traps.
5. Lower under control to a full stretch.
6. Breathing: Inhale before the shrug. Exhale as you lift the shoulders up. Inhale on the way down.
7. Form check: Move straight up and down — rolling the shoulders adds no benefit and stresses the joint.
8. Form check: Keep the chin level; do not crane the neck forward.
9. The Bodyweight Standing Shrug mainly trains your Upper Back (Trapezius), Shoulders (Deltoids). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$, 'shrug',
  $instr$[rule | engine=exercise_instruction_copy.dart | class=shrug] NASM EPFT 6th ed. ch.13 — single-joint resistance technique$instr$, '2085-2026-05-18'
FROM public.exercise_library WHERE id = 'bd6a566e-457d-4821-a6bb-012cc911b7dd'
  AND NOT EXISTS (SELECT 1 FROM public.exercise_instruction_backup
                  WHERE id = 'bd6a566e-457d-4821-a6bb-012cc911b7dd');
UPDATE public.exercise_library SET instructions = $instr$1. Stand tall holding the weight at your sides (or in front), arms straight and relaxed.
2. Brace your core; your arms are just hooks, they do not lift.
3. Lift your shoulders straight UP toward your ears.
4. Pause briefly at the top and squeeze the upper traps.
5. Lower under control to a full stretch.
6. Breathing: Inhale before the shrug. Exhale as you lift the shoulders up. Inhale on the way down.
7. Form check: Move straight up and down — rolling the shoulders adds no benefit and stresses the joint.
8. Form check: Keep the chin level; do not crane the neck forward.
9. The Bodyweight Standing Shrug mainly trains your Upper Back (Trapezius), Shoulders (Deltoids). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$ WHERE id = 'bd6a566e-457d-4821-a6bb-012cc911b7dd';

INSERT INTO public.exercise_instruction_backup
  (id, source_table, old_instructions, new_instructions, movement_class,
   source_citation, rewrite_batch)
SELECT id, 'exercise_library', instructions, $instr$1. Set a cable high (or hold the weight) and stand side-on with feet shoulder-width.
2. Brace your core and grip the handle or weight with both hands.
3. Pull and rotate the weight down and across your body toward the opposite hip.
4. Let your hips and trunk rotate together while the arms stay fairly straight.
5. Return under control along the same path; finish all reps, then switch sides.
6. Breathing: Inhale before the chop. Exhale as you rotate and pull across. Inhale on the controlled return.
7. Form check: Rotate through the trunk and hips, not just the arms.
8. Form check: Keep the spine tall — do not crunch or round as you rotate.
9. The Diagonal Chop Cable mainly trains your Abdominals (Obliques). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$, 'woodchop',
  $instr$[rule | engine=exercise_instruction_copy.dart | class=woodchop] NASM EPFT 6th ed. ch.9; McGill, Low Back Disorders 2nd ed. — trunk / core training$instr$, '2085-2026-05-18'
FROM public.exercise_library WHERE id = '17e9f89e-7771-4432-892d-57805de1bb68'
  AND NOT EXISTS (SELECT 1 FROM public.exercise_instruction_backup
                  WHERE id = '17e9f89e-7771-4432-892d-57805de1bb68');
UPDATE public.exercise_library SET instructions = $instr$1. Set a cable high (or hold the weight) and stand side-on with feet shoulder-width.
2. Brace your core and grip the handle or weight with both hands.
3. Pull and rotate the weight down and across your body toward the opposite hip.
4. Let your hips and trunk rotate together while the arms stay fairly straight.
5. Return under control along the same path; finish all reps, then switch sides.
6. Breathing: Inhale before the chop. Exhale as you rotate and pull across. Inhale on the controlled return.
7. Form check: Rotate through the trunk and hips, not just the arms.
8. Form check: Keep the spine tall — do not crunch or round as you rotate.
9. The Diagonal Chop Cable mainly trains your Abdominals (Obliques). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$ WHERE id = '17e9f89e-7771-4432-892d-57805de1bb68';

INSERT INTO public.exercise_instruction_backup
  (id, source_table, old_instructions, new_instructions, movement_class,
   source_citation, rewrite_batch)
SELECT id, 'exercise_library', instructions, $instr$1. Hinge forward at the hips with a flat back, or set up chest-supported on an incline bench.
2. Let the weights hang straight down with a soft, fixed bend in the elbows.
3. Brace your core and keep your head in line with your spine.
4. Raise the weights out to the sides, squeezing the shoulder blades lightly together.
5. Lower under control, keeping tension on the rear delts throughout.
6. Breathing: Inhale before the rep. Exhale as you raise the weights out. Inhale on the controlled descent.
7. Form check: Lead with the elbows and stop at shoulder height.
8. Form check: Keep the movement at the shoulder — do not bend the elbows and turn it into a row.
9. The Dumbbell Chest Supported Y Raise mainly trains your Shoulders (Posterior Deltoids, Lower Trapezius). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$, 'rear_delt_fly',
  $instr$[rule | engine=exercise_instruction_copy.dart | class=rear_delt_fly] NASM EPFT 6th ed. ch.13 — single-joint resistance technique$instr$, '2085-2026-05-18'
FROM public.exercise_library WHERE id = '5a301ee7-3f01-4d9d-8f36-041d75713da5'
  AND NOT EXISTS (SELECT 1 FROM public.exercise_instruction_backup
                  WHERE id = '5a301ee7-3f01-4d9d-8f36-041d75713da5');
UPDATE public.exercise_library SET instructions = $instr$1. Hinge forward at the hips with a flat back, or set up chest-supported on an incline bench.
2. Let the weights hang straight down with a soft, fixed bend in the elbows.
3. Brace your core and keep your head in line with your spine.
4. Raise the weights out to the sides, squeezing the shoulder blades lightly together.
5. Lower under control, keeping tension on the rear delts throughout.
6. Breathing: Inhale before the rep. Exhale as you raise the weights out. Inhale on the controlled descent.
7. Form check: Lead with the elbows and stop at shoulder height.
8. Form check: Keep the movement at the shoulder — do not bend the elbows and turn it into a row.
9. The Dumbbell Chest Supported Y Raise mainly trains your Shoulders (Posterior Deltoids, Lower Trapezius). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$ WHERE id = '5a301ee7-3f01-4d9d-8f36-041d75713da5';

INSERT INTO public.exercise_instruction_backup
  (id, source_table, old_instructions, new_instructions, movement_class,
   source_citation, rewrite_batch)
SELECT id, 'exercise_library', instructions, $instr$1. Set a cable high (or hold the weight) and stand side-on with feet shoulder-width.
2. Brace your core and grip the handle or weight with both hands.
3. Pull and rotate the weight down and across your body toward the opposite hip.
4. Let your hips and trunk rotate together while the arms stay fairly straight.
5. Return under control along the same path; finish all reps, then switch sides.
6. Breathing: Inhale before the chop. Exhale as you rotate and pull across. Inhale on the controlled return.
7. Form check: Rotate through the trunk and hips, not just the arms.
8. Form check: Keep the spine tall — do not crunch or round as you rotate.
9. The Dumbbell Half-Kneeling Wood Chopper mainly trains your Obliques (External and Internal Obliques). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$, 'woodchop',
  $instr$[rule | engine=exercise_instruction_copy.dart | class=woodchop] NASM EPFT 6th ed. ch.9; McGill, Low Back Disorders 2nd ed. — trunk / core training$instr$, '2085-2026-05-18'
FROM public.exercise_library WHERE id = 'f3c9c27e-7a0a-46dc-9793-0aa620557ba7'
  AND NOT EXISTS (SELECT 1 FROM public.exercise_instruction_backup
                  WHERE id = 'f3c9c27e-7a0a-46dc-9793-0aa620557ba7');
UPDATE public.exercise_library SET instructions = $instr$1. Set a cable high (or hold the weight) and stand side-on with feet shoulder-width.
2. Brace your core and grip the handle or weight with both hands.
3. Pull and rotate the weight down and across your body toward the opposite hip.
4. Let your hips and trunk rotate together while the arms stay fairly straight.
5. Return under control along the same path; finish all reps, then switch sides.
6. Breathing: Inhale before the chop. Exhale as you rotate and pull across. Inhale on the controlled return.
7. Form check: Rotate through the trunk and hips, not just the arms.
8. Form check: Keep the spine tall — do not crunch or round as you rotate.
9. The Dumbbell Half-Kneeling Wood Chopper mainly trains your Obliques (External and Internal Obliques). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$ WHERE id = 'f3c9c27e-7a0a-46dc-9793-0aa620557ba7';

INSERT INTO public.exercise_instruction_backup
  (id, source_table, old_instructions, new_instructions, movement_class,
   source_citation, rewrite_batch)
SELECT id, 'exercise_library', instructions, $instr$1. Set up with the weight at mid-chest, feet planted and core braced.
2. Position your elbows tucked at roughly 45 degrees from your torso.
3. Set your shoulder blades down and back against the bench or floor.
4. Press the weight away from your chest until your arms are nearly straight.
5. Lower under control back to the chest, stopping just short of a hard lockout.
6. Breathing: Inhale as the weight lowers and brace. Exhale as you press the weight up. Reset the breath between reps.
7. Form check: Keep the shoulder blades set — do not let them round forward.
8. Form check: Press in a smooth line; do not let the elbows flare wide.
9. The Dumbbell Lying On Floor Chest Press mainly trains your Chest (Pectoralis Major). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$, 'chest_press',
  $instr$[rule | engine=exercise_instruction_copy.dart | class=chest_press] NSCA ESSC 4th ed. ch.13; NASM EPFT 6th ed. ch.13 — horizontal pressing$instr$, '2085-2026-05-18'
FROM public.exercise_library WHERE id = 'c0918e72-e518-4f5c-850c-6df98a89459e'
  AND NOT EXISTS (SELECT 1 FROM public.exercise_instruction_backup
                  WHERE id = 'c0918e72-e518-4f5c-850c-6df98a89459e');
UPDATE public.exercise_library SET instructions = $instr$1. Set up with the weight at mid-chest, feet planted and core braced.
2. Position your elbows tucked at roughly 45 degrees from your torso.
3. Set your shoulder blades down and back against the bench or floor.
4. Press the weight away from your chest until your arms are nearly straight.
5. Lower under control back to the chest, stopping just short of a hard lockout.
6. Breathing: Inhale as the weight lowers and brace. Exhale as you press the weight up. Reset the breath between reps.
7. Form check: Keep the shoulder blades set — do not let them round forward.
8. Form check: Press in a smooth line; do not let the elbows flare wide.
9. The Dumbbell Lying On Floor Chest Press mainly trains your Chest (Pectoralis Major). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$ WHERE id = 'c0918e72-e518-4f5c-850c-6df98a89459e';

INSERT INTO public.exercise_instruction_backup
  (id, source_table, old_instructions, new_instructions, movement_class,
   source_citation, rewrite_batch)
SELECT id, 'exercise_library', instructions, $instr$1. Stand tall with a slight knee bend, a weight in each hand at your sides.
2. Keep a soft, fixed bend in the elbows of about 10 to 15 degrees.
3. Brace your core and keep your torso still — do not lean back.
4. Raise the weights out to the sides until your arms reach shoulder height.
5. Lower under control to the start, resisting the weight the whole way down.
6. Breathing: Inhale before the raise. Exhale as you lift the weights to shoulder height. Inhale on the controlled descent.
7. Form check: Lead with the elbows, not the hands, and keep the wrists neutral.
8. Form check: Stop at shoulder height — going higher shifts work off the side delts.
9. The Dumbbell Seated Lateral Raise mainly trains your Shoulders (Lateral Deltoids). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$, 'lateral_raise',
  $instr$[rule | engine=exercise_instruction_copy.dart | class=lateral_raise] NASM EPFT 6th ed. ch.13 — single-joint resistance technique$instr$, '2085-2026-05-18'
FROM public.exercise_library WHERE id = '320055ab-7b76-4519-956d-d224d718eb17'
  AND NOT EXISTS (SELECT 1 FROM public.exercise_instruction_backup
                  WHERE id = '320055ab-7b76-4519-956d-d224d718eb17');
UPDATE public.exercise_library SET instructions = $instr$1. Stand tall with a slight knee bend, a weight in each hand at your sides.
2. Keep a soft, fixed bend in the elbows of about 10 to 15 degrees.
3. Brace your core and keep your torso still — do not lean back.
4. Raise the weights out to the sides until your arms reach shoulder height.
5. Lower under control to the start, resisting the weight the whole way down.
6. Breathing: Inhale before the raise. Exhale as you lift the weights to shoulder height. Inhale on the controlled descent.
7. Form check: Lead with the elbows, not the hands, and keep the wrists neutral.
8. Form check: Stop at shoulder height — going higher shifts work off the side delts.
9. The Dumbbell Seated Lateral Raise mainly trains your Shoulders (Lateral Deltoids). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$ WHERE id = '320055ab-7b76-4519-956d-d224d718eb17';

INSERT INTO public.exercise_instruction_backup
  (id, source_table, old_instructions, new_instructions, movement_class,
   source_citation, rewrite_batch)
SELECT id, 'exercise_library', instructions, $instr$1. Stand tall, weights resting against the front of your thighs, palms facing you.
2. Keep a slight fixed bend in the elbows and brace your core.
3. Raise the weight straight in front of you up to shoulder height.
4. Pause briefly at the top with the arm parallel to the floor.
5. Lower slowly under control back to the thighs.
6. Breathing: Inhale before the raise. Exhale as you lift the weight. Inhale on the controlled descent.
7. Form check: Do not swing or use the torso to heave the weight up.
8. Form check: Stop at shoulder height — there is no need to go overhead.
9. The Dumbbell Single-Arm Front Raise mainly trains your Shoulders (Anterior Deltoids). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$, 'front_raise',
  $instr$[rule | engine=exercise_instruction_copy.dart | class=front_raise] NASM EPFT 6th ed. ch.13 — single-joint resistance technique$instr$, '2085-2026-05-18'
FROM public.exercise_library WHERE id = '4ce306db-9214-4e7b-96e8-0b776bc3887a'
  AND NOT EXISTS (SELECT 1 FROM public.exercise_instruction_backup
                  WHERE id = '4ce306db-9214-4e7b-96e8-0b776bc3887a');
UPDATE public.exercise_library SET instructions = $instr$1. Stand tall, weights resting against the front of your thighs, palms facing you.
2. Keep a slight fixed bend in the elbows and brace your core.
3. Raise the weight straight in front of you up to shoulder height.
4. Pause briefly at the top with the arm parallel to the floor.
5. Lower slowly under control back to the thighs.
6. Breathing: Inhale before the raise. Exhale as you lift the weight. Inhale on the controlled descent.
7. Form check: Do not swing or use the torso to heave the weight up.
8. Form check: Stop at shoulder height — there is no need to go overhead.
9. The Dumbbell Single-Arm Front Raise mainly trains your Shoulders (Anterior Deltoids). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$ WHERE id = '4ce306db-9214-4e7b-96e8-0b776bc3887a';

INSERT INTO public.exercise_instruction_backup
  (id, source_table, old_instructions, new_instructions, movement_class,
   source_citation, rewrite_batch)
SELECT id, 'exercise_library', instructions, $instr$1. Stand tall holding the weight in front of your thighs with a shoulder-width grip.
2. Brace your core and keep your chest tall.
3. Pull the weight straight up along your body, leading with the elbows.
4. Stop when your elbows reach shoulder height — no higher.
5. Lower under control back to the start.
6. Breathing: Inhale before the pull. Exhale as you pull the weight up. Inhale as you lower.
7. Form check: Do not pull the elbows above shoulder height — that can pinch the shoulder.
8. Form check: Widen your grip if you feel any shoulder discomfort.
9. The Dumbbell Single-Arm Upright Row mainly trains your Shoulders (Lateral Deltoids), Upper Back (Trapezius). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$, 'upright_row',
  $instr$[rule | engine=exercise_instruction_copy.dart | class=upright_row] NASM EPFT 6th ed. ch.13 — single-joint resistance technique$instr$, '2085-2026-05-18'
FROM public.exercise_library WHERE id = '4807b5d2-5918-459b-8f4a-fc1646904ee8'
  AND NOT EXISTS (SELECT 1 FROM public.exercise_instruction_backup
                  WHERE id = '4807b5d2-5918-459b-8f4a-fc1646904ee8');
UPDATE public.exercise_library SET instructions = $instr$1. Stand tall holding the weight in front of your thighs with a shoulder-width grip.
2. Brace your core and keep your chest tall.
3. Pull the weight straight up along your body, leading with the elbows.
4. Stop when your elbows reach shoulder height — no higher.
5. Lower under control back to the start.
6. Breathing: Inhale before the pull. Exhale as you pull the weight up. Inhale as you lower.
7. Form check: Do not pull the elbows above shoulder height — that can pinch the shoulder.
8. Form check: Widen your grip if you feel any shoulder discomfort.
9. The Dumbbell Single-Arm Upright Row mainly trains your Shoulders (Lateral Deltoids), Upper Back (Trapezius). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$ WHERE id = '4807b5d2-5918-459b-8f4a-fc1646904ee8';

INSERT INTO public.exercise_instruction_backup
  (id, source_table, old_instructions, new_instructions, movement_class,
   source_citation, rewrite_batch)
SELECT id, 'exercise_library', instructions, $instr$1. Rest your forearms on your thighs or a bench with the wrists just past the edge, palms up.
2. Let the weight roll toward your fingertips for a full stretch.
3. Curl the weight up by flexing the wrists only.
4. Squeeze the forearms at the top of the range.
5. Lower slowly back to a full stretch.
6. Breathing: Inhale before the curl. Exhale as you curl the weight up. Inhale as you lower.
7. Form check: Move only at the wrist — the forearms stay planted.
8. Form check: Use a light load and a full range; forearms respond to control, not heavy weight.
9. The Dumbbell Standing Wrist Curl mainly trains your Forearms (Flexor Carpi Radialis, Flexor Carpi Ulnaris). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$, 'wrist_curl',
  $instr$[rule | engine=exercise_instruction_copy.dart | class=wrist_curl] NASM EPFT 6th ed. ch.13 — single-joint resistance technique$instr$, '2085-2026-05-18'
FROM public.exercise_library WHERE id = '1fe8c2fb-e5dc-4395-abc3-f3fa8bd7f967'
  AND NOT EXISTS (SELECT 1 FROM public.exercise_instruction_backup
                  WHERE id = '1fe8c2fb-e5dc-4395-abc3-f3fa8bd7f967');
UPDATE public.exercise_library SET instructions = $instr$1. Rest your forearms on your thighs or a bench with the wrists just past the edge, palms up.
2. Let the weight roll toward your fingertips for a full stretch.
3. Curl the weight up by flexing the wrists only.
4. Squeeze the forearms at the top of the range.
5. Lower slowly back to a full stretch.
6. Breathing: Inhale before the curl. Exhale as you curl the weight up. Inhale as you lower.
7. Form check: Move only at the wrist — the forearms stay planted.
8. Form check: Use a light load and a full range; forearms respond to control, not heavy weight.
9. The Dumbbell Standing Wrist Curl mainly trains your Forearms (Flexor Carpi Radialis, Flexor Carpi Ulnaris). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$ WHERE id = '1fe8c2fb-e5dc-4395-abc3-f3fa8bd7f967';

INSERT INTO public.exercise_instruction_backup
  (id, source_table, old_instructions, new_instructions, movement_class,
   source_citation, rewrite_batch)
SELECT id, 'exercise_library', instructions, $instr$1. Set up with the weight at mid-chest, feet planted and core braced.
2. Position your elbows tucked at roughly 45 degrees from your torso.
3. Set your shoulder blades down and back against the bench or floor.
4. Press the weight away from your chest until your arms are nearly straight.
5. Lower under control back to the chest, stopping just short of a hard lockout.
6. Breathing: Inhale as the weight lowers and brace. Exhale as you press the weight up. Reset the breath between reps.
7. Form check: Keep the shoulder blades set — do not let them round forward.
8. Form check: Press in a smooth line; do not let the elbows flare wide.
9. The Hold The World Med Ball Chest Press mainly trains your Chest (Pectoralis Major). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$, 'chest_press',
  $instr$[rule | engine=exercise_instruction_copy.dart | class=chest_press] NSCA ESSC 4th ed. ch.13; NASM EPFT 6th ed. ch.13 — horizontal pressing$instr$, '2085-2026-05-18'
FROM public.exercise_library WHERE id = 'e9e2808c-28af-4b40-beeb-f9a7d4f5bac5'
  AND NOT EXISTS (SELECT 1 FROM public.exercise_instruction_backup
                  WHERE id = 'e9e2808c-28af-4b40-beeb-f9a7d4f5bac5');
UPDATE public.exercise_library SET instructions = $instr$1. Set up with the weight at mid-chest, feet planted and core braced.
2. Position your elbows tucked at roughly 45 degrees from your torso.
3. Set your shoulder blades down and back against the bench or floor.
4. Press the weight away from your chest until your arms are nearly straight.
5. Lower under control back to the chest, stopping just short of a hard lockout.
6. Breathing: Inhale as the weight lowers and brace. Exhale as you press the weight up. Reset the breath between reps.
7. Form check: Keep the shoulder blades set — do not let them round forward.
8. Form check: Press in a smooth line; do not let the elbows flare wide.
9. The Hold The World Med Ball Chest Press mainly trains your Chest (Pectoralis Major). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$ WHERE id = 'e9e2808c-28af-4b40-beeb-f9a7d4f5bac5';

INSERT INTO public.exercise_instruction_backup
  (id, source_table, old_instructions, new_instructions, movement_class,
   source_citation, rewrite_batch)
SELECT id, 'exercise_library', instructions, $instr$1. Stand tall, weights resting against the front of your thighs, palms facing you.
2. Keep a slight fixed bend in the elbows and brace your core.
3. Raise the weight straight in front of you up to shoulder height.
4. Pause briefly at the top with the arm parallel to the floor.
5. Lower slowly under control back to the thighs.
6. Breathing: Inhale before the raise. Exhale as you lift the weight. Inhale on the controlled descent.
7. Form check: Do not swing or use the torso to heave the weight up.
8. Form check: Stop at shoulder height — there is no need to go overhead.
9. The Kettlebell Front Raise mainly trains your Shoulders (Anterior Deltoids). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$, 'front_raise',
  $instr$[rule | engine=exercise_instruction_copy.dart | class=front_raise] NASM EPFT 6th ed. ch.13 — single-joint resistance technique$instr$, '2085-2026-05-18'
FROM public.exercise_library WHERE id = '8ed12762-6557-4700-814b-ae38101a3fa4'
  AND NOT EXISTS (SELECT 1 FROM public.exercise_instruction_backup
                  WHERE id = '8ed12762-6557-4700-814b-ae38101a3fa4');
UPDATE public.exercise_library SET instructions = $instr$1. Stand tall, weights resting against the front of your thighs, palms facing you.
2. Keep a slight fixed bend in the elbows and brace your core.
3. Raise the weight straight in front of you up to shoulder height.
4. Pause briefly at the top with the arm parallel to the floor.
5. Lower slowly under control back to the thighs.
6. Breathing: Inhale before the raise. Exhale as you lift the weight. Inhale on the controlled descent.
7. Form check: Do not swing or use the torso to heave the weight up.
8. Form check: Stop at shoulder height — there is no need to go overhead.
9. The Kettlebell Front Raise mainly trains your Shoulders (Anterior Deltoids). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$ WHERE id = '8ed12762-6557-4700-814b-ae38101a3fa4';

INSERT INTO public.exercise_instruction_backup
  (id, source_table, old_instructions, new_instructions, movement_class,
   source_citation, rewrite_batch)
SELECT id, 'exercise_library', instructions, $instr$1. Set up with the weight at mid-chest, feet planted and core braced.
2. Position your elbows tucked at roughly 45 degrees from your torso.
3. Set your shoulder blades down and back against the bench or floor.
4. Press the weight away from your chest until your arms are nearly straight.
5. Lower under control back to the chest, stopping just short of a hard lockout.
6. Breathing: Inhale as the weight lowers and brace. Exhale as you press the weight up. Reset the breath between reps.
7. Form check: Keep the shoulder blades set — do not let them round forward.
8. Form check: Press in a smooth line; do not let the elbows flare wide.
9. The Landmine Chest Press mainly trains your Chest (Pectoralis Major). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$, 'chest_press',
  $instr$[rule | engine=exercise_instruction_copy.dart | class=chest_press] NSCA ESSC 4th ed. ch.13; NASM EPFT 6th ed. ch.13 — horizontal pressing$instr$, '2085-2026-05-18'
FROM public.exercise_library WHERE id = '457fe392-213b-4bd5-b221-c5f2f05ea498'
  AND NOT EXISTS (SELECT 1 FROM public.exercise_instruction_backup
                  WHERE id = '457fe392-213b-4bd5-b221-c5f2f05ea498');
UPDATE public.exercise_library SET instructions = $instr$1. Set up with the weight at mid-chest, feet planted and core braced.
2. Position your elbows tucked at roughly 45 degrees from your torso.
3. Set your shoulder blades down and back against the bench or floor.
4. Press the weight away from your chest until your arms are nearly straight.
5. Lower under control back to the chest, stopping just short of a hard lockout.
6. Breathing: Inhale as the weight lowers and brace. Exhale as you press the weight up. Reset the breath between reps.
7. Form check: Keep the shoulder blades set — do not let them round forward.
8. Form check: Press in a smooth line; do not let the elbows flare wide.
9. The Landmine Chest Press mainly trains your Chest (Pectoralis Major). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$ WHERE id = '457fe392-213b-4bd5-b221-c5f2f05ea498';

INSERT INTO public.exercise_instruction_backup
  (id, source_table, old_instructions, new_instructions, movement_class,
   source_citation, rewrite_batch)
SELECT id, 'exercise_library', instructions, $instr$1. Stand tall with a slight knee bend, a weight in each hand at your sides.
2. Keep a soft, fixed bend in the elbows of about 10 to 15 degrees.
3. Brace your core and keep your torso still — do not lean back.
4. Raise the weights out to the sides until your arms reach shoulder height.
5. Lower under control to the start, resisting the weight the whole way down.
6. Breathing: Inhale before the raise. Exhale as you lift the weights to shoulder height. Inhale on the controlled descent.
7. Form check: Lead with the elbows, not the hands, and keep the wrists neutral.
8. Form check: Stop at shoulder height — going higher shifts work off the side delts.
9. The Laying Lateral Raise mainly trains your Shoulders (Lateral Deltoids). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$, 'lateral_raise',
  $instr$[rule | engine=exercise_instruction_copy.dart | class=lateral_raise] NASM EPFT 6th ed. ch.13 — single-joint resistance technique$instr$, '2085-2026-05-18'
FROM public.exercise_library WHERE id = 'a06effca-ef7b-4c50-993f-795e0e8fb00a'
  AND NOT EXISTS (SELECT 1 FROM public.exercise_instruction_backup
                  WHERE id = 'a06effca-ef7b-4c50-993f-795e0e8fb00a');
UPDATE public.exercise_library SET instructions = $instr$1. Stand tall with a slight knee bend, a weight in each hand at your sides.
2. Keep a soft, fixed bend in the elbows of about 10 to 15 degrees.
3. Brace your core and keep your torso still — do not lean back.
4. Raise the weights out to the sides until your arms reach shoulder height.
5. Lower under control to the start, resisting the weight the whole way down.
6. Breathing: Inhale before the raise. Exhale as you lift the weights to shoulder height. Inhale on the controlled descent.
7. Form check: Lead with the elbows, not the hands, and keep the wrists neutral.
8. Form check: Stop at shoulder height — going higher shifts work off the side delts.
9. The Laying Lateral Raise mainly trains your Shoulders (Lateral Deltoids). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$ WHERE id = 'a06effca-ef7b-4c50-993f-795e0e8fb00a';

INSERT INTO public.exercise_instruction_backup
  (id, source_table, old_instructions, new_instructions, movement_class,
   source_citation, rewrite_batch)
SELECT id, 'exercise_library', instructions, $instr$1. Stand tall, weights resting against the front of your thighs, palms facing you.
2. Keep a slight fixed bend in the elbows and brace your core.
3. Raise the weight straight in front of you up to shoulder height.
4. Pause briefly at the top with the arm parallel to the floor.
5. Lower slowly under control back to the thighs.
6. Breathing: Inhale before the raise. Exhale as you lift the weight. Inhale on the controlled descent.
7. Form check: Do not swing or use the torso to heave the weight up.
8. Form check: Stop at shoulder height — there is no need to go overhead.
9. The Plate Full Front Raise mainly trains your Shoulders (Anterior Deltoids). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$, 'front_raise',
  $instr$[rule | engine=exercise_instruction_copy.dart | class=front_raise] NASM EPFT 6th ed. ch.13 — single-joint resistance technique$instr$, '2085-2026-05-18'
FROM public.exercise_library WHERE id = '725411da-e7f3-40f4-90ff-40adb3957211'
  AND NOT EXISTS (SELECT 1 FROM public.exercise_instruction_backup
                  WHERE id = '725411da-e7f3-40f4-90ff-40adb3957211');
UPDATE public.exercise_library SET instructions = $instr$1. Stand tall, weights resting against the front of your thighs, palms facing you.
2. Keep a slight fixed bend in the elbows and brace your core.
3. Raise the weight straight in front of you up to shoulder height.
4. Pause briefly at the top with the arm parallel to the floor.
5. Lower slowly under control back to the thighs.
6. Breathing: Inhale before the raise. Exhale as you lift the weight. Inhale on the controlled descent.
7. Form check: Do not swing or use the torso to heave the weight up.
8. Form check: Stop at shoulder height — there is no need to go overhead.
9. The Plate Full Front Raise mainly trains your Shoulders (Anterior Deltoids). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$ WHERE id = '725411da-e7f3-40f4-90ff-40adb3957211';

INSERT INTO public.exercise_instruction_backup
  (id, source_table, old_instructions, new_instructions, movement_class,
   source_citation, rewrite_batch)
SELECT id, 'exercise_library', instructions, $instr$1. Hinge forward at the hips with a flat back, or set up chest-supported on an incline bench.
2. Let the weights hang straight down with a soft, fixed bend in the elbows.
3. Brace your core and keep your head in line with your spine.
4. Raise the weights out to the sides, squeezing the shoulder blades lightly together.
5. Lower under control, keeping tension on the rear delts throughout.
6. Breathing: Inhale before the rep. Exhale as you raise the weights out. Inhale on the controlled descent.
7. Form check: Lead with the elbows and stop at shoulder height.
8. Form check: Keep the movement at the shoulder — do not bend the elbows and turn it into a row.
9. The Plate Internally Rotated Rear Delt Fly mainly trains your Shoulders (Posterior Deltoids). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$, 'rear_delt_fly',
  $instr$[rule | engine=exercise_instruction_copy.dart | class=rear_delt_fly] NASM EPFT 6th ed. ch.13 — single-joint resistance technique$instr$, '2085-2026-05-18'
FROM public.exercise_library WHERE id = 'be865292-30c5-4002-a82e-4258e4c1ef6e'
  AND NOT EXISTS (SELECT 1 FROM public.exercise_instruction_backup
                  WHERE id = 'be865292-30c5-4002-a82e-4258e4c1ef6e');
UPDATE public.exercise_library SET instructions = $instr$1. Hinge forward at the hips with a flat back, or set up chest-supported on an incline bench.
2. Let the weights hang straight down with a soft, fixed bend in the elbows.
3. Brace your core and keep your head in line with your spine.
4. Raise the weights out to the sides, squeezing the shoulder blades lightly together.
5. Lower under control, keeping tension on the rear delts throughout.
6. Breathing: Inhale before the rep. Exhale as you raise the weights out. Inhale on the controlled descent.
7. Form check: Lead with the elbows and stop at shoulder height.
8. Form check: Keep the movement at the shoulder — do not bend the elbows and turn it into a row.
9. The Plate Internally Rotated Rear Delt Fly mainly trains your Shoulders (Posterior Deltoids). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$ WHERE id = 'be865292-30c5-4002-a82e-4258e4c1ef6e';

INSERT INTO public.exercise_instruction_backup
  (id, source_table, old_instructions, new_instructions, movement_class,
   source_citation, rewrite_batch)
SELECT id, 'exercise_library', instructions, $instr$1. Stand tall with a slight knee bend, a weight in each hand at your sides.
2. Keep a soft, fixed bend in the elbows of about 10 to 15 degrees.
3. Brace your core and keep your torso still — do not lean back.
4. Raise the weights out to the sides until your arms reach shoulder height.
5. Lower under control to the start, resisting the weight the whole way down.
6. Breathing: Inhale before the raise. Exhale as you lift the weights to shoulder height. Inhale on the controlled descent.
7. Form check: Lead with the elbows, not the hands, and keep the wrists neutral.
8. Form check: Stop at shoulder height — going higher shifts work off the side delts.
9. The Plate Lateral Raise mainly trains your Shoulders (Lateral Deltoids). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$, 'lateral_raise',
  $instr$[rule | engine=exercise_instruction_copy.dart | class=lateral_raise] NASM EPFT 6th ed. ch.13 — single-joint resistance technique$instr$, '2085-2026-05-18'
FROM public.exercise_library WHERE id = '124efe8c-16fe-4873-8598-87fe550f3fff'
  AND NOT EXISTS (SELECT 1 FROM public.exercise_instruction_backup
                  WHERE id = '124efe8c-16fe-4873-8598-87fe550f3fff');
UPDATE public.exercise_library SET instructions = $instr$1. Stand tall with a slight knee bend, a weight in each hand at your sides.
2. Keep a soft, fixed bend in the elbows of about 10 to 15 degrees.
3. Brace your core and keep your torso still — do not lean back.
4. Raise the weights out to the sides until your arms reach shoulder height.
5. Lower under control to the start, resisting the weight the whole way down.
6. Breathing: Inhale before the raise. Exhale as you lift the weights to shoulder height. Inhale on the controlled descent.
7. Form check: Lead with the elbows, not the hands, and keep the wrists neutral.
8. Form check: Stop at shoulder height — going higher shifts work off the side delts.
9. The Plate Lateral Raise mainly trains your Shoulders (Lateral Deltoids). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$ WHERE id = '124efe8c-16fe-4873-8598-87fe550f3fff';

INSERT INTO public.exercise_instruction_backup
  (id, source_table, old_instructions, new_instructions, movement_class,
   source_citation, rewrite_batch)
SELECT id, 'exercise_library', instructions, $instr$1. Anchor a band at elbow height, or lie on your side holding a light dumbbell.
2. Pin the working elbow to your side, bent at 90 degrees.
3. Keeping the elbow glued in place, rotate your forearm outward.
4. Move only as far as the shoulder rotates freely — a small range is normal.
5. Return slowly under control to the start.
6. Breathing: Inhale before the rep. Exhale as you rotate outward. Inhale on the controlled return.
7. Form check: Keep the elbow pinned to your ribs the entire time.
8. Form check: Use very light resistance — this trains rotator-cuff control, it is not a strength lift.
9. The Resistance Band Standing External Rotation mainly trains your Rotator Cuff (Infraspinatus, Teres Minor). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$, 'external_rotation',
  $instr$[rule | engine=exercise_instruction_copy.dart | class=external_rotation] NASM EPFT 6th ed. ch.13 — single-joint resistance technique$instr$, '2085-2026-05-18'
FROM public.exercise_library WHERE id = '52a21139-88f4-43e5-b4c2-fdafbe79d896'
  AND NOT EXISTS (SELECT 1 FROM public.exercise_instruction_backup
                  WHERE id = '52a21139-88f4-43e5-b4c2-fdafbe79d896');
UPDATE public.exercise_library SET instructions = $instr$1. Anchor a band at elbow height, or lie on your side holding a light dumbbell.
2. Pin the working elbow to your side, bent at 90 degrees.
3. Keeping the elbow glued in place, rotate your forearm outward.
4. Move only as far as the shoulder rotates freely — a small range is normal.
5. Return slowly under control to the start.
6. Breathing: Inhale before the rep. Exhale as you rotate outward. Inhale on the controlled return.
7. Form check: Keep the elbow pinned to your ribs the entire time.
8. Form check: Use very light resistance — this trains rotator-cuff control, it is not a strength lift.
9. The Resistance Band Standing External Rotation mainly trains your Rotator Cuff (Infraspinatus, Teres Minor). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$ WHERE id = '52a21139-88f4-43e5-b4c2-fdafbe79d896';

INSERT INTO public.exercise_instruction_backup
  (id, source_table, old_instructions, new_instructions, movement_class,
   source_citation, rewrite_batch)
SELECT id, 'exercise_library', instructions, $instr$1. Set up with the weight at mid-chest, feet planted and core braced.
2. Position your elbows tucked at roughly 45 degrees from your torso.
3. Set your shoulder blades down and back against the bench or floor.
4. Press the weight away from your chest until your arms are nearly straight.
5. Lower under control back to the chest, stopping just short of a hard lockout.
6. Breathing: Inhale as the weight lowers and brace. Exhale as you press the weight up. Reset the breath between reps.
7. Form check: Keep the shoulder blades set — do not let them round forward.
8. Form check: Press in a smooth line; do not let the elbows flare wide.
9. The Svend Press Flat Bench mainly trains your Chest (Pectoralis Major). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$, 'chest_press',
  $instr$[rule | engine=exercise_instruction_copy.dart | class=chest_press] NSCA ESSC 4th ed. ch.13; NASM EPFT 6th ed. ch.13 — horizontal pressing$instr$, '2085-2026-05-18'
FROM public.exercise_library WHERE id = 'a8374aa2-4983-4020-bf3b-0985cc14e37c'
  AND NOT EXISTS (SELECT 1 FROM public.exercise_instruction_backup
                  WHERE id = 'a8374aa2-4983-4020-bf3b-0985cc14e37c');
UPDATE public.exercise_library SET instructions = $instr$1. Set up with the weight at mid-chest, feet planted and core braced.
2. Position your elbows tucked at roughly 45 degrees from your torso.
3. Set your shoulder blades down and back against the bench or floor.
4. Press the weight away from your chest until your arms are nearly straight.
5. Lower under control back to the chest, stopping just short of a hard lockout.
6. Breathing: Inhale as the weight lowers and brace. Exhale as you press the weight up. Reset the breath between reps.
7. Form check: Keep the shoulder blades set — do not let them round forward.
8. Form check: Press in a smooth line; do not let the elbows flare wide.
9. The Svend Press Flat Bench mainly trains your Chest (Pectoralis Major). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$ WHERE id = 'a8374aa2-4983-4020-bf3b-0985cc14e37c';

INSERT INTO public.exercise_instruction_backup
  (id, source_table, old_instructions, new_instructions, movement_class,
   source_citation, rewrite_batch)
SELECT id, 'exercise_library_manual', instructions, $instr$1. Stand tall with a slight knee bend, a weight in each hand at your sides.
2. Keep a soft, fixed bend in the elbows of about 10 to 15 degrees.
3. Brace your core and keep your torso still — do not lean back.
4. Raise the weights out to the sides until your arms reach shoulder height.
5. Lower under control to the start, resisting the weight the whole way down.
6. Breathing: Inhale before the raise. Exhale as you lift the weights to shoulder height. Inhale on the controlled descent.
7. Form check: Lead with the elbows, not the hands, and keep the wrists neutral.
8. Form check: Stop at shoulder height — going higher shifts work off the side delts.
9. The Kettlebell Single-Arm Lateral Raise mainly trains your Full Body (Multiple Muscle Groups). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$, 'lateral_raise',
  $instr$[rule | engine=exercise_instruction_copy.dart | class=lateral_raise] NASM EPFT 6th ed. ch.13 — single-joint resistance technique$instr$, '2085-2026-05-18'
FROM public.exercise_library_manual WHERE id = '614189d2-7857-41dd-b73d-6c556820d83d'
  AND NOT EXISTS (SELECT 1 FROM public.exercise_instruction_backup
                  WHERE id = '614189d2-7857-41dd-b73d-6c556820d83d');
UPDATE public.exercise_library_manual SET instructions = $instr$1. Stand tall with a slight knee bend, a weight in each hand at your sides.
2. Keep a soft, fixed bend in the elbows of about 10 to 15 degrees.
3. Brace your core and keep your torso still — do not lean back.
4. Raise the weights out to the sides until your arms reach shoulder height.
5. Lower under control to the start, resisting the weight the whole way down.
6. Breathing: Inhale before the raise. Exhale as you lift the weights to shoulder height. Inhale on the controlled descent.
7. Form check: Lead with the elbows, not the hands, and keep the wrists neutral.
8. Form check: Stop at shoulder height — going higher shifts work off the side delts.
9. The Kettlebell Single-Arm Lateral Raise mainly trains your Full Body (Multiple Muscle Groups). If you are newer to it, start light and add load only once the movement feels controlled, and on heavier sets end the set when your form or brace breaks down rather than grinding out a risky rep.$instr$ WHERE id = '614189d2-7857-41dd-b73d-6c556820d83d';
