-- Migration 2201 — daily_lessons content catalog
-- Backs:
--   GET /api/v1/discover/daily-lesson      (today's long-form lesson)
--   GET /api/v1/discover/knowledge-cards   (rotating 3-card slate)
-- Author-curated content (no LLM). Idempotent: re-running is a no-op.

CREATE TABLE IF NOT EXISTS daily_lessons (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    slug text UNIQUE NOT NULL,
    title text NOT NULL,
    body text NOT NULL,
    read_min int NOT NULL DEFAULT 3,
    category text NOT NULL,
    published_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS daily_lessons_category_idx ON daily_lessons (category);
CREATE INDEX IF NOT EXISTS daily_lessons_published_at_idx ON daily_lessons (published_at);

INSERT INTO daily_lessons (slug, title, body, read_min, category) VALUES
('protein-basics', 'Why protein matters more than you think', 'Protein does two jobs lifters rely on: it repairs muscle micro-tears after training and it keeps you full between meals. Aim for 0.7 to 1.0 grams per pound of bodyweight per day if you lift. Spread it across 3 to 5 meals (20 to 40g each) because muscle protein synthesis is meal-by-meal, not a daily bucket. Whole sources — chicken, Greek yogurt, eggs, tofu, lentils, whey — are easier to dose than bars. If you only fix one nutrition variable this month, fix this one.', 4, 'nutrition'),
('80-20-tracking', 'The 80/20 rule of food tracking', 'You do not need to weigh every gram forever. Tight tracking for 2 to 4 weeks teaches you portion sizes and macro patterns; after that, 80% accuracy beats 100% burnout. Log your usual meals once, save them as templates, and eyeball restaurants. The goal is calibration, not religion. People who track loosely for years out-perform people who track perfectly for six weeks then quit.', 3, 'nutrition'),
('sleep-and-strength', 'How sleep affects your strength numbers', 'One night of 5 hours of sleep cuts max strength output by roughly 5 to 10 percent and tanks bar speed even more. Two weeks of restricted sleep cuts testosterone in healthy young men by 10 to 15 percent. Your nervous system is what moves heavy weight, and it consolidates during deep sleep in the first half of the night. If your numbers stall, audit sleep before audit programming.', 4, 'recovery'),
('active-recovery-vs-rest', 'Active recovery vs. full rest days', 'Full rest = no structured exercise. Active recovery = 20 to 40 min of low-intensity movement (walking, easy cycling, mobility) at conversational pace. Active recovery increases blood flow to sore tissue and clears metabolites faster, but it is NOT a hidden workout. If your "easy day" leaves you tired, it was a workout. Use full rest after heavy lower-body sessions; active recovery on most other off days.', 3, 'recovery'),
('reading-nutrition-labels', 'Reading a nutrition label in 10 seconds', 'Check the serving size first — package size and serving size are rarely the same. Then scan in order: calories, protein, fiber, added sugar. Ignore the front of the box. "Low fat" usually means more sugar; "high protein" snack bars often have less than a chicken thigh. Anything with a 4-syllable oil in the first five ingredients is engineered to make you eat more of it.', 4, 'nutrition'),
('caffeine-and-training', 'Caffeine and your workout', 'Caffeine genuinely raises performance — 3 to 6 mg per kg bodyweight, taken 30 to 60 min before training, lifts strength output 2 to 5% and endurance more. But tolerance builds in 2 to 3 weeks. Cycle off for a week each quarter. Avoid caffeine within 8 hours of bed (its half-life is 5 to 6 hours), or your "fine sleep" is actually fragmented sleep masquerading as fine.', 4, 'nutrition'),
('weight-fluctuation', 'Why your weight fluctuates daily', 'Sodium, glycogen, and water swing the scale 2 to 4 lb every day, with no fat change. A 600 mg salt meal can show up as 1.5 lb overnight. Carb-heavy days store ~3g of water per gram of glycogen. Womens cycle phase moves it further. Weigh-in rule: same time, same conditions (post-bathroom, pre-food), and trust the 7-day rolling average — never the daily number.', 4, 'progress'),
('progressive-overload', 'Progressive overload, explained simply', 'You get stronger by giving the muscle slightly more than it handled last time. The four levers: more weight, more reps, more sets, or better technique at the same weight. You do not need all four every session — pick one per exercise per week. Tracking matters; if you cannot beat last weeks log, you are maintaining, not progressing.', 4, 'training'),
('rir-and-rpe', 'RIR and RPE: stop guessing how hard a set was', 'RIR = reps in reserve. RPE = rate of perceived exertion (10 = max). For hypertrophy, most working sets should leave 1 to 3 reps in the tank (RIR 1-3, RPE 7-9). Going to true failure on every set drives fatigue without extra growth and wrecks the next session. Save failure for the last set of small isolation movements, not compounds.', 4, 'training'),
('warmup-that-works', 'A warmup that actually helps', '5 min of light cardio to raise core temperature, then 2 to 3 ramp-up sets at 50%, 70%, and 90% of your working weight for the first compound lift. Skip static stretching pre-lift — it temporarily reduces force output by 5 to 8%. Save the long stretching for after, when tissue is warm. Total warmup time: 8 to 10 min, not 25.', 3, 'training'),
('volume-vs-intensity', 'Volume vs. intensity — when to push which', 'Volume = total work (sets × reps × load). Intensity = how close to max each set is. Both grow muscle, but trade off — high intensity caps how much volume you can recover from. Beginners progress on intensity (just add weight). Intermediates plateau and need to add sets per muscle per week (volume), typically 10 to 20 hard sets per muscle group.', 4, 'training'),
('deload-weeks', 'When to deload — and how', 'After 4 to 8 weeks of progressive overload, performance flattens or drops, sleep gets worse, joints ache. That is accumulated fatigue, not weakness. A deload = 1 week at 50 to 60% of usual volume (cut sets, keep weight). You will come back the following week stronger because fatigue dissipates faster than fitness. Schedule deloads — do not wait until you stall.', 4, 'recovery'),
('hydration-numbers', 'How much water do you actually need', '0.5 to 1.0 oz per pound of bodyweight per day is the working range — more in heat, more if you lift in a hot gym, more if you drink coffee. Pee color is the cheapest gauge: pale lemonade = good, apple juice = behind. A 2% drop in hydration cuts strength output measurably. Carry a 1 L bottle; refill twice = done.', 3, 'recovery'),
('creatine-explained', 'Creatine: the most boring great supplement', '5g of creatine monohydrate daily increases strength 5 to 10%, lean mass 2 to 5 lb over months, and supports brain function. No loading phase needed — it just takes 3 to 4 weeks to saturate. Take it any time of day with any food. Generic monohydrate is the same molecule as any premium label. Skip the rest of the supplement aisle until your training and food are dialed.', 4, 'nutrition'),
('rest-between-sets', 'How long should you rest between sets', 'Compound lifts (squat, bench, deadlift, press) — 2 to 4 min between heavy sets. Isolation (curls, lateral raises, leg extension) — 60 to 90 sec. Resting too little drops strength and recruitment on the next set; resting too long lets the nervous system disengage. Watch the clock; do not let phone scrolling decide.', 3, 'training'),
('eccentric-tempo', 'Eccentric tempo: the cheap hypertrophy lever', 'The lowering phase of a lift (lowering the bar in a bench, descending into a squat) is where most muscle damage and growth signal happens. Take 2 to 4 seconds on the eccentric, 1 second on the concentric. You will use less weight and grow more. This is the single change that turns lifters from "I lift heavy" to "I lift well."', 3, 'training'),
('compound-vs-isolation', 'Compounds first, isolation second', 'Compound lifts (squat, deadlift, bench, row, press, pull-up) hit multiple muscles per rep, drive the most strength, and need a fresh nervous system. Isolation (curls, raises, extensions) cleans up the gaps. Always order compounds first in a session — flipping the order means your compound work happens fatigued.', 3, 'training'),
('walking-for-fat-loss', 'Walking is underrated for fat loss', 'Walking 8,000 to 12,000 steps daily burns 300 to 500 kcal without spiking hunger the way hard cardio does. It does not interfere with lifting recovery. Most lifters who "cannot lose fat" are sedentary outside the gym. A 30 min walk after each main meal also lowers post-meal blood glucose by 15 to 30%.', 3, 'nutrition'),
('protein-timing', 'Protein timing — does the "anabolic window" matter', 'The 30-minute post-workout window is mostly mythology. What matters is total daily protein and that you get a 30 to 40g dose within 2 to 3 hours of training. If you trained fasted, eat sooner. If you ate a protein-rich meal 2 hours before lifting, the window is already covered.', 3, 'nutrition'),
('zone-2-cardio', 'Zone 2 cardio: the boring engine builder', 'Zone 2 = 60 to 70% of max heart rate, conversational pace, breathing through the nose for most of it. 2 to 3 sessions of 30 to 45 min per week improves mitochondrial density, recovery between lifting sets, and resting heart rate. It does not interfere with strength gains the way high-intensity intervals can.', 4, 'cardio'),
('soreness-is-not-progress', 'Soreness is not the goal', 'DOMS (delayed-onset muscle soreness) is a sign of unfamiliar stimulus, not effective training. Beginners are sore from everything; experienced lifters can train hard and barely feel it the next day while still progressing. If chasing soreness drives your programming, you are chasing the wrong signal — chase the logbook instead.', 3, 'training'),
('fiber-target', 'Fiber: the forgotten macronutrient', 'Most adults eat 12 to 15g of fiber daily; the target is 25 to 35g. Fiber slows digestion (steadier energy), feeds gut bacteria, and lowers LDL. Easiest wins: oats at breakfast, beans/lentils at one meal, a piece of fruit and some vegetables at every other meal. Ramp up gradually or you will pay for it.', 3, 'nutrition'),
('alcohol-and-muscle', 'Alcohol and muscle — the real cost', 'One drink does little. Three or more in a session suppresses protein synthesis for ~24 hours, disrupts deep sleep (even if you "pass out fine"), and dehydrates you. If you drink, do it on non-training days and stay under 2 drinks. The hidden cost is not the calories; it is the recovery debt.', 3, 'recovery'),
('mind-muscle-connection', 'Mind-muscle connection — when it helps', 'Consciously focusing on the working muscle (squeezing the lat in a row, tensing the chest at the top of a press) increases activation 5 to 20% on isolation lifts. It matters less on heavy compounds where the load dictates recruitment. Use it on smaller muscles (rear delts, glutes, biceps) where form drift is easy.', 3, 'training'),
('grip-strength-matters', 'Grip strength is a sneaky longevity marker', 'Grip strength predicts all-cause mortality better than blood pressure in adults over 40. Train it deliberately: heavy farmer carries (40m, 3 sets) once a week, dead hangs from a bar 3x weekly to failure, and avoid straps on every pulling set. Strong grip = stronger pulls, stronger forearms, and a measurable health proxy.', 4, 'training'),
('cutting-vs-bulking', 'Cutting vs. bulking — pick one', 'The single biggest beginner mistake is trying to lose fat and gain muscle simultaneously while staying at maintenance. It works for 12 weeks then stalls. Beyond beginner stage, pick a 12 to 20 week cycle: lean bulk at +200 to +400 kcal, or cut at -400 to -600 kcal. Track scale + waist + lift numbers weekly. Switch when one is "done."', 4, 'nutrition'),
('omega-3-and-recovery', 'Omega-3s and recovery', '2 to 3g of combined EPA + DHA daily reduces inflammatory soreness, supports joint health, and may aid muscle protein synthesis in older adults. Most diets are heavy in omega-6 (seed oils) and light on omega-3 (fatty fish, algae oil). 2 servings of salmon/sardines/mackerel per week or a quality fish-oil cap covers it.', 3, 'nutrition'),
('rep-ranges-truth', 'Rep ranges — the real story', 'Sets of 5 to 30 reps all grow muscle if taken close to failure. Heavy (3 to 6 reps) builds more strength per unit volume; moderate (8 to 15) builds size with less joint stress; high (15+) builds endurance and works on small muscles. Most hypertrophy programs live in the 6 to 12 range because it balances all three.', 3, 'training'),
('sleep-environment', 'Fix your sleep environment first', 'Bedroom temperature 65 to 68°F (18 to 20°C). Blackout dark (the tiny LED on your charger matters). Phone outside the room or face-down on do-not-disturb. Consistent wake time 7 days a week — your circadian clock cannot tell weekend from weekday. These four free changes outperform any sleep supplement.', 4, 'recovery'),
('cardio-and-lifting', 'Cardio + lifting — making them coexist', 'The interference effect is real but small. Keep hard cardio (HIIT, sprints) separate from lower-body lift days by at least 6 hours, ideally a different day. Zone 2 cardio can be done the same day as lifting with minimal interference. Cap total weekly cardio at 3 to 4 sessions while in a strength block.', 4, 'cardio')
ON CONFLICT (slug) DO NOTHING;
