-- Add description column to workouts table
-- Stores a 1-2 sentence explanation of the workout's training logic
-- Generated by Gemini during workout creation
ALTER TABLE workouts ADD COLUMN IF NOT EXISTS description TEXT;
