-- 311_common_miscellaneous.sql

INSERT INTO food_nutrition_overrides (
  food_name_normalized, display_name,
  calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g,
  fiber_per_100g, sugar_per_100g,
  default_weight_per_piece_g, default_serving_g,
  source, variant_names, notes,
  restaurant_name, food_category, default_count
) VALUES
('baby_food_fruit_puree', 'Baby Food Fruit Puree', 52, 0.4, 12.5, 0.1, 1.0, 9.5, NULL, 113, 'usda', ARRAY['baby food fruit', 'baby fruit puree', 'gerber fruit puree', 'stage 2 fruit'], '59 cal per pouch (113g). Stage 2, mixed fruit.', NULL, 'snacks', 1),
('baby_food_veggie_puree', 'Baby Food Vegetable Puree', 35, 1.0, 6.5, 0.3, 1.5, 2.5, NULL, 113, 'usda', ARRAY['baby food vegetable', 'baby veggie puree', 'gerber vegetables', 'stage 2 vegetable'], '40 cal per pouch (113g). Stage 2, mixed vegetables.', NULL, 'snacks', 1),
('cheerios_plain', 'Cheerios (Plain)', 375, 11.1, 74.0, 6.3, 10.7, 3.6, NULL, 28, 'usda', ARRAY['cheerios', 'plain cheerios', 'original cheerios', 'toddler cheerios'], '105 cal per cup (28g). Whole grain oat cereal.', NULL, 'snacks', 1),
('animal_crackers', 'Animal Crackers', 446, 6.6, 73.3, 13.3, 1.0, 20.0, 3, 30, 'usda', ARRAY['animal crackers', 'barnum animal crackers', 'stauffer animal crackers'], '134 cal per 10 crackers (30g). Classic snack crackers.', NULL, 'snacks', 10),
('apple_slices_peanut_butter', 'Apple Slices with Peanut Butter', 133, 3.5, 14.0, 7.0, 2.5, 9.5, NULL, 130, 'usda', ARRAY['apple with peanut butter', 'apple and pb', 'apple peanut butter snack'], '173 cal per serving (130g). 1 medium apple + 1 tbsp PB.', NULL, 'snacks', 1),
('tuna_salad', 'Tuna Salad (with Mayo)', 187, 12.0, 6.0, 13.0, 0.3, 2.5, NULL, 120, 'usda', ARRAY['tuna salad', 'canned tuna salad', 'tuna salad with mayo', 'tuna mix'], '224 cal per scoop (120g). With mayo, celery, onion.', NULL, 'proteins', 1),
('hard_boiled_egg_white', 'Hard Boiled Egg White', 52, 11.0, 0.7, 0.2, 0, 0.7, 33, 66, 'usda', ARRAY['egg white', 'boiled egg white', 'hard boiled egg white', 'egg white only'], '34 cal per 2 egg whites (66g). Yolk removed.', NULL, 'proteins', 2),
('chicken_breast_meal_prep', 'Chicken Breast (Meal Prep, Seasoned)', 170, 31.0, 1.0, 4.0, 0, 0, NULL, 150, 'usda', ARRAY['meal prep chicken', 'seasoned chicken breast', 'grilled chicken meal prep', 'baked seasoned chicken'], '255 cal per breast (150g). Baked, lightly seasoned.', NULL, 'proteins', 1),
('ground_turkey_cooked', 'Ground Turkey (Cooked, Seasoned)', 170, 23.0, 1.5, 7.5, 0, 0, NULL, 113, 'usda', ARRAY['cooked ground turkey', 'seasoned ground turkey', 'ground turkey meal prep', 'lean ground turkey'], '192 cal per serving (113g). 93% lean, seasoned.', NULL, 'proteins', 1),
('baked_salmon_meal_prep', 'Baked Salmon (Meal Prep)', 208, 20.0, 0, 13.4, 0, 0, NULL, 140, 'usda', ARRAY['baked salmon', 'meal prep salmon', 'oven baked salmon', 'salmon fillet baked'], '291 cal per fillet (140g). Atlantic, baked.', NULL, 'proteins', 1),
('turkey_meatballs', 'Turkey Meatballs (Homemade)', 157, 17.0, 6.0, 7.0, 0.5, 1.0, 30, 120, 'usda', ARRAY['turkey meatballs', 'homemade turkey meatballs', 'lean turkey meatballs'], '188 cal per 4 meatballs (120g). Lean ground turkey with breadcrumbs.', NULL, 'proteins', 4),
('shredded_chicken', 'Shredded Chicken', 148, 25.0, 0, 5.0, 0, 0, NULL, 85, 'usda', ARRAY['shredded chicken', 'pulled chicken', 'shredded chicken breast', 'rotisserie shredded'], '126 cal per 3 oz (85g). From rotisserie or poached breast.', NULL, 'proteins', 1),
('pulled_pork_slow_cooker', 'Pulled Pork (Slow Cooker)', 210, 22.0, 4.0, 11.5, 0, 3.0, NULL, 113, 'usda', ARRAY['pulled pork', 'slow cooker pulled pork', 'crockpot pulled pork', 'bbq pulled pork'], '237 cal per serving (113g). Pork shoulder, slow-cooked.', NULL, 'proteins', 1),
('instant_ramen_prepared', 'Instant Ramen (Prepared)', 68, 2.5, 9.5, 2.2, 0.5, 0.5, NULL, 550, 'usda', ARRAY['instant ramen', 'ramen noodles prepared', 'maruchan ramen cooked', 'instant noodle soup'], '374 cal per packet prepared (550g). With seasoning and water.', NULL, 'other', 1),
('cup_noodles', 'Cup Noodles (Prepared)', 80, 2.5, 10.5, 3.0, 0.5, 1.0, NULL, 350, 'usda', ARRAY['cup noodles', 'cup of noodles', 'nissin cup noodles', 'cup ramen'], '280 cal per cup prepared (350g). With hot water.', NULL, 'other', 1),
('canned_soup_chicken_noodle', 'Canned Chicken Noodle Soup', 30, 1.6, 3.8, 0.8, 0.4, 0.5, NULL, 248, 'usda', ARRAY['chicken noodle soup', 'canned chicken soup', 'campbells chicken noodle', 'chicken soup'], '74 cal per cup (248g). Ready-to-serve.', NULL, 'other', 1),
('canned_chili', 'Canned Chili (with Beans)', 90, 6.5, 10.0, 2.5, 3.0, 2.5, NULL, 247, 'usda', ARRAY['canned chili', 'hormel chili', 'canned chili with beans', 'chili con carne'], '222 cal per cup (247g). With beans, ready-to-serve.', NULL, 'other', 1),
('frozen_lean_meal', 'Frozen Meal (Generic Lean)', 100, 8.0, 14.0, 1.5, 1.5, 3.0, 255, 255, 'usda', ARRAY['frozen lean meal', 'frozen diet meal', 'healthy choice meal', 'smart ones meal'], '255 cal per meal (255g). Low-calorie frozen entree.', NULL, 'other', 1),
('microwave_mac_cheese', 'Microwave Mac & Cheese', 170, 5.5, 22.0, 6.5, 0.5, 4.0, 206, 206, 'usda', ARRAY['microwave mac and cheese', 'velveeta mac and cheese cup', 'easy mac', 'mac and cheese cup'], '350 cal per cup (206g). Single serve, microwaveable.', NULL, 'other', 1),
('instant_mashed_potatoes', 'Instant Mashed Potatoes (Prepared)', 78, 2.0, 14.5, 1.5, 1.0, 1.0, NULL, 210, 'usda', ARRAY['instant mashed potatoes', 'mashed potatoes instant', 'idahoan mashed potatoes', 'potato flakes'], '164 cal per cup prepared (210g). With water and butter.', NULL, 'other', 1),
('boxed_mac_cheese', 'Boxed Mac & Cheese (Prepared)', 164, 5.8, 21.0, 6.2, 0.7, 4.5, NULL, 200, 'usda', ARRAY['kraft mac and cheese', 'boxed mac and cheese', 'macaroni and cheese', 'kraft dinner'], '328 cal per cup prepared (200g). With milk and butter.', NULL, 'other', 1),
('ramen_noodles_dry', 'Ramen Noodles (Dry Block)', 436, 9.0, 62.0, 17.0, 2.0, 1.5, 85, 85, 'usda', ARRAY['dry ramen', 'ramen block', 'instant noodle dry', 'maruchan dry'], '371 cal per dry block (85g). Before cooking, without seasoning.', NULL, 'other', 1),
('top_ramen_prepared', 'Top Ramen (Prepared with Seasoning)', 72, 2.5, 9.8, 2.3, 0.5, 0.5, NULL, 530, 'usda', ARRAY['top ramen', 'top ramen prepared', 'nissin top ramen', 'top ramen cooked'], '382 cal per packet prepared (530g). With full seasoning packet.', NULL, 'other', 1),
('butter_serving', 'Butter', 717, 0.9, 0.1, 81.0, 0, 0.1, 14, 14, 'usda', ARRAY['butter', 'salted butter', 'unsalted butter', 'butter pat', 'butter serving'], '100 cal per tbsp (14g). Salted, stick butter.', NULL, 'condiments', 1),
('cream_cheese_serving', 'Cream Cheese', 342, 5.9, 4.1, 34.2, 0, 3.2, 28, 28, 'usda', ARRAY['cream cheese', 'philadelphia cream cheese', 'cream cheese spread', 'schmear'], '96 cal per 1 oz (28g). Regular, full fat.', NULL, 'condiments', 1),
('avocado_mash', 'Avocado Mash', 160, 2.0, 8.5, 14.7, 6.7, 0.7, NULL, 50, 'usda', ARRAY['avocado mash', 'mashed avocado', 'smashed avocado', 'avocado toast topping', 'guacamole basic'], '80 cal per 1/4 avocado (50g). Mashed, plain.', NULL, 'condiments', 1),
('ricotta_toast', 'Ricotta (Toast Topping)', 174, 11.3, 3.0, 13.0, 0, 0.3, NULL, 60, 'usda', ARRAY['ricotta', 'ricotta cheese', 'ricotta toast', 'whole milk ricotta'], '104 cal per 1/4 cup (60g). Whole milk ricotta.', NULL, 'condiments', 1),
('goat_cheese_spread', 'Goat Cheese (Chevre)', 364, 21.6, 0.1, 30.0, 0, 0.1, NULL, 28, 'usda', ARRAY['goat cheese', 'chevre', 'goat cheese crumble', 'goat cheese spread'], '102 cal per 1 oz (28g). Soft, fresh.', NULL, 'condiments', 1),
('croutons', 'Croutons (Seasoned)', 407, 11.6, 62.0, 12.6, 3.0, 5.0, NULL, 7, 'usda', ARRAY['croutons', 'seasoned croutons', 'salad croutons', 'garlic croutons'], '29 cal per 2 tbsp (7g). Seasoned, store-bought.', NULL, 'condiments', 1),
('bacon_bits', 'Bacon Bits (Real)', 400, 33.3, 3.3, 27.8, 0, 0, NULL, 7, 'usda', ARRAY['bacon bits', 'real bacon bits', 'bacon crumbles', 'oscar mayer bacon bits'], '28 cal per tbsp (7g). Cured pork, crumbled.', NULL, 'condiments', 1),
('shredded_cheese_salad', 'Shredded Cheese (for Salad)', 393, 24.0, 1.5, 32.5, 0, 0.5, NULL, 28, 'usda', ARRAY['shredded cheese', 'shredded cheddar', 'cheese topping', 'grated cheese'], '110 cal per 1/4 cup (28g). Cheddar or Mexican blend.', NULL, 'condiments', 1),
('dried_cranberries_salad', 'Dried Cranberries (for Salad)', 325, 0.2, 82.0, 1.4, 5.3, 65.0, NULL, 20, 'usda', ARRAY['dried cranberries', 'craisins', 'ocean spray craisins', 'cranberry raisins'], '65 cal per 2 tbsp (20g). Sweetened, dried.', NULL, 'condiments', 1),
('sliced_almonds_salad', 'Sliced Almonds (for Salad)', 576, 21.0, 22.0, 49.4, 12.2, 3.9, NULL, 11, 'usda', ARRAY['sliced almonds', 'slivered almonds', 'almond slices', 'salad almonds'], '63 cal per 2 tbsp (11g). Blanched, sliced.', NULL, 'condiments', 1),
('sunflower_seeds_salad', 'Sunflower Seeds (for Salad)', 584, 20.8, 20.0, 51.5, 8.6, 2.6, NULL, 9, 'usda', ARRAY['sunflower seeds', 'sunflower seed kernels', 'salad seeds'], '53 cal per tbsp (9g). Hulled, roasted.', NULL, 'condiments', 1),
('ranch_dip', 'Ranch Dip', 200, 1.7, 6.7, 18.3, 0, 3.3, NULL, 30, 'usda', ARRAY['ranch dip', 'ranch veggie dip', 'hidden valley ranch dip'], '60 cal per 2 tbsp (30g). Sour cream based.', NULL, 'condiments', 1),
('spinach_artichoke_dip', 'Spinach Artichoke Dip', 180, 4.5, 8.0, 14.0, 1.0, 2.0, NULL, 34, 'usda', ARRAY['spinach artichoke dip', 'spinach dip', 'hot spinach dip', 'artichoke dip'], '61 cal per 2 tbsp (34g). Warm, cream cheese based.', NULL, 'condiments', 1),
('french_onion_dip', 'French Onion Dip', 180, 2.5, 10.0, 14.0, 0.5, 5.0, NULL, 30, 'usda', ARRAY['french onion dip', 'onion dip', 'sour cream onion dip', 'lay dip'], '54 cal per 2 tbsp (30g). Sour cream based.', NULL, 'condiments', 1),
('cheese_dip_queso', 'Cheese Dip (Queso)', 153, 5.0, 8.0, 11.0, 0.3, 3.0, NULL, 33, 'usda', ARRAY['queso dip', 'cheese dip', 'nacho cheese dip', 'queso blanco'], '50 cal per 2 tbsp (33g). Melted cheese dip.', NULL, 'condiments', 1),
('bean_dip', 'Bean Dip', 95, 4.5, 13.0, 2.5, 3.5, 1.0, NULL, 34, 'usda', ARRAY['bean dip', 'refried bean dip', 'frito lay bean dip', 'black bean dip'], '32 cal per 2 tbsp (34g). Refried bean based.', NULL, 'condiments', 1),
('buffalo_chicken_dip', 'Buffalo Chicken Dip', 170, 10.0, 4.0, 13.0, 0.2, 1.5, NULL, 34, 'usda', ARRAY['buffalo chicken dip', 'buffalo dip', 'hot chicken dip'], '58 cal per 2 tbsp (34g). Shredded chicken, cream cheese, hot sauce.', NULL, 'condiments', 1),
('cauliflower_rice', 'Cauliflower Rice', 25, 1.9, 3.9, 0.3, 2.0, 1.5, NULL, 85, 'usda', ARRAY['cauliflower rice', 'riced cauliflower', 'cauliflower crumbles', 'cauli rice'], '21 cal per serving (85g). Raw, riced.', NULL, 'other', 1),
('zucchini_noodles', 'Zucchini Noodles (Zoodles)', 17, 1.2, 2.7, 0.3, 1.0, 1.7, NULL, 113, 'usda', ARRAY['zucchini noodles', 'zoodles', 'spiralized zucchini', 'zucchini pasta'], '19 cal per cup (113g). Raw, spiralized.', NULL, 'other', 1),
('spaghetti_squash', 'Spaghetti Squash (Cooked)', 31, 0.6, 6.5, 0.6, 1.5, 2.5, NULL, 155, 'usda', ARRAY['spaghetti squash', 'squash noodles', 'cooked spaghetti squash'], '48 cal per cup (155g). Baked, fork-scraped strands.', NULL, 'other', 1),
('shirataki_noodles', 'Shirataki Noodles', 9, 0, 3.0, 0, 3.0, 0, NULL, 113, 'usda', ARRAY['shirataki noodles', 'konjac noodles', 'miracle noodles', 'zero calorie noodles'], '10 cal per serving (113g). Glucomannan fiber, nearly zero cal.', NULL, 'other', 1),
('lettuce_wrap', 'Lettuce Wrap (Butter Lettuce)', 15, 1.3, 2.2, 0.2, 1.1, 0.7, 30, 30, 'usda', ARRAY['lettuce wrap', 'butter lettuce wrap', 'lettuce cup', 'lettuce bun'], '5 cal per leaf (30g). Used as bun replacement.', NULL, 'other', 1),
('coconut_flour', 'Coconut Flour', 443, 17.5, 60.0, 14.0, 39.0, 8.0, NULL, 15, 'usda', ARRAY['coconut flour', 'organic coconut flour', 'gluten free coconut flour'], '66 cal per 2 tbsp (15g). High fiber, gluten-free.', NULL, 'other', 1),
('almond_flour', 'Almond Flour', 571, 21.4, 19.6, 50.0, 10.7, 3.6, NULL, 14, 'usda', ARRAY['almond flour', 'almond meal', 'blanched almond flour', 'ground almonds'], '80 cal per 2 tbsp (14g). Blanched, finely ground.', NULL, 'other', 1),
('cassava_flour', 'Cassava Flour', 340, 1.4, 83.0, 0.3, 4.0, 3.7, NULL, 25, 'usda', ARRAY['cassava flour', 'tapioca flour', 'yuca flour', 'otto cassava flour'], '85 cal per 2 tbsp (25g). Grain-free, paleo-friendly.', NULL, 'other', 1),
('protein_powder_generic', 'Protein Powder (Whey, Generic)', 400, 80.0, 10.0, 3.3, 0, 3.0, NULL, 30, 'usda', ARRAY['protein powder', 'whey protein', 'protein shake powder', 'whey isolate', 'protein scoop'], '120 cal per scoop (30g). Whey isolate, unflavored.', NULL, 'other', 1),
('chia_seeds', 'Chia Seeds', 486, 16.5, 42.1, 30.7, 34.4, 0, NULL, 12, 'usda', ARRAY['chia seeds', 'chia', 'organic chia seeds', 'chia seed'], '58 cal per tbsp (12g). Rich in omega-3, fiber.', NULL, 'other', 1),
('flax_meal', 'Flax Meal (Ground Flaxseed)', 534, 18.3, 28.9, 42.2, 27.3, 1.6, NULL, 7, 'usda', ARRAY['flax meal', 'ground flaxseed', 'flaxseed meal', 'milled flax', 'linseed meal'], '37 cal per tbsp (7g). Ground, golden or brown.', NULL, 'other', 1),
('spirulina_powder', 'Spirulina Powder', 290, 57.5, 24.0, 7.7, 3.6, 3.1, NULL, 7, 'usda', ARRAY['spirulina', 'spirulina powder', 'blue spirulina', 'green spirulina'], '20 cal per tsp (7g). Dried blue-green algae.', NULL, 'other', 1),
('mct_oil', 'MCT Oil', 862, 0, 0, 95.8, 0, 0, NULL, 14, 'usda', ARRAY['mct oil', 'medium chain triglyceride oil', 'mct coconut oil', 'brain octane'], '121 cal per tbsp (14g). 100% medium-chain triglycerides.', NULL, 'other', 1),
('collagen_peptides', 'Collagen Peptides', 360, 90.0, 0, 0, 0, 0, NULL, 10, 'usda', ARRAY['collagen peptides', 'collagen powder', 'vital proteins collagen', 'hydrolyzed collagen'], '36 cal per scoop (10g). Hydrolyzed, unflavored.', NULL, 'other', 1),
('jasmine_rice_cooked', 'Jasmine Rice (Cooked)', 130, 2.7, 28.0, 0.3, 0.4, 0, NULL, 186, 'usda', ARRAY['jasmine rice', 'cooked jasmine rice', 'thai jasmine rice', 'white jasmine rice'], '242 cal per cup (186g). Fragrant Thai rice.', NULL, 'staples', 1),
('basmati_rice_cooked', 'Basmati Rice (Cooked)', 121, 3.5, 25.0, 0.4, 0.4, 0, NULL, 186, 'usda', ARRAY['basmati rice', 'cooked basmati rice', 'indian basmati', 'white basmati rice'], '225 cal per cup (186g). Long-grain, aromatic.', NULL, 'staples', 1),
('sushi_rice_cooked', 'Sushi Rice (Cooked)', 143, 2.5, 31.0, 0.3, 0.3, 3.0, NULL, 186, 'usda', ARRAY['sushi rice', 'cooked sushi rice', 'seasoned sushi rice', 'vinegared rice'], '266 cal per cup (186g). Short-grain, seasoned with rice vinegar and sugar.', NULL, 'staples', 1),
('arborio_rice_cooked', 'Arborio Rice (Cooked, for Risotto)', 130, 2.4, 28.5, 0.3, 0.3, 0, NULL, 186, 'usda', ARRAY['arborio rice', 'risotto rice', 'cooked arborio', 'italian rice cooked'], '242 cal per cup (186g). Starchy, creamy Italian rice.', NULL, 'staples', 1),
('sticky_rice_cooked', 'Sticky Rice (Glutinous, Cooked)', 97, 2.0, 21.1, 0.2, 0.3, 0, NULL, 174, 'usda', ARRAY['sticky rice', 'glutinous rice', 'sweet rice', 'mochi rice', 'thai sticky rice'], '169 cal per cup (174g). Steamed, short-grain, very sticky.', NULL, 'staples', 1),
('fried_rice_plain', 'Fried Rice (Plain/Basic)', 163, 3.5, 22.0, 6.5, 0.8, 0.5, NULL, 200, 'usda', ARRAY['fried rice', 'plain fried rice', 'basic fried rice', 'egg fried rice', 'chinese fried rice'], '326 cal per cup (200g). With egg, soy sauce, oil, scallions.', NULL, 'staples', 1)

ON CONFLICT (food_name_normalized) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  calories_per_100g = EXCLUDED.calories_per_100g,
  protein_per_100g = EXCLUDED.protein_per_100g,
  carbs_per_100g = EXCLUDED.carbs_per_100g,
  fat_per_100g = EXCLUDED.fat_per_100g,
  fiber_per_100g = EXCLUDED.fiber_per_100g,
  sugar_per_100g = EXCLUDED.sugar_per_100g,
  default_weight_per_piece_g = EXCLUDED.default_weight_per_piece_g,
  default_serving_g = EXCLUDED.default_serving_g,
  source = EXCLUDED.source,
  variant_names = EXCLUDED.variant_names,
  notes = EXCLUDED.notes,
  restaurant_name = EXCLUDED.restaurant_name,
  food_category = EXCLUDED.food_category,
  default_count = EXCLUDED.default_count,
  updated_at = NOW();
