/// Country codes with names and flag emoji for food region filtering.
/// Covers all 212 regions that have food data in the database.
library;

class CountryCode {
  final String code; // ISO alpha-2
  final String name;
  final String flag; // Unicode flag emoji

  const CountryCode({required this.code, required this.name, required this.flag});
}

/// Returns the Unicode flag emoji for an ISO alpha-2 country code.
String countryFlag(String code) {
  final upper = code.toUpperCase();
  if (upper.length != 2) return '🌐';
  final a = upper.codeUnitAt(0);
  final b = upper.codeUnitAt(1);
  return String.fromCharCode(0x1F1E6 + a - 65) +
      String.fromCharCode(0x1F1E6 + b - 65);
}

/// All 212 countries/territories with food data, sorted alphabetically by name.
const List<CountryCode> kCountryCodes = [
  CountryCode(code: 'AF', name: 'Afghanistan', flag: '🇦🇫'),
  CountryCode(code: 'AL', name: 'Albania', flag: '🇦🇱'),
  CountryCode(code: 'DZ', name: 'Algeria', flag: '🇩🇿'),
  CountryCode(code: 'AD', name: 'Andorra', flag: '🇦🇩'),
  CountryCode(code: 'AO', name: 'Angola', flag: '🇦🇴'),
  CountryCode(code: 'AG', name: 'Antigua & Barbuda', flag: '🇦🇬'),
  CountryCode(code: 'AR', name: 'Argentina', flag: '🇦🇷'),
  CountryCode(code: 'AM', name: 'Armenia', flag: '🇦🇲'),
  CountryCode(code: 'AW', name: 'Aruba', flag: '🇦🇼'),
  CountryCode(code: 'AS', name: 'American Samoa', flag: '🇦🇸'),
  CountryCode(code: 'AU', name: 'Australia', flag: '🇦🇺'),
  CountryCode(code: 'AT', name: 'Austria', flag: '🇦🇹'),
  CountryCode(code: 'AZ', name: 'Azerbaijan', flag: '🇦🇿'),
  CountryCode(code: 'BS', name: 'Bahamas', flag: '🇧🇸'),
  CountryCode(code: 'BH', name: 'Bahrain', flag: '🇧🇭'),
  CountryCode(code: 'BD', name: 'Bangladesh', flag: '🇧🇩'),
  CountryCode(code: 'BB', name: 'Barbados', flag: '🇧🇧'),
  CountryCode(code: 'BY', name: 'Belarus', flag: '🇧🇾'),
  CountryCode(code: 'BE', name: 'Belgium', flag: '🇧🇪'),
  CountryCode(code: 'BZ', name: 'Belize', flag: '🇧🇿'),
  CountryCode(code: 'BJ', name: 'Benin', flag: '🇧🇯'),
  CountryCode(code: 'BM', name: 'Bermuda', flag: '🇧🇲'),
  CountryCode(code: 'BT', name: 'Bhutan', flag: '🇧🇹'),
  CountryCode(code: 'BO', name: 'Bolivia', flag: '🇧🇴'),
  CountryCode(code: 'BA', name: 'Bosnia & Herzegovina', flag: '🇧🇦'),
  CountryCode(code: 'BW', name: 'Botswana', flag: '🇧🇼'),
  CountryCode(code: 'BR', name: 'Brazil', flag: '🇧🇷'),
  CountryCode(code: 'BN', name: 'Brunei', flag: '🇧🇳'),
  CountryCode(code: 'BG', name: 'Bulgaria', flag: '🇧🇬'),
  CountryCode(code: 'BF', name: 'Burkina Faso', flag: '🇧🇫'),
  CountryCode(code: 'BI', name: 'Burundi', flag: '🇧🇮'),
  CountryCode(code: 'KH', name: 'Cambodia', flag: '🇰🇭'),
  CountryCode(code: 'CM', name: 'Cameroon', flag: '🇨🇲'),
  CountryCode(code: 'CA', name: 'Canada', flag: '🇨🇦'),
  CountryCode(code: 'CV', name: 'Cape Verde', flag: '🇨🇻'),
  CountryCode(code: 'KY', name: 'Cayman Islands', flag: '🇰🇾'),
  CountryCode(code: 'CF', name: 'Central African Republic', flag: '🇨🇫'),
  CountryCode(code: 'TD', name: 'Chad', flag: '🇹🇩'),
  CountryCode(code: 'CL', name: 'Chile', flag: '🇨🇱'),
  CountryCode(code: 'CN', name: 'China', flag: '🇨🇳'),
  CountryCode(code: 'CO', name: 'Colombia', flag: '🇨🇴'),
  CountryCode(code: 'KM', name: 'Comoros', flag: '🇰🇲'),
  CountryCode(code: 'CG', name: 'Congo', flag: '🇨🇬'),
  CountryCode(code: 'CD', name: 'Congo (DR)', flag: '🇨🇩'),
  CountryCode(code: 'CR', name: 'Costa Rica', flag: '🇨🇷'),
  CountryCode(code: 'HR', name: 'Croatia', flag: '🇭🇷'),
  CountryCode(code: 'CU', name: 'Cuba', flag: '🇨🇺'),
  CountryCode(code: 'CY', name: 'Cyprus', flag: '🇨🇾'),
  CountryCode(code: 'CZ', name: 'Czech Republic', flag: '🇨🇿'),
  CountryCode(code: 'DK', name: 'Denmark', flag: '🇩🇰'),
  CountryCode(code: 'DJ', name: 'Djibouti', flag: '🇩🇯'),
  CountryCode(code: 'DM', name: 'Dominica', flag: '🇩🇲'),
  CountryCode(code: 'DO', name: 'Dominican Republic', flag: '🇩🇴'),
  CountryCode(code: 'EC', name: 'Ecuador', flag: '🇪🇨'),
  CountryCode(code: 'EG', name: 'Egypt', flag: '🇪🇬'),
  CountryCode(code: 'SV', name: 'El Salvador', flag: '🇸🇻'),
  CountryCode(code: 'GQ', name: 'Equatorial Guinea', flag: '🇬🇶'),
  CountryCode(code: 'ER', name: 'Eritrea', flag: '🇪🇷'),
  CountryCode(code: 'EE', name: 'Estonia', flag: '🇪🇪'),
  CountryCode(code: 'ET', name: 'Ethiopia', flag: '🇪🇹'),
  CountryCode(code: 'FO', name: 'Faroe Islands', flag: '🇫🇴'),
  CountryCode(code: 'FJ', name: 'Fiji', flag: '🇫🇯'),
  CountryCode(code: 'FI', name: 'Finland', flag: '🇫🇮'),
  CountryCode(code: 'FR', name: 'France', flag: '🇫🇷'),
  CountryCode(code: 'PF', name: 'French Polynesia', flag: '🇵🇫'),
  CountryCode(code: 'GF', name: 'French Guiana', flag: '🇬🇫'),
  CountryCode(code: 'GA', name: 'Gabon', flag: '🇬🇦'),
  CountryCode(code: 'GM', name: 'Gambia', flag: '🇬🇲'),
  CountryCode(code: 'GE', name: 'Georgia', flag: '🇬🇪'),
  CountryCode(code: 'DE', name: 'Germany', flag: '🇩🇪'),
  CountryCode(code: 'GH', name: 'Ghana', flag: '🇬🇭'),
  CountryCode(code: 'GR', name: 'Greece', flag: '🇬🇷'),
  CountryCode(code: 'GL', name: 'Greenland', flag: '🇬🇱'),
  CountryCode(code: 'GD', name: 'Grenada', flag: '🇬🇩'),
  CountryCode(code: 'GP', name: 'Guadeloupe', flag: '🇬🇵'),
  CountryCode(code: 'GU', name: 'Guam', flag: '🇬🇺'),
  CountryCode(code: 'GT', name: 'Guatemala', flag: '🇬🇹'),
  CountryCode(code: 'GG', name: 'Guernsey', flag: '🇬🇬'),
  CountryCode(code: 'GN', name: 'Guinea', flag: '🇬🇳'),
  CountryCode(code: 'GW', name: 'Guinea-Bissau', flag: '🇬🇼'),
  CountryCode(code: 'GY', name: 'Guyana', flag: '🇬🇾'),
  CountryCode(code: 'HT', name: 'Haiti', flag: '🇭🇹'),
  CountryCode(code: 'HN', name: 'Honduras', flag: '🇭🇳'),
  CountryCode(code: 'HK', name: 'Hong Kong', flag: '🇭🇰'),
  CountryCode(code: 'HU', name: 'Hungary', flag: '🇭🇺'),
  CountryCode(code: 'IS', name: 'Iceland', flag: '🇮🇸'),
  CountryCode(code: 'IN', name: 'India', flag: '🇮🇳'),
  CountryCode(code: 'ID', name: 'Indonesia', flag: '🇮🇩'),
  CountryCode(code: 'IR', name: 'Iran', flag: '🇮🇷'),
  CountryCode(code: 'IE', name: 'Ireland', flag: '🇮🇪'),
  CountryCode(code: 'IM', name: 'Isle of Man', flag: '🇮🇲'),
  CountryCode(code: 'IL', name: 'Israel', flag: '🇮🇱'),
  CountryCode(code: 'IT', name: 'Italy', flag: '🇮🇹'),
  CountryCode(code: 'CI', name: 'Ivory Coast', flag: '🇨🇮'),
  CountryCode(code: 'JM', name: 'Jamaica', flag: '🇯🇲'),
  CountryCode(code: 'JP', name: 'Japan', flag: '🇯🇵'),
  CountryCode(code: 'JE', name: 'Jersey', flag: '🇯🇪'),
  CountryCode(code: 'JO', name: 'Jordan', flag: '🇯🇴'),
  CountryCode(code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿'),
  CountryCode(code: 'KE', name: 'Kenya', flag: '🇰🇪'),
  CountryCode(code: 'KI', name: 'Kiribati', flag: '🇰🇮'),
  CountryCode(code: 'KW', name: 'Kuwait', flag: '🇰🇼'),
  CountryCode(code: 'KG', name: 'Kyrgyzstan', flag: '🇰🇬'),
  CountryCode(code: 'LA', name: 'Laos', flag: '🇱🇦'),
  CountryCode(code: 'LV', name: 'Latvia', flag: '🇱🇻'),
  CountryCode(code: 'LB', name: 'Lebanon', flag: '🇱🇧'),
  CountryCode(code: 'LS', name: 'Lesotho', flag: '🇱🇸'),
  CountryCode(code: 'LR', name: 'Liberia', flag: '🇱🇷'),
  CountryCode(code: 'LY', name: 'Libya', flag: '🇱🇾'),
  CountryCode(code: 'LI', name: 'Liechtenstein', flag: '🇱🇮'),
  CountryCode(code: 'LT', name: 'Lithuania', flag: '🇱🇹'),
  CountryCode(code: 'LU', name: 'Luxembourg', flag: '🇱🇺'),
  CountryCode(code: 'MO', name: 'Macau', flag: '🇲🇴'),
  CountryCode(code: 'MK', name: 'North Macedonia', flag: '🇲🇰'),
  CountryCode(code: 'MG', name: 'Madagascar', flag: '🇲🇬'),
  CountryCode(code: 'MW', name: 'Malawi', flag: '🇲🇼'),
  CountryCode(code: 'MY', name: 'Malaysia', flag: '🇲🇾'),
  CountryCode(code: 'MV', name: 'Maldives', flag: '🇲🇻'),
  CountryCode(code: 'ML', name: 'Mali', flag: '🇲🇱'),
  CountryCode(code: 'MT', name: 'Malta', flag: '🇲🇹'),
  CountryCode(code: 'MH', name: 'Marshall Islands', flag: '🇲🇭'),
  CountryCode(code: 'MQ', name: 'Martinique', flag: '🇲🇶'),
  CountryCode(code: 'MR', name: 'Mauritania', flag: '🇲🇷'),
  CountryCode(code: 'MU', name: 'Mauritius', flag: '🇲🇺'),
  CountryCode(code: 'YT', name: 'Mayotte', flag: '🇾🇹'),
  CountryCode(code: 'MX', name: 'Mexico', flag: '🇲🇽'),
  CountryCode(code: 'FM', name: 'Micronesia', flag: '🇫🇲'),
  CountryCode(code: 'MD', name: 'Moldova', flag: '🇲🇩'),
  CountryCode(code: 'MC', name: 'Monaco', flag: '🇲🇨'),
  CountryCode(code: 'MN', name: 'Mongolia', flag: '🇲🇳'),
  CountryCode(code: 'ME', name: 'Montenegro', flag: '🇲🇪'),
  CountryCode(code: 'MA', name: 'Morocco', flag: '🇲🇦'),
  CountryCode(code: 'MZ', name: 'Mozambique', flag: '🇲🇿'),
  CountryCode(code: 'MM', name: 'Myanmar', flag: '🇲🇲'),
  CountryCode(code: 'NA', name: 'Namibia', flag: '🇳🇦'),
  CountryCode(code: 'NP', name: 'Nepal', flag: '🇳🇵'),
  CountryCode(code: 'NL', name: 'Netherlands', flag: '🇳🇱'),
  CountryCode(code: 'NC', name: 'New Caledonia', flag: '🇳🇨'),
  CountryCode(code: 'NZ', name: 'New Zealand', flag: '🇳🇿'),
  CountryCode(code: 'NI', name: 'Nicaragua', flag: '🇳🇮'),
  CountryCode(code: 'NE', name: 'Niger', flag: '🇳🇪'),
  CountryCode(code: 'NG', name: 'Nigeria', flag: '🇳🇬'),
  CountryCode(code: 'MP', name: 'Northern Mariana Islands', flag: '🇲🇵'),
  CountryCode(code: 'NO', name: 'Norway', flag: '🇳🇴'),
  CountryCode(code: 'OM', name: 'Oman', flag: '🇴🇲'),
  CountryCode(code: 'PK', name: 'Pakistan', flag: '🇵🇰'),
  CountryCode(code: 'PA', name: 'Panama', flag: '🇵🇦'),
  CountryCode(code: 'PY', name: 'Paraguay', flag: '🇵🇾'),
  CountryCode(code: 'PH', name: 'Philippines', flag: '🇵🇭'),
  CountryCode(code: 'PL', name: 'Poland', flag: '🇵🇱'),
  CountryCode(code: 'PT', name: 'Portugal', flag: '🇵🇹'),
  CountryCode(code: 'QA', name: 'Qatar', flag: '🇶🇦'),
  CountryCode(code: 'RU', name: 'Russia', flag: '🇷🇺'),
  CountryCode(code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦'),
  CountryCode(code: 'SG', name: 'Singapore', flag: '🇸🇬'),
  CountryCode(code: 'ZA', name: 'South Africa', flag: '🇿🇦'),
  CountryCode(code: 'KR', name: 'South Korea', flag: '🇰🇷'),
  CountryCode(code: 'ES', name: 'Spain', flag: '🇪🇸'),
  CountryCode(code: 'SE', name: 'Sweden', flag: '🇸🇪'),
  CountryCode(code: 'TH', name: 'Thailand', flag: '🇹🇭'),
  CountryCode(code: 'TR', name: 'Turkey', flag: '🇹🇷'),
  CountryCode(code: 'UA', name: 'Ukraine', flag: '🇺🇦'),
  CountryCode(code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪'),
  CountryCode(code: 'GB', name: 'United Kingdom', flag: '🇬🇧'),
  CountryCode(code: 'US', name: 'United States', flag: '🇺🇸'),
  CountryCode(code: 'VN', name: 'Vietnam', flag: '🇻🇳'),
];
