/// Pre-Set Coaching Banner
///
/// Inline banner rendered above Set 1 of an exercise in the active workout
/// screen. Surfaces a data-grounded, cross-session insight generated by
/// [PreSetInsightEngine]. Persistent until dismissed (or until the first set
/// is logged — the parent stops passing a message at that point).
library;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_animate/flutter_animate.dart';

import '../../../core/constants/app_colors.dart';

class PreSetCoachingBanner extends StatelessWidget {
  final String message;
  final VoidCallback onDismiss;

  /// Used as the animation key so the banner re-animates when the message
  /// or exercise changes, but stays quiet across incidental rebuilds.
  final String animationKey;

  const PreSetCoachingBanner({
    super.key,
    required this.message,
    required this.onDismiss,
    required this.animationKey,
  });

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;

    final borderColor = const Color(0xFFD4A24E).withOpacity(0.35);
    final iconColor = const Color(0xFFD4A24E);
    final bg = isDark ? const Color(0xFF1F1B14) : const Color(0xFFFFF8E7);
    final textColor = isDark ? Colors.white : AppColors.pureBlack;

    return Semantics(
      label: 'Coaching insight. $message.',
      container: true,
      child: Padding(
        padding: const EdgeInsets.fromLTRB(12, 10, 12, 8),
        child: Container(
          padding: const EdgeInsets.fromLTRB(12, 10, 4, 10),
          decoration: BoxDecoration(
            color: bg,
            borderRadius: BorderRadius.circular(12),
            border: Border.all(color: borderColor, width: 1),
          ),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Padding(
                padding: const EdgeInsets.only(top: 2, right: 10),
                child: Icon(
                  Icons.auto_awesome, // ✨ sparkle
                  size: 16,
                  color: iconColor,
                ),
              ),
              Expanded(
                child: Text(
                  message,
                  maxLines: 3,
                  overflow: TextOverflow.ellipsis,
                  style: TextStyle(
                    fontSize: 13.5,
                    height: 1.35,
                    color: textColor,
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
              Semantics(
                button: true,
                label: 'Dismiss coaching insight',
                child: IconButton(
                  tooltip: 'Dismiss',
                  iconSize: 18,
                  padding: EdgeInsets.zero,
                  constraints: const BoxConstraints(
                    minWidth: 40,
                    minHeight: 40,
                  ),
                  visualDensity: VisualDensity.compact,
                  icon: Icon(
                    Icons.close_rounded,
                    color: textColor.withOpacity(0.6),
                  ),
                  onPressed: () {
                    HapticFeedback.selectionClick();
                    onDismiss();
                  },
                ),
              ),
            ],
          ),
        ),
      ),
    )
        .animate(key: ValueKey(animationKey))
        .fadeIn(duration: 220.ms, curve: Curves.easeOutCubic)
        .slideY(begin: -0.08, end: 0, duration: 220.ms, curve: Curves.easeOutCubic);
  }
}
