import 'package:flutter/material.dart';

enum ChatActionBehavior { sendPrompt, openMediaPicker }

enum ChatMediaMode { camera, gallery, video, recordVideo }

class ChatQuickAction {
  final String id;
  final String label;
  final String description;
  final String category;
  final IconData icon;
  final Color color;
  final ChatActionBehavior behavior;
  final String? prompt;
  final ChatMediaMode? mediaMode;
  final String? examplePrompt;

  const ChatQuickAction({
    required this.id,
    required this.label,
    required this.description,
    required this.category,
    required this.icon,
    required this.color,
    required this.behavior,
    this.prompt,
    this.mediaMode,
    this.examplePrompt,
  });
}

const chatQuickActionRegistry = <String, ChatQuickAction>{
  'check_form': ChatQuickAction(
    id: 'check_form',
    label: 'Check My Form',
    description: 'Record an exercise for AI form feedback',
    category: 'Form Analysis',
    icon: Icons.videocam_outlined,
    color: Color(0xFFF97316),
    behavior: ChatActionBehavior.openMediaPicker,
    mediaMode: ChatMediaMode.video,
    examplePrompt: 'Please check my exercise form',
  ),
  'scan_food': ChatQuickAction(
    id: 'scan_food',
    label: 'Scan Food',
    description: 'Snap a photo for instant calorie estimates',
    category: 'Nutrition',
    icon: Icons.camera_alt_outlined,
    color: Color(0xFF22C55E),
    behavior: ChatActionBehavior.openMediaPicker,
    mediaMode: ChatMediaMode.camera,
    examplePrompt: 'Analyze this food and estimate calories',
  ),
  'analyze_menu': ChatQuickAction(
    id: 'analyze_menu',
    label: 'Analyze Menu',
    description: 'Photograph a menu for smart picks',
    category: 'Nutrition',
    icon: Icons.menu_book_outlined,
    color: Color(0xFF14B8A6),
    behavior: ChatActionBehavior.openMediaPicker,
    mediaMode: ChatMediaMode.gallery,
    examplePrompt: 'Analyze this menu and suggest healthy options',
  ),
  'quick_workout': ChatQuickAction(
    id: 'quick_workout',
    label: 'Quick Workout',
    description: 'Generate a fast workout on the fly',
    category: 'Workout',
    icon: Icons.flash_on_outlined,
    color: Color(0xFF06B6D4),
    behavior: ChatActionBehavior.sendPrompt,
    prompt: 'Create a quick 15-minute workout for me',
  ),
  'nutrition_advice': ChatQuickAction(
    id: 'nutrition_advice',
    label: 'Nutrition Tips',
    description: 'Get personalized nutrition guidance',
    category: 'Nutrition',
    icon: Icons.restaurant_outlined,
    color: Color(0xFFA855F7),
    behavior: ChatActionBehavior.sendPrompt,
    prompt: 'What should I eat based on my fitness goals?',
  ),
  'compare_form': ChatQuickAction(
    id: 'compare_form',
    label: 'Compare Form',
    description: 'Compare two videos of the same exercise',
    category: 'Form Analysis',
    icon: Icons.compare_outlined,
    color: Color(0xFFF97316),
    behavior: ChatActionBehavior.openMediaPicker,
    mediaMode: ChatMediaMode.video,
    examplePrompt: 'Compare my exercise form between these videos',
  ),
  'recovery_tips': ChatQuickAction(
    id: 'recovery_tips',
    label: 'Recovery Help',
    description: 'Get recovery and rest day advice',
    category: 'Recovery',
    icon: Icons.self_improvement_outlined,
    color: Color(0xFF3B82F6),
    behavior: ChatActionBehavior.sendPrompt,
    prompt: 'I need recovery advice for my muscles',
  ),
  'meal_prep': ChatQuickAction(
    id: 'meal_prep',
    label: 'Meal Prep',
    description: 'Plan your meals for the week',
    category: 'Workout',
    icon: Icons.lunch_dining_outlined,
    color: Color(0xFF22C55E),
    behavior: ChatActionBehavior.sendPrompt,
    prompt: 'Give me a simple high-protein meal prep plan',
  ),
  'injury_help': ChatQuickAction(
    id: 'injury_help',
    label: 'Injury Advice',
    description: 'Get guidance on pain and injuries',
    category: 'Recovery',
    icon: Icons.healing_outlined,
    color: Color(0xFFEF4444),
    behavior: ChatActionBehavior.sendPrompt,
    prompt: 'I have pain in my body, what should I do?',
  ),
  'calorie_check': ChatQuickAction(
    id: 'calorie_check',
    label: 'Calorie Check',
    description: 'Quick photo calorie estimate',
    category: 'Nutrition',
    icon: Icons.local_fire_department_outlined,
    color: Color(0xFFF59E0B),
    behavior: ChatActionBehavior.openMediaPicker,
    mediaMode: ChatMediaMode.camera,
    examplePrompt: 'How many calories are in this food?',
  ),
  // === APP CONTROL ===
  'toggle_dark_mode': ChatQuickAction(
    id: 'toggle_dark_mode',
    label: 'Toggle Dark Mode',
    description: 'Switch between dark and light theme',
    category: 'App Control',
    icon: Icons.dark_mode_outlined,
    color: Color(0xFF6366F1),
    behavior: ChatActionBehavior.sendPrompt,
    prompt: 'Toggle dark mode',
  ),
  'toggle_sounds': ChatQuickAction(
    id: 'toggle_sounds',
    label: 'Toggle Sounds',
    description: 'Mute or unmute all workout sounds',
    category: 'App Control',
    icon: Icons.volume_off_outlined,
    color: Color(0xFF8B5CF6),
    behavior: ChatActionBehavior.sendPrompt,
    prompt: 'Toggle workout sounds',
  ),
  'toggle_tts': ChatQuickAction(
    id: 'toggle_tts',
    label: 'Voice Announcements',
    description: 'Turn voice coach on or off during workouts',
    category: 'App Control',
    icon: Icons.record_voice_over_outlined,
    color: Color(0xFFEC4899),
    behavior: ChatActionBehavior.sendPrompt,
    prompt: 'Toggle voice announcements',
  ),
  // === NAVIGATION ===
  'go_to_stats': ChatQuickAction(
    id: 'go_to_stats',
    label: 'View My Progress',
    description: 'Open your stats and progress dashboard',
    category: 'Navigation',
    icon: Icons.bar_chart_outlined,
    color: Color(0xFF10B981),
    behavior: ChatActionBehavior.sendPrompt,
    prompt: 'Take me to my stats',
  ),
  'go_to_library': ChatQuickAction(
    id: 'go_to_library',
    label: 'Exercise Library',
    description: 'Browse 500+ exercises with form videos',
    category: 'Navigation',
    icon: Icons.fitness_center_outlined,
    color: Color(0xFF0EA5E9),
    behavior: ChatActionBehavior.sendPrompt,
    prompt: 'Open the exercise library',
  ),
  'go_to_schedule': ChatQuickAction(
    id: 'go_to_schedule',
    label: 'Weekly Schedule',
    description: 'View and manage your workout schedule',
    category: 'Navigation',
    icon: Icons.calendar_month_outlined,
    color: Color(0xFFF59E0B),
    behavior: ChatActionBehavior.sendPrompt,
    prompt: 'Show me my weekly schedule',
  ),
  // === TRACKING ===
  'log_water': ChatQuickAction(
    id: 'log_water',
    label: 'Log Water',
    description: 'Track your water intake',
    category: 'Tracking',
    icon: Icons.water_drop_outlined,
    color: Color(0xFF06B6D4),
    behavior: ChatActionBehavior.sendPrompt,
    prompt: 'I drank a glass of water',
  ),
  'set_water_goal': ChatQuickAction(
    id: 'set_water_goal',
    label: 'Set Water Goal',
    description: 'Change your daily water intake target',
    category: 'Tracking',
    icon: Icons.flag_outlined,
    color: Color(0xFF14B8A6),
    behavior: ChatActionBehavior.sendPrompt,
    prompt: 'Set my daily water goal to 8 glasses',
  ),
  // === STATS & REPORTS ===
  'view_report': ChatQuickAction(
    id: 'view_report',
    label: 'Weekly Report',
    description: 'View your AI-generated weekly summary',
    category: 'Stats & Reports',
    icon: Icons.summarize_outlined,
    color: Color(0xFF8B5CF6),
    behavior: ChatActionBehavior.sendPrompt,
    prompt: 'Show me my weekly report',
  ),
  'my_dashboard': ChatQuickAction(
    id: 'my_dashboard',
    label: 'My Dashboard',
    description: 'See this week at a glance',
    category: 'Stats & Reports',
    icon: Icons.dashboard_outlined,
    color: Color(0xFF6366F1),
    behavior: ChatActionBehavior.sendPrompt,
    prompt: 'Show me my dashboard',
  ),
  'my_compliance': ChatQuickAction(
    id: 'my_compliance',
    label: 'Workout Compliance',
    description: 'Check your workout completion rate',
    category: 'Stats & Reports',
    icon: Icons.track_changes_outlined,
    color: Color(0xFF10B981),
    behavior: ChatActionBehavior.sendPrompt,
    prompt: 'How am I doing with my workout compliance this week?',
  ),
  'my_measurements': ChatQuickAction(
    id: 'my_measurements',
    label: 'My Measurements',
    description: 'View body measurement trends',
    category: 'Stats & Reports',
    icon: Icons.straighten_outlined,
    color: Color(0xFFF59E0B),
    behavior: ChatActionBehavior.sendPrompt,
    prompt: 'Show me my body measurement trends',
  ),
  // === COACH INSIGHTS ===
  'progress_check': ChatQuickAction(
    id: 'progress_check',
    label: 'Progress Check',
    description: 'Get AI assessment of your overall progress',
    category: 'Coach Insights',
    icon: Icons.trending_up_outlined,
    color: Color(0xFF22C55E),
    behavior: ChatActionBehavior.sendPrompt,
    prompt: 'Give me an overall progress check - how am I doing?',
  ),
  'deload_check': ChatQuickAction(
    id: 'deload_check',
    label: 'Need a Deload?',
    description: 'Check if you need a recovery week',
    category: 'Coach Insights',
    icon: Icons.battery_charging_full_outlined,
    color: Color(0xFFEF4444),
    behavior: ChatActionBehavior.sendPrompt,
    prompt: 'Based on my readiness and training volume, do I need a deload week?',
  ),
  'adjust_plan': ChatQuickAction(
    id: 'adjust_plan',
    label: 'Adjust My Plan',
    description: 'Ask AI to modify intensity based on recovery',
    category: 'Coach Insights',
    icon: Icons.tune_outlined,
    color: Color(0xFF06B6D4),
    behavior: ChatActionBehavior.sendPrompt,
    prompt: 'Based on my readiness scores and recent workouts, should you adjust my training intensity?',
  ),
};

const defaultChatQuickActionOrder = [
  'check_form',
  'scan_food',
  'analyze_menu',
  'quick_workout',
  'nutrition_advice',
  'compare_form',
  'recovery_tips',
  'meal_prep',
  'injury_help',
  'calorie_check',
  'toggle_dark_mode',
  'toggle_sounds',
  'toggle_tts',
  'go_to_stats',
  'go_to_library',
  'go_to_schedule',
  'log_water',
  'set_water_goal',
  'view_report',
  'my_dashboard',
  'my_compliance',
  'my_measurements',
  'progress_check',
  'deload_check',
  'adjust_plan',
];
