// AUTO-GENERATED by scripts/generate-seo.mjs on every build — do not edit
// by hand. Single source of truth for "how many free tools" everywhere in
// marketing copy (hero, nav, footer, FAQ, marquee). The generator counts
// slugs in src/components/tools/calcRegistry.ts, so adding a tool updates
// every mention sitewide on the next build.
export const FREE_TOOL_COUNT = 62;
